### ISSUE TITLE
File "GCSOLARGENERATIONGLOBALS.GLOBAL.MBIN" does not compile/decompile correctly.

### ISSUE THREAD

**Issue by Galenmacil** [monkeyman192/MBINCompiler#100]
Using NMS Steam buildID 3204363 with MBINCompiler 1.64.0-pre4.

MBINCompiler does not show any errors when decompiling or compiling the file but NMS ignore any modifications I have done to it.

When comparing the EXML decompiled by 1.64.0-pre4 versus the same EXML decompiled by 1.61.0.-pre2 you can spot subtle "unaligned" difference at the end of the file.

**Comment by monkeyman192** [comment]
I cannot see any differences with the current version, so I'll close this under the assumption that it is fixed...
