### ISSUE TITLE
1.57.0.0 Failed to recompress NMS_REALITY_GCTECHNOLOGYTABLE correctly

### ISSUE THREAD

**Issue by carrow26** [monkeyman192/MBINCompiler#102]
For METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN (v1.57), using MBINCOMPILER v1.57.0.0 to decompress then recompress produced a .MBIN that was significantly different to the original. A mod based on an altered NMS_REALITY_GCTECHNOLOGYTABLE.exml did not function correctly.

**Comment by monkeyman192** [comment]
see #103
