### ISSUE TITLE
1.57.0.0 GCCREATUREGLOBALS not recompressed properly

### ISSUE THREAD

**Issue by carrow26** [monkeyman192/MBINCompiler#103]
Using MBINCOMPILER.exe v1.57.0.0 to decompress then recompress /GCCREATUREGLOBALS.MBIN (v1.57) produced a .MBIN that was significantly different to the original (recompressed .MBIN missing a reference to METADATA/SIMULATION/ECOSYSTEM/ROLEDESCRIPTIONTABLES/UNDERWATER/UNDERWATERTABLECOMMON.MXML)

**Comment by monkeyman192** [comment]
We don't really support backward compatibility or previous versions sorry. It's too hard to maintain previous versions.
