### ISSUE TITLE
Compiler error with GCPLAYERGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by kranplatzverdichter** [monkeyman192/MBINCompiler#104]
**Describe the bug**
Drop the GCPLAYERGLOBALS.GLOBAL.MBIN file over MBINCompiler and get the exception "[MbinException]: Failed serializing GcPlayerGlobals to EXML."

**Steps To Reproduce**
1. Drop the GCPLAYERGLOBALS.GLOBAL.MBIN on MBINCompiler.exe
2. The error appears (see Attachments)

 - libMBIN (MBINCompiler) Version: v1.65.0.3
 - NMS Game Version or Steam Build Number: 3251077
 - MBIN File: GCPLAYERGLOBALS.GLOBAL.MBIN
 - MBIN File Version: 1.7

Attachments:
[MBINCompiler1653.log](https://github.com/monkeyman192/MBINCompiler/files/2526758/MBINCompiler1653.log)

**Comment by monkeyman192** [comment]
Many files will be broken with the new 1.7 update. We haven't done any updates for it, so maybe just hold off raising any more issues until we have a 1.7 compatible version uploaded :)

**Comment by monkeyman192** [comment]
most recent release fixes this issue :)
https://github.com/monkeyman192/MBINCompiler/releases/tag/v1.70.0-pre1

**Comment by MuteButtonHero** [comment]
OMG that was fast! Respect!

**Comment by kranplatzverdichter** [comment]
Thank you for the update and this nice tool
