### ISSUE TITLE
Can't decompile some MBIN files

### ISSUE THREAD

**Issue by jensjcs** [monkeyman192/MBINCompiler#106]
1. Just used the NMS Mod Station 1.2.2 to decompile the MBIN files.
2. Needed the Task Manager to end the MBIN Compiler, because of endless loop of MBIN COMPILER

 - libMBIN (MBINCompiler) Version:  1.70.0.1
 - NMS Game Version or Steam Build Number: 1.70
 - MBIN File: DEFAULTREALITY.MBIN
 - MBIN File Version: 1.70.0.1

Can't decompile the DEFAULTREALITY.MBIN, the same for the ATLASPATHTABLE.MBIN and BASECOMPUTERMISSIONTABLE.MBIN

_Attachments:_
LOG:
[VERSION]: MBINCompiler v1.70.0.1
[ARGS]: "convert" "-y" "H:\0_nms_unpacked\METADATA\REALITY\DEFAULTREALITY.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: H:\0_nms_unpacked\METADATA\REALITY\DEFAULTREALITY.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	B28BD7B6E44337F0	template:	cGcRealityManagerData
  

[ERROR]: [AggregateException]: Mindestens ein Fehler ist aufgetreten.

**Comment by monkeyman192** [comment]
I have not yet updated the structs to decompile this file. I'll close this when I have the file decompiling (should be in about 12h...)

**Comment by monkeyman192** [comment]
this is properly fixed in the most recent update:
https://github.com/monkeyman192/MBINCompiler/releases/tag/v1.70.0-pre4
