### ISSUE TITLE
Some UI files don't recompile correctly

### ISSUE THREAD

**Issue by ianm32** [monkeyman192/MBINCompiler#107]
_Fill in the details for each relevant section._
_When you're done, then delete any instructions, example text and irrelevant sections._  
_Please select the project on the sidebar where you encountered the problem._

**Describe the bug**
The specific file I tested is "\UI\HUD\SHIP\SIDESCREENSPEED.MBIN"

I've had crashes attempting to mod several other ship UI files, so they're possibly related.

**Expected behavior**
The file was decompiled and immediately recompiled with no changes made to its contents, then packed into a mod.  In-game, the relevant ship screen is black and the game CTD's when flying.

A hex compare revealed several chunks of differences beyond just the header.  In case it's helpful, a report of that compare is attached.

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 1.70.0-pre3
 - NMS Game Version: Latest Experimental
 - MBIN File: \UI\HUD\SHIP\SIDESCREENSPEED.MBIN
 - MBIN File Version: 

[CompareReport.txt](https://github.com/monkeyman192/MBINCompiler/files/2539802/CompareReport.txt)

**Comment by monkeyman192** [comment]
most recent update should have fixed any issues with UI files:
https://github.com/monkeyman192/MBINCompiler/releases/tag/v1.70.0-pre4
