### ISSUE TITLE
Strip compiler version line

### ISSUE THREAD

**Issue by MuteButtonHero** [monkeyman192/MBINCompiler#108]
I would like an option to strip/not include the compiler version line in EXML files. Example:
--File created using MBINCompiler version (1.70.0)--

The problem is that when running a compare & merge on multiple files this line will cause them to show as different and therefore require a merge. I can strip this line but I'm working with 75+ files so the simplest  solution is to opt out of having it included.

**Comment by monkeyman192** [comment]
can you not get your xml parser to skip comments? That's generally an option?

**Comment by MuteButtonHero** [comment]
Not a necessity, just a convenience. I'm using KDiff3 to walk the directories and do the merge and it won't ignore XML type comments (only C/C++ type) but I can work around it in other ways. 

I can add stripping that line into the python script I'm writing to make the merging of a new release with my mods more automated. If HG is going to maintain a weekly release schedule like Sean said I'm going to be doing a lot of merging and doing it all manually is getting tedious.

**Comment by GaticusHax** [comment]
Stale request.
