### ISSUE TITLE
Unable to decompile NMS_REALITY_GCPRODUCTTABLE

### ISSUE THREAD

**Issue by destrofer** [monkeyman192/MBINCompiler#110]
**Describe the bug**
MBINCompiler fails to decompile `METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN` with this message:
```
Auto-Detected --input-format=MBIN
Converting d:\Editing\my-mod-system\NoMansSky\tmp\METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.

  [INFO]: d:\Editing\my-mod-system\NoMansSky\tmp\METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN

[ERROR]: [AggregateException]: One or more errors occurred.
```

**Expected behavior**
`METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN` should get decompiled to `METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.EXML`

**Steps To Reproduce**
1. Unpack original `NMS_REALITY_GCPRODUCTTABLE.MBIN` from `NMSARC.515F1D3.pak` using `psarc`.
2. Run command `MBINCompiler.exe METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN`

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: [eg 1.71.0.1]
 - NMS Steam Build Number: 3325157
 - MBIN File: METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN
 - MBIN File Version: don't know

**MBINCompiler.log**
```
[VERSION]: MBINCompiler v1.71.0.1
[ARGS]: "tmp\METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: d:\Editing\my-mod-system\NoMansSky\tmp\METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	24413570DF127C76	template:	cGcProductTable
  

[ERROR]: [AggregateException]: One or more errors occurred.
```

**Comment by monkeyman192** [comment]
damn, give us a bit of time to update mbincompiler first!! We are working on it!!
I'll have this fixed later today

**Comment by sdgabai** [comment]
This was the first place that I found to write you a message, monkeyman192.
My husband and I are avid NMS gamers w/ about 400+ & 800+ hours each [some are AFK hours lol]
By this point, we have come to love the 30+ mods we were using in 1.71 NMS, and welcome VISIONS inclusions of a lot of the "visions" of the modders in the community. For the most part, these were powered by those that supported you in the creation of the MBinCompiler project series. Please stay in good health! We worry about you. :D We hope you have all the support you need to keep this project going long term. Many count on you. My programming skills are archaic; but, they are decent. If I can be of some help at some level; I'd like to help too. Proper nutrition and rest can cut down on fatigue, mistakes, stress, and wasted time. Good luck, thanks, and Happy Holidays!
Stephanie & Bob

**Comment by Shyressa** [comment]
This is for the same file and the Visions 1.75 HF released on 11/22, and running v1.75.0-pre2 of MBinCompiler.  Hope this helps.

[VERSION]: MBINCompiler v1.75.0.2
[ARGS]: "F:\NMS Modding\MBINCompiler-175\NMS_REALITY_GCPRODUCTTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: F:\NMS Modding\MBINCompiler-175\NMS_REALITY_GCPRODUCTTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	24413570DF127C76	template:	cGcProductTable
  

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcProductTable from MBIN.
[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by Shyressa** [comment]
The pre3 version has fixed this issue and it is now decompiling and compiling correctly.

**Comment by destrofer** [comment]
Thanks a lot! You're the greatest! :)

**Comment by knzai** [comment]
pre4 has the problem as well, but I'll try pre3 and see if that works for that file. Thanks!

**Comment by knzai** [comment]
nvm, it has having trouble with NMS_REALITY_GCPROCPRODUCTTABLE when the non proc one is likely the one I need.
