### ISSUE TITLE
List of Structs broken with 1.75 update

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#111]
### New structs:

- [x] cGcAtlasRecvTotalContribution	95AC0992C92BD05E
- [x] cGcAtlasSendRequestTotalContribution	0DC9B438A409E6F01
- [x] cGcBaseBuildingEntryLinkGridData	0ABF17392D4C2F9F4
- [x] cGcBiomeFileListOption	0C44DEAC47C50A412
- [x] cGcBiomeSubType	0B6773AD60EFCB088
- [x] cGcCreatureCrystalBiomeMovementData	4A9B3DFF84E1DF84
- [x] cGcCreatureCrystalMovementData	0ABC096FCF4596D62
- [x] cGcCreatureWeirdMovementData	495ADF9A25F53FEF
- [x] cGcCustomisationColourPalettes	0FEB57F7A1D0FB6A8
- [x] cGCHUDEffectRewardData    DB92FE50460E2D1F
- [x] cGcMessageFiendCrime	5873ED86AF6E466E
- [x] cGcNameGeneratorWord	0B53BA0DB9BED6F2B
- [x] cGcPlanetDataResourceHint	78E22E9728E307D2
- [x] cGcPlanetWaterColourData	4DDC814768F6A7A4
- [x] cGcProceduralProductWord	3E71C0C038386682
- [x] cGcRainbowType	0B9CF7DBD6666BED1
- [x] cGcRewardCommunityContribution	89B5232517B88E96
- [x] cGcSimpleIkRecoilComponentData	2F34AAE6D58F523F
- [x] cGcStormEvent	19F9D2AE2B03DFA4
- [x] cGcWaterColourSettingList	0DDF10BFCF81EB27B
- [x] cGcWeirdCreatureRewardList	3147BCDA0F39A1E0

### Structs with internal changes:

- [x] cGcAIShipSpawnData	0FD03DF836E7D27C9
- [x] cGcAlienPuzzleEntry	44F07E6FA55CE844
- [x] cGcAlienPuzzleOption	2E3653CFA46A2238
- [x] cGcAlienPuzzleTable	0FEAF1D567D35E0EB
- [x] cGcAtlasSendSubmitContribution	6A9DDB8006A4E264
- [x] cGcAudioAreaTriggerComponentData	0ABC949FBB8C4C860
- [x] cGcAudioWwiseEvents	0F5449A0A2D4BBC97
- [x] cGcBiomeFileList	73D64DB7C6194A4A
- [x] cGcBiomeFileListOptions	0EA40F91AFC046B6C
- [x] cGcBountySpawnInfo	2F48B90E90863990
- [x] cGcButtonSpawn	77F262AF87D87FAF
- [x] cGcButtonSpawnTable	53A21967B8EFF6FB
- [x] cGcCreatureAlertData	9C0901BDD017D265
- [x] cGcCreatureData	0D82919CD8001FE4A
- [x] cGcCreatureDataTable	0AF797A9974247C34
- [x] cGcCreatureFilenameTable	0D3A2D6582C011CE1
- [x] cGcCreatureNearbyEvent	82607315D11C8BA8
- [x] cGcCreatureRoleDataTable	0E94464E2EAD600D7
- [x] cGcCreatureRoleDescriptionTable	82060166C6BEF63B
- [x] cGcCreatureSpawnComponentData	5C45360A79CFEBB8
- [x] cGcCreatureTypes	6971D929A87B9FEA
- [x] cGcDefaulMissionProduct	2E0F99255E9355DF
- [x] cGcDefaultMissionItemsTable	62B7549F9EF7703E
- [x] cGcEncounterComponentData	52049EC71382D2EC
- [x] cGcEnvironmentSpawnData	0A98E71737595CAB3
- [x] cGcExperienceSpawnTable	7BE33229BF7C53AA
- [x] cGcExplosionData	0BD4B2DD33ACBD5DA
- [x] cGcExplosionDataTable	145858E7D95F4962
- [x] cGcExternalObjectFileList	8DD8A6B4B649C764
- [x] cGcExternalObjectList	89EA24456BA01812
- [x] cGcFiendCrime	23F63688C28E979D
- [x] cGcFiendCrimeAction	59FDEDC6EC119BDF
- [x] cGcFiendCrimeSpawnData	7E08D2891797A237
- [x] cGcFiendCrimeSpawnTable	0A5790FF9AE6AF9EA
- [x] cGcGalaxyAudioSetupData	23EF1D70E5FBC202
- [x] cGcGenericMissionSequence	4B534E3F4D0D8228
- [x] cGcGrabPlayerComponentData	44311A411BF5EAE7
- [x] cGcHUDStartup	0C4158197BE4B0753
- [x] cGcHUDStartupTable	32650BDE9A30FBD2
- [x] cGcInteractionComponentData	6D20427FAFEA9820
- [x] cGcInteractionType	3B27FE5DC612D9FB
- [x] cGcInventorySlotActionData	0E61FE2C17D2233F
- [x] cGcLaserBeamData	85EE8A13FE8A3505
- [x] cGcMarkerComponentData	45AA7B4042BDC4D9
- [x] cGcMissionConditionHasProduct	5004ED048AD3F0FB
- [x] cGcMissionConditionProductKnown	9E151D13F3E402FF
- [x] cGcMissionSequenceAudioEvent	0B6F31CE03523BF82
- [x] cGcMissionSequenceCollectProduct	0CE7178114DD7D496
- [x] cGcMissionSequenceShowMessage	4FA17818676378A7
- [x] cGcMissionTable	8F9E2FA26ADDA411
- [x] cGcNPCPlacementInfo	0E066BDFEA3FD5467
- [x] cGcNPCSpawnTable	9DE4BACE6CA69877
- [x] cGcPlanetGenerationInputData	0DE8BF371F6565035
- [x] cGcPlanetWeatherData	0F03B9BCEB3DF5278
- [x] cGcPlayerEmoteList	0CE7049D622C53DCA
- [x] cGcProceduralProductCategory	0F9F81B6AD39F86F3
- [x] cGcProceduralTechnologyTable	0C7B22AB8DA40AAEB
- [x] cGcProductData	4408162C9D554F85
- [x] cGcProductTable	24413570DF127C76
- [x] cGcProjectileData	0B0910434295E49F1
- [x] cGcProjectileDataTable	0E515E3E3D6D7C2BD
- [x] cGcPurchaseableSpecials	0DE430B92BA2F7D3E
- [x] cGcRealityGameIcons	0E99CEE3335E8D533
- [x] cGcRewardIncrementInteractionIndex	749F7CA4A4583762
- [x] cGcRewardProceduralProduct	0B1927A9D53D2F6C8
- [x] cGcScanEventData	0A7FD6DC2D2C673AC
- [x] cGcScanEventTable	9987FBD45541267F
- [x] cGcScannableComponentData	0ED588DAE8AEBA7D1
- [x] cGcScannerIconTypes	40ABD329BE41172E
- [x] cGcSolarSystemData	0E5A2E6412933D6B3
- [x] cTkActionButtonLookup	6A901CD00C8B3BBF
- [x] cTkActionButtonMap	0D0BF3BAF4263B9DA
- [x] cTkInputEnum	0F701733D06A2222E
- [x] cTkMaterialData	131B3F6891FE771C	
- [x] cTkMaterialFlags	0B23908E7B2B205DF
- [x] cTkMaterialMetaData	0F111D25A1967E8F3				fixme!!!

### Structs with a file size change:

- [x] cGcBaseBuildingEntry	old: 0x228	new: 0x220	GUID: 0AB745621068EB93B
- [x] cGcBaseBuildingTable	old: 0x19F0	new: 0x1A00	GUID: 8BF3CBE8570EB1DA
- [x] cGcBiomeData	old: 0x340	new: 0x4F0	GUID: 0F0E5EFEAA98B886C
- [x] cGcBiomeListPerStarType	old: 0x158	new: 0x15C	GUID: 0C41550066972A7DF
- [x] cGcCreatureFilename	old: 0x90	new: 0x110	GUID: 941C900F4BF1D0B
- [x] cGcCreatureRoleData	old: 0x510	new: 0x550	GUID: 0BD1B2070692ABD58
- [x] cGcCreatureRoleDescription	old: 0x40	new: 0x60	GUID: 0EEECA4CD639B4B32
- [x] cGcCreatureRoleFilenameTable	old: 0x140	new: 0x280	GUID: 0D049F5710295C1E0
- [x] cGcCreatureSpawnData	old: 0x598	new: 0x860	GUID: 0A2A7D9766212FC6B
- [x] cGcDefaultSaveData	old: 0x25CD0	new: 0x25CF0	GUID: 0A7B446FEA81D5252
- [x] cGcDestroyAction	old: 0x1	new: 0x18	GUID: 58C7698795121554
- [x] cGcDestructableComponentData	old: 0x160	new: 0x198	GUID: 15C3E631C67A521C
- [x] cGcExternalObjectListOptions	old: 0x40	new: 0x50	GUID: 2CFDA1347C0D985F
- [x] cGcMissionConditionRefinerActive	old: 0x88	new: 0x30	GUID: 0C2EECD23AFF2DBC4
- [x] cGcNGuiLayerData	old: 0x310	new: 0x320	GUID: 7C767D18FDA6CB96
- [x] cGcPerformanceGuard	old: 0x4	new: 0x8	GUID: 39A24470DAF09705
- [x] cGcPlanetData	old: 0x3BB0	new: 0x3BE0	GUID: 0B66E8264B53F0C36
- [x] cGcPlanetGenerationIntermediateData	old: 0x3D0	new: 0x450	GUID: 58BCE0F06F70CC01
- [x] cGcPlanetWaterData	old: 0x1D0	new: 0x180	GUID: 0EE35B5C5F8B515B0
- [x] cGcPlayerCharacterState	old: 0x78	new: 0xA8	GUID: 0FAC1A85D2BC41DE
- [x] cGcPlayerEmote	old: 0x100	new: 0x128	GUID: 0AF5616FFEC6C1D13
- [x] cGcPlayerFullBodyIKComponentData	old: 0x1E0	new: 0x1F0	GUID: 8D3C85E56A8668D8
- [x] cGcPlayerStateData	old: 0x25C50	new: 0x25C70	GUID: 0AA97AB5C8FE2F135
- [x] cGcProceduralProductData	old: 0x4C0	new: 0x830	GUID: 0BB6A74EA89F6BCC
- [x] cGcProceduralProductTable	old: 0x10	new: 0x5A10	GUID: 0A445AFD8463EAB2
- [x] cGcProceduralTechnologyData	old: 0x280	new: 0x290	GUID: 13E923D49B616ECC
- [x] cGcProductProceduralOnlyData	old: 0x38	new: 0x148	GUID: 2DF4B2BD8E92EEA7
- [x] cGcPurchaseableSpecial	old: 0x18	new: 0x20	GUID: 2222AFDB29769EBA
- [x] cGcRealityManagerData	old: 0xAB30	new: 0xABC0	GUID: 892501428CFD27EC
- [x] cGcRefinerRecipe	old: 0xB0	new: 0x50	GUID: 0B724C69807198B4F
- [x] cGcRewardModifyStat	old: 0x18	new: 0x30	GUID: 94B1F64B650A15E0
- [x] cGcShootableComponentData	old: 0x78	new: 0x80	GUID: 14A50F19D60AD726
- [x] cGcSimpleInteractionComponentData	old: 0x138	new: 0x168	GUID: 0D1F6EF24C10C40CC
- [x] cGcTerrainControls	old: 0x74	new: 0x78	GUID: 1E15DB90CA3FBF5B
- [x] cGcThirdPersonAnimParams	old: 0x50	new: 0x58	GUID: 55B27ACF9CD7B77B
- [x] cGcUserSettingsData	old: 0x38F0	new: 0x38F8	GUID: 16AF75AD89EF15F2
- [x] cGcWeatherProperties	old: 0x610	new: 0x620	GUID: 0BF89A1534A8662A1

**Comment by GaticusHax** [comment]
Can't edit the todo list :/
GcDebugOptions and GcWaterGlobals are done

**Comment by voodooo3** [comment]
Hello,
seems that cGcPlayerGlobals is not decompiling and is missing from this list.

Tested with v1.75.0-pre2 and v1.75.0-pre1.

keep up the good work! :)

**Comment by GaticusHax** [comment]
Thanks voodooo3
The globals are not listed here but that is normal. They are handled differently.
Here is a list of the broken globals:

- [x] cGcDebugOptions 21676C20AFF3CCB8
- [x] cGcWaterGlobals F5BC9F27DFFC1970
- [x] cGcBuildingGlobals 6FE36EAD5A79276C
- [x] cGcCameraGlobals 5D17CCC0EA2A7E40
- [x] cGcCreatureGlobals 49FCFC6FC5219F15
- [x] cGcPlayerGlobals 323F208221BE947D
- [x] cGcSkyGlobals	796B976A7C9297E9
- [x] cGcGalaxyGlobals E44F8EA503FCA519
- [x] cGcGameplayGlobals C78D17FE2EF366D8
- [x] cGcSpaceshipGlobals 48F08DADC5C494F3
- [x] cGcUIGlobals D7AD6AC27F76443B
- [x] cGcTerrainGlobals D5017D9BF917053E
- [x] cGcVehicleGlobals BC8FE511DDCD0705

**Comment by sdgabai** [comment]
I don't know how I can be of help; but, I'd like to try. Most of my programming skills are from 30 years ago. Only some of them have been upgraded to the more modern stuff; but, I understand basic software design and software linguistics if you want to call it that. How may I be of help?

**Comment by GaticusHax** [comment]
Hi @sdgabai
It's appreciated. Join us on the NMS Modding Discord to discuss.
https://discord.gg/xekBEJw
