### ISSUE TITLE
GCDEBUGOPTIONS.GLOBAL.MBIN no longer compiles

### ISSUE THREAD

**Issue by jay33721** [monkeyman192/MBINCompiler#112]
GCDEBUGOPTIONS.GLOBAL.MBIN from game version 1.77 does not compile with the latest version of MBINCompiler (1.75.0-pre4).

Error Message:

Auto-Detected --input-format=MBIN
Converting D:\Games\Steam\steamapps\common\No Man's Sky\NMSMS\Proj\No Random Sentinels 1.77\GCDEBUGOPTIONS.GLOBAL.MBIN

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.

  [INFO]: D:\Games\Steam\steamapps\common\No Man's Sky\NMSMS\Proj\No Random Sentinels 1.77\GCDEBUGOPTIONS.GLOBAL.MBIN

[ERROR]: [AggregateException]: One or more errors occurred.

Press any key to continue . . .

.log file attached:
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/2683093/MBINCompiler.log)

**Comment by theFisher86** [comment]
@jay33721 MBINCompiler v 1.75.0-pre4 is for Game Version 1.75... you'll need to wait until MBINCompiler v 1.77 comes out for it to reliably decompile 1.77 game files.  Granted, a lot of 1.77 files will probably decompile with 1.75 but nothing is guaranteed.
