### ISSUE TITLE
File not recognized after patch 1.77

### ISSUE THREAD

**Issue by roie-r** [monkeyman192/MBINCompiler#113]
Hi, the latest patch 1.77 made changes and some files are not recognized any more - using your latest 1.75.0.4 build.

So far, the one I found is **GCCAMERAGLOBALS**:
```
Auto-Detected --input-format=MBIN
Converting D:\NMS_Unpacked\GCCAMERAGLOBALS.GLOBAL.MBIN
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
[INFO]: D:\NMS_Unpacked\GCCAMERAGLOBALS.GLOBAL.MBIN
[ERROR]: [AggregateException]: One or more errors occurred.
```

**Comment by DireHo** [comment]
There are a lot more files that cannot be decompiled after 1.77, unfortunately.

**Comment by roie-r** [comment]
Thanx for the update :)
