### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by DireHo** [monkeyman192/MBINCompiler#114]
Hi
Would it be possible to update the compiler to open this file? 

Auto-Detected --input-format=MBIN
Converting E:\nms MODDING\game files\METADATA\REALITY\TABLES\NMS_REALITY_GCPROCPRODUCTTABLE.MBIN
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
[INFO]: E:\nms MODDING\game files\METADATA\REALITY\TABLES\NMS_REALITY_GCPROCPRODUCTTABLE.MBIN
[ERROR]: [AggregateException]: One or more errors occurred.

MBIN v1.77.0-pre1, file from NMS 1.77.

**Comment by monkeyman192** [comment]
That is the old version of the file, so it cannot be opened. Open the normal ProductTable instead.
