### ISSUE TITLE
GCGAMEPLAYGLOBALS.GLOBAL.MBIN Errors

### ISSUE THREAD

**Issue by Kyle4G** [monkeyman192/MBINCompiler#122]
Compiler gives the attachers errors:
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3510207/MBINCompiler.log)

**Comment by Yolo56** [comment]
You are not using the last version of MbinCompiler - Release 4 was release
But even with that version, it wont work. Exemple with GCDEBUGOPTIONS.GLOBAL.MBIN

[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3510294/MBINCompiler.log)

**Comment by monkeyman192** [comment]
Please read the release notes in the [releases](https://github.com/monkeyman192/MBINCompiler/releases)
As you will see globals aren't functioning yet and I know this. They have been added to the list in #119 so they aren't expected to work until they are ticked off that list
