### ISSUE TITLE
Compilation Failed on EXPERIENCESPAWNTABLE

### ISSUE THREAD

**Issue by echthesia** [monkeyman192/MBINCompiler#123]
**Describe the bug**
When I attempt to compile METADATA/SIMULATION/SCENE/EXPERIENCESPAWNTABLE.MBIN (or .EXML rather) which is checked as complete in Issue 119, compilation fails with an InvalidGUIDException and an instruction to submit an issue on GitHub. This occurs even on the vanilla file without even opening the file between decompilation (which works fine) and recompilation.

**Expected behavior**
The EXML should be compiled to MBIN.

**Steps To Reproduce**
Attempt to compile any EXPERIENCESPAWNTABLE.EXML.

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 2.0.4pre4
 - NMS Game Version or Steam Build Number: 2.06
 - MBIN File: EXPERIENCESPAWNTABLE.MBIN
 - MBIN File Version: 2.0.4

**Additional Information**
Add any other information here that you think might be helpful.

_Attachments:_
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3510352/MBINCompiler.log)

**Comment by monkeyman192** [comment]
Thanks!
This will be fixed in the next release coming in a few hours from this comment...
