### ISSUE TITLE
Mods in VR Not Working - Looking for a File - Help?

### ISSUE THREAD

**Issue by glitchi256** [monkeyman192/MBINCompiler#124]
**Is your feature request related to a problem? Please describe.**
Whenever anyone tries to load mods with VR, the game is locking up on a black screen. Music can be heard but nothing can be interacted with. The theory right now is that the mod warning screen is popping up, but in VR you cant interact with it. Keypresses dont work, nor does mouse or VR controls.

**Describe the solution you'd like**
Im looking for the file associated with this message so I can try to remove it. If I can remove the warning all together from appearing, it might be possible to circumvent this and get mods working in VR.

**Describe alternatives you've considered**
I dont know if this can be done through modding an MBIN file or not. I feel like there might be a setting in a file somewhere that is as simple as "Showmodwarning?" with a 0 or 1 value that I can just turn off, but it might be more involved. Asking here because I assume people here know the game inside out.

**Comment by monkeyman192** [comment]
This is something that is controlled by the exe itself. It isn't possible to modify any mbin files to remove this warning, however it is possible to patch the game so that the screen doesn't show up. This patch has not (as far as I am aware) been made for Beyond yet.

**Comment by glitchi256** [comment]
Yeah I saw the old mod online but author hid it so I dont know what they
did. Would it involve modding the exe with a hex editor or a dll? Sounds
over my head but Im exploring options, Id really like to get these mods
working in VR would massively improve the experience.
