### ISSUE TITLE
Error compiling DEFAULTSAVEDATA.MBIN 

### ISSUE THREAD

**Issue by 7redstarkiller** [monkeyman192/MBINCompiler#125]
The MBIN decompiler errors when trying to decompile DEFAULTSAVEDATA.MBIN 

 - libMBIN (MBINCompiler) Version: [eg 2.0.6.2]
 - NMS Game Version or Steam Build Number: Beyond (2.0)
 - MBIN File:  DEFAULTSAVEDATA.MBIN 
 - MBIN File Version: [eg 2.0.6.2]

The log reads:

[VERSION]: MBINCompiler v2.0.6.2
[ARGS]: "C:\Users\Tristan\Desktop\No Man's Sky Modding\Unpacked Files\METADATA\GAMESTATE\DEFAULTSAVEDATA.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcDefaultSaveData from MBIN.
[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x1418

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by monkeyman192** [comment]
Thanks for letting me know. The issue will be fixed in the next release :)
