### ISSUE TITLE
Error Decompiling GCUIGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by Coop25** [monkeyman192/MBINCompiler#126]
**Describe the bug**
when i try to decompile GCUIGLOBALS.GLOBAL.MBIN i get the following message

```
[VERSION]: MBINCompiler v2.0.6.3
[ARGS]: "convert" "-y" "E:\A-Nms-Mod-Tools\Project\two\GCUIGLOBALS.GLOBAL.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: E:\A-Nms-Mod-Tools\Project\two\GCUIGLOBALS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	B0A618899754E7E2	template:	cGcUIGlobals
  

[ERROR]: [AggregateException]: One or more errors occurred.
```

**Expected behavior**
I was expecting a decompiled EXML file

**Steps To Reproduce**
1. attempt to drag and drop GCUIGLOBALS.GLOBAL.MBIN onto MBINCompiler.exe

**Comment by birb3D** [comment]
I am also having an issue with this but a different error:
>  [VERSION]: MBINCompiler v2.0.6.3
> [ARGS]: "I:\NMSMods\GCGAMEPLAYGLOBALS.GLOBAL.MBIN"
> 
> If you encounter any errors, please submit a bug report and include this log file.
> Please check that there isn't already a similar issue open before creating a new one.
> https://github.com/monkeyman192/MBINCompiler/issues
> 
> [INFO]: Auto-Detected --input-format=MBIN
> [INFO]: --input-format=MBIN --output-format=EXML
> 
> [ERROR]: [AggregateException]: One or more errors occurred.
> [MbinException]: Failed serializing GcGameplayGlobals to EXML.
> [InvalidOperationException]: There was an error generating the XML document.
> [ArgumentException]: '', hexadecimal value 0x06, is an invalid character.
> 
>    at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
>    at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
>    at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
>    at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
>    at System.Xml.XmlWellFormedWriter.WriteString(String text)
>    at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
>    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)

**Comment by monkeyman192** [comment]
These globals are not supported yet. To see what is see [this list](https://github.com/monkeyman192/MBINCompiler/issues/119)
