### ISSUE TITLE
Does not extract the file METADATA\UI\HUD\SCANNERICONS.MBIN

### ISSUE THREAD

**Issue by strudo76** [monkeyman192/MBINCompiler#127]
**Describe the bug**
Give error when attempting to extract the file
Auto-Detected --input-format=MBIN
Converting D:\NMS_Modding\MyMods\BeyondMod_208A_ScannerIcons\METADATA\UI\HUD\SCANNERICONS.MBIN
[ERROR]: [AggregateException]: One or more errors occurred.

Press any key to continue . . .

**Expected behavior**
Produce a valid EXML file

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: [2.0.6-pre3]
 - NMS Game Version or Steam Build Number: [2.08A]
 - MBIN File: [METADATA\UI\HUD\SCANNERICONS.MBIN]
 - MBIN File Version: [eg 1.0.0.0]

**Comment by monkeyman192** [comment]
Thanks for that. It will be fixed in the next release!
