### ISSUE TITLE
Failed to read TkAttachmentData from LANDINGDATA.ENTITY.MBIN

### ISSUE THREAD

**Issue by Sycholic** [monkeyman192/MBINCompiler#131]
_Fill in the details for each relevant section._
Latest Version of both MBIN and NMSMS and fresh unpack (ie. everything up to date within a 1/2hr of posting time)

[VERSION]: MBINCompiler v2.0.9.2
[ARGS]: "convert" "-y" "-f" "D:\nms_mymods\LandingPadFix\MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\TECH\LANDINGPAD\ENTITIES\LANDINGDATA.ENTITY.MBIN"

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [MbinException]: Failed to read TkAttachmentData from MBIN.
  [InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x260
  
  [INFO]: D:\nms_mymods\LandingPadFix\MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\TECH\LANDINGPAD\ENTITIES\LANDINGDATA.ENTITY.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	87068490DC83B1C1	template:	cTkAttachmentData
  
     at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read TkAttachmentData from MBIN.
  [FILE]: D:\nms_mymods\LandingPadFix\MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\TECH\LANDINGPAD\ENTITIES\LANDINGDATA.ENTITY.MBIN
  
[INFO]: TIME: 0.057 seconds

Sorry for the poor formatting copy/pasted directly from the MBIN log in mod station

**Comment by monkeyman192** [comment]
Ok, after having a look, it seems this issue is because you are trying to decompile an older version of the file.
Not sure how you ended up having an old version if your files were recently unpacked, but I get that exact error you do when unpacking a 2.0.6 version of the file. The current 2.0.9-era file decompiles perfectly fine with the current version of MBINCompiler.
