### ISSUE TITLE
CREATUREDATATABLE.MBIN recompile issue

### ISSUE THREAD

**Issue by Sycholic** [monkeyman192/MBINCompiler#133]
Not sure what going on.  someone was having trouble and we figured out mbin is being bad some reason..  apparently after decompiling the mbin, editing the exml, then recompiling it. the recompiled file is not correct as you cant decompile it again, got the logs I tried it on both 2.0.9.2 and 2.0.10.1 so not sure what going on.

decompile:  METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN
edit creature max scale from 1.5 to 30.0
recompile file then try to decompile it again to verify

Log files of error:
[VERSION]: MBINCompiler v2.0.10.1
[ARGS]: "convert" "-y" "-f" "D:\nms_mymods\testies\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN"

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [MbinException]: Failed to read GcCreatureDataTable from MBIN.
  [InvalidListException]: Invalid list read, magic 4E44525F expected xxxxxx01 at 0x6598
  
  [INFO]: D:\nms_mymods\testies\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN
  [INFO]: MBIN	version:	2.0.10.1	guid:	AF797A9974247C34	template:	cGcCreatureDataTable
  
     at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read GcCreatureDataTable from MBIN.
  [FILE]: D:\nms_mymods\testies\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN
  
[INFO]: TIME: 0.053 seconds

[VERSION]: MBINCompiler v2.0.9.2
[ARGS]: "convert" "-y" "-f" "D:\nms_mymods\testies\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN"

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [MbinException]: Failed to read GcCreatureDataTable from MBIN.
  [InvalidListException]: Invalid list read, magic 4E44525F expected xxxxxx01 at 0x6598
  
  [INFO]: D:\nms_mymods\testies\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN
  [INFO]: MBIN	version:	2.0.10.1	guid:	AF797A9974247C34	template:	cGcCreatureDataTable
  
     at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read GcCreatureDataTable from MBIN.
  [FILE]: D:\nms_mymods\testies\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN
  
[INFO]: TIME: 0.052 seconds

**Comment by monkeyman192** [comment]
Thanks for this! It will be fixed in the next release
