### ISSUE TITLE
Failed serializing with invalid character

### ISSUE THREAD

**Issue by XavBX** [monkeyman192/MBINCompiler#135]
**Describe the bug**
Can't convert **GCUIGLOBALS.GLOBAL.MBIN** file to EXML. A failed serializing issue occured.

> ⚠️ _French environment. But the character which generate the issue are not a french character. Same problem with the game downloaded in English._

**Steps To Reproduce**
1. Copy **GCUIGLOBALS.GLOBAL.MBIN** in a folder
2. Launch convert function with args : **"-y"** and **"-f"** on the file
3. Warning detected : **File not recognized**
4. Error occured : **Failed serializing on the file**

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: **v2.0.10.1**
 - Steam Build Number: 4153226 (_lastest version available on Steam_)
 - MBIN File: **GCUIGLOBALS.GLOBAL.MBIN**
 - MBIN File Version: lastest version from games download (_Steam version_)

**Additional Information**
Log file : [MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3563222/MBINCompiler.log)

**Comment by XavBX** [comment]
There is this thread on StackOverflow that could solve the problem : [Treating strings for insertion into XElement](https://stackoverflow.com/questions/12943740/treating-strings-for-insertion-into-xelement)

The solution sound like a replacement of all characters bellow 0x20 by their XML unicode codes :
```c#
    static Lazy<Regex> ControlChars = new Lazy<Regex>(() => new Regex("[\x00-\x1f]", RegexOptions.Compiled));

    private static string FixData_Replace(Match match)
    {
        if ((match.Value.Equals("\t")) || (match.Value.Equals("\n")) || (match.Value.Equals("\r")))
            return match.Value;

        return "&#" + ((int)match.Value[0]).ToString("X4") + ";";
    }

    public static string Fix(object data, MatchEvaluator replacer = null)
    {
        if (data == null) return null;
        string fixed_data;
        if (replacer != null) fixed_data = ControlChars.Value.Replace(data.ToString(), replacer);
        else fixed_data = ControlChars.Value.Replace(data.ToString(), FixData_Replace);
        return fixed_data;
    }
```

Could you check that, please.

**Comment by XavBX** [comment]
I add this 2 functions in NMSTemplate.cs : 
```c#
        private static string FixData_Replace(Match match)
        {
            if ((match.Value.Equals("\t")) || (match.Value.Equals("\n")) || (match.Value.Equals("\r")))
                return match.Value;

            return "&#" + ((int)match.Value[0]).ToString("X4") + ";";
        }

        public static string Fix(object data, MatchEvaluator replacer = null)
        {
            Lazy<Regex> ControlChars = new Lazy<Regex>(() => new Regex("[\x00-\x1f]", RegexOptions.Compiled));
            if (data == null) return null;
            string fixed_data;
            if (replacer != null) fixed_data = ControlChars.Value.Replace(data.ToString(), replacer);
            else fixed_data = ControlChars.Value.Replace(data.ToString(), FixData_Replace);
            return fixed_data;
        }
```

And call it in SerializeEXmlValue function for String value : 
```c#
switch (fieldType.Name)
{
        case "String":
                valueString = Fix(value?.ToString() ?? "");
```

Result : Work fine for write the EXML file. But I have now bad some characters, like that : 
```xml
    <Property name="Anim" value="��Y?��&amp;#0019;?" />
```

Need to improve this fix 😄

**Comment by monkeyman192** [comment]
The issue is that I haven't yet mapped out the template for the struct. It will be done soon.
The "File not recognized" gives that away ;)
