### ISSUE TITLE
Can't decompile NMS_REALITY_GCTECHNOLOGYTABLE.MBIN

### ISSUE THREAD

**Issue by porlock2** [monkeyman192/MBINCompiler#138]
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3563886/MBINCompiler.log)
[NMS_REALITY_GCTECHNOLOGYTABLE.zip](https://github.com/monkeyman192/MBINCompiler/files/3563887/NMS_REALITY_GCTECHNOLOGYTABLE.zip)

Last experimental update.

**Comment by monkeyman192** [comment]
This is fixed in the most recent release
