### ISSUE TITLE
Experimental update 2019-09-12: tables unrecognized

### ISSUE THREAD

**Issue by Berbe** [monkeyman192/MBINCompiler#142]
Following the [Experimental Branch 12/09](https://steamcommunity.com/app/275850/discussions/0/2952595757880068564/) update, some tables seem to fail to be parsed correctly:
```
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
[FILE]: CONSUMABLEITEMTABLE.MBIN

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
[FILE]: NMS_DIALOG_GCALIENPUZZLETABLE.MBIN
```
**Specs (please complete the following information, if applicable):**
 - MBINCompiler [v2.0.11-pre1](https://github.com/monkeyman192/MBINCompiler/releases/tag/v2.0.11-pre1)
 - NMS Game Version or Steam Build Number: `4190270`
 - MBIN Files: `METADATA/REALITY/TABLES`

**Attachments:**
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3607582/MBINCompiler.log)

**Comment by monkeyman192** [comment]
This is now covered by #143 thanks :)

**Comment by Berbe** [comment]
Thank you for your work! (o:
