### ISSUE TITLE
.ANIM.MBIN files won't decompile since BEYOND

### ISSUE THREAD

**Issue by EthanRDoesMC** [monkeyman192/MBINCompiler#151]
Every ANIM.MBIN file from BEYOND I have tried to decompile has failed. This has been consistent with multiple BEYOND game versions and mbincompiler versions. 

Example log:
[VERSION]: MBINCompiler v2.0.13.1
[ARGS]: "convert" "-y" "-f" "D:\NMSMods\Beyond\BeyondProjects\Nyooom\MODELS\COMMON\SPACECRAFT\FIGHTERS\ANIMS\COCKPIT_A_HATCH_OPEN.ANIM.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [MbinException]: Failed to read TkAnimMetadata from MBIN.
  [EndOfStreamException]: Unable to read beyond the end of the stream.
  
  [INFO]: D:\NMSMods\Beyond\BeyondProjects\Nyooom\MODELS\COMMON\SPACECRAFT\FIGHTERS\ANIMS\COCKPIT_A_HATCH_OPEN.ANIM.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	3CD7D2192958BA6C	template:	cTkAnimMetadata
  
     at System.IO.__Error.EndOfFile()
     at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
     at System.IO.BinaryReader.ReadSingle()
     at libMBIN.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
     at libMBIN.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
     at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read TkAnimMetadata from MBIN.
  [FILE]: D:\NMSMods\Beyond\BeyondProjects\Nyooom\MODELS\COMMON\SPACECRAFT\FIGHTERS\ANIMS\COCKPIT_A_HATCH_OPEN.ANIM.MBIN
  
[INFO]: TIME: 0.046 seconds

**Comment by monkeyman192** [comment]
So turns out this issue is because of the changes I made to `NMSTemplate` which allowed everything to have a relative offset. This was fine for most files, however it appears that the animation files do not have a relative offset... I have fixed the deserialisation code but reserialisation probably will need some code changes...

**Comment by GaticusHax** [comment]
This is fixed [close]
