### ISSUE TITLE
Some sort of --CopyHeader Option?

### ISSUE THREAD

**Issue by GaticusHax** [monkeyman192/MBINCompiler#160]
Even though MBINCompiler has an option to use the --V0 header format when compiling MBIN files which conforms to the same MBIN header format that is used in vanilla MBIN files; the data itself, such as timestamp are different and means that when comparing binary files, all MBINs are flagged as different than the vanilla files simply because of these known and expected differences.

To be able to reproduce the vanilla mbin files so they can be faithfully compared, the recompiled mbin should be able to import the header data from the vanilla mbin header so that they match. 

- [ ] It should be possible to use this copy operation on an existing mbin without recompiling.
- [ ] It should also be possible to use this operation inline with the convert process.

**Comment by monkeyman192** [comment]
I think this change isn't something we need to do since I don't think we actually care any more about making this particular field the same. It's better for us to use that chunk of the header as the mbincompiler version since that is much more useful and used by a number of tools now.
