### ISSUE TITLE
MBIN Conversion Testing

### ISSUE THREAD

**Issue by GaticusHax** [monkeyman192/MBINCompiler#161]
When each new NMS update rolls out and libMBIN needs to do massive updates to the structs, it is necessary to test the changes by recompiling vanilla MBIN files and comparing to the originals. Sometimes the changes are widespread across many, possibly unknown types of MBINs, so it is prudent to test a variety of MBINs for all possible structs.  

The general technique is to process all the MBINS in the vanilla GAMEDATA in it's entirety, but this is inefficient and very slow. There are only about 2000 NMS structs in libMBIN but there are around 40,000 MBIN files in the GAMEDATA and typically takes about 5 or 10 minutes to execute on a moderate machine using an SSD.   

This testing procedure should be addressed so that it is much more efficient and to provide some options to facilitate and simplify the process so that it is more convenient.

**Comment by monkeyman192** [comment]
@HolterPhylo has done some work relating to automation of extracting small and unique mbin files to maximise the coverage of structs to provide a compact database of files we can test on. It might not get 100% coverage, but I think it will be very close...

**Comment by monkeyman192** [comment]
I have some ideas for this and have started to implement to testing of recompiling files (eg. see #199 )
This will be slowly expanded on.

**Comment by monkeyman192** [comment]
I'm going to close this as I would consider this complete at this point. The testing process is quite streamlined, and with the recent scripts added to the [MBINCompiler test data repo](https://github.com/monkeyman192/MBINCompiler-test-data), I think we have a pretty comprehensive test suite for the CI.
