### ISSUE TITLE
Integrate Automated Unit Testing into the Travis-CI Pipeline.

### ISSUE THREAD

**Issue by GaticusHax** [monkeyman192/MBINCompiler#163]
Unit testing should be performed after the automated build process to ensure that the project not only builds but is also sane. Particularly before the deployment process, unit testing should be used to help ensure that bad builds  are not released.

_blocked by #161 and #162_

**Comment by monkeyman192** [comment]
I should have closed this a while ago as we now have unit tests running on the CI
