### ISSUE TITLE
String Id in Language EXML's is truncated

### ISSUE THREAD

**Issue by lukegravitt** [monkeyman192/MBINCompiler#164]
**Describe the bug**
In language EXML files (for example, NMS_UPDATE3_ENGLISH.EXML), entries are extracted with an `Id` property that seems to be getting truncated at 31 characters.

Examples of this are entries for some of the trade commodities in above file:

`<Property name="Id" value="UI_TRADE_ITEM_COMMODITY_1_NAME_" />`
`<Property name="Id" value="UI_TRADE_ITEM_COMMODITY_2_NAME_" />`

These correspond to 'Decrypted User Data' and 'Star Silk'. The string `Id`'s are referenced in the corresponding data table:

In `NMS_REALITY_GCPRODUCTTABLE.EXML`:

`<Property name="NameLower" value="UI_TRADE_ITEM_COMMODITY_1_NAME_L" />`
`<Property name="NameLower" value="UI_TRADE_ITEM_COMMODITY_2_NAME_L" />`

This `L` is truncated in the translation file. I have not attempted to repack or mod these files, only read the data and have accounted for the error in my own project, but wanted to let you know about the weirdness.

MBINCompiler v2,13.0.3

**Comment by monkeyman192** [comment]
As odd as it sounds, this isn't a bug with MBINCompiler...
The ID fields are 32 bytes long with the last byte being a null character. That's just how HG has it (see attached image of the binary data, you can see the ID ends after the underscore (this is the unedited vanilla file))
![image](https://user-images.githubusercontent.com/8000597/67132940-58a79e00-f256-11e9-9c13-ca0a8b5745cb.png)
