### ISSUE TITLE
I can't compile BIRD.GEOMETRY.MBIN, but file and MBINCompiler are from current version

### ISSUE THREAD

**Issue by Timo3681** [monkeyman192/MBINCompiler#165]
![image](https://user-images.githubusercontent.com/21967584/67165750-2c406e80-f389-11e9-9c16-8674e77d8afc.png)

**Comment by GaticusHax** [comment]
You need to show the MBINCompiler.log

**Comment by monkeyman192** [comment]
I'm going to close this as not relevant/doesn't need to be fixed. We don't really need to properly support geometry files in this way...
