### ISSUE TITLE
Errors decompiling two mission files

### ISSUE THREAD

**Issue by clownmug** [monkeyman192/MBINCompiler#167]
Trying to decompile latest version of COREMISSIONTABLE.MBIN gives [ArgumentNullException] and MISSIONCOMMUNITYDATA.MBIN gives [EndOfStreamException]. All other mission files seem to be fine.

MBINCompiler Version: 2.13.0.3
NMS Game Version: 2.13
MBIN File: [COREMISSIONTABLE.MBIN, MISSIONCOMMUNITYDATA.MBIN]
MBIN File Version: 2.13

[MISSIONCOMMUNITYDATA.log](https://github.com/monkeyman192/MBINCompiler/files/3764720/MISSIONCOMMUNITYDATA.log)
[COREMISSIONTABLE.log](https://github.com/monkeyman192/MBINCompiler/files/3764721/COREMISSIONTABLE.log)

**Comment by clampi** [comment]
Hello, same issue happens with BASECOMPUTERMISSIONTABLE.MBIN.
MBINCompiler 2.13.0.3
NMS BuildID 4333995

**Comment by monkeyman192** [comment]
This is a) stale, and b) fixed (well it was, it is probably now broken again but will be fixed in due process).
Closing as no longer needed :)
