### ISSUE TITLE
[UPDATE] Updated structs from 2.13 to 2.15

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#168]
# New structs:

- [x] cGcAtlasActiveFeaturedBaseHeader	0A383984B7DBD6058
- [x] cGcAtlasFeaturedBaseStateChange	6419C3C949E87B35
- [x] cGcAtlasRecvActiveFeaturedBasesQuery	0CB44EBD725E824C4
- [x] cGcAtlasRecvFeaturedBasesQueryList	4ABD0759676FBD77
- [x] cGcAtlasSendChangeFeaturedBasesEnv	4B0EA5D3993F3367
- [x] cGcAtlasSendMarkFeaturedBase	50FAD3F04610D74C
- [x] cGcAtlasSendMarkFeaturedBaseWithImage	9586CD35800C5D18
- [x] cGcAtlasSendQueryActiveFeaturedBases	7F8B36DDFFD87DFB
- [x] cGcAtlasSendQueryFeaturedBases	9282B3044051AD64
- [x] cGcAtlasSendRemoveFeaturedBases	0D19915ADEC16B704
- [x] cGcMissionConditionIsPlayerWeak	6E18159DA19C16C
- [x] cGcRewardActivateFiends	0AA0C5623247548E8

# Structs with internal changes:

- [x] cGcAlienPuzzleOption	7D94083E5E34AFDB
- [x] cGcAlienPuzzleTable	66E4342B5E46E1D2
- [x] cGcAtlasRecvBaseList	0B116FE1E65D75D9
- [x] cGcAtlasRecvBaseQueryList	16A2D963F903CD30
- [x] cGcAudioAreaTriggerComponentData	0D4644714A388C0F3
- [x] cGcAudioWwiseEvents	0F5E1354C940DD9CE
- [x] cGcBuildingPlacementErrorTypes	0E7A224F2DA386498
- [x] cGcConsumableItem	366BD5CA685D8C26
- [x] cGcConsumableItemTable	1DF0CF0995937F13
- [x] cGcExplosionData	0F5C0C64A5BBD07EC
- [x] cGcExplosionDataTable	1B4A32AF7EB4A214
- [x] cGcGalaxyAudioSetupData	0B6573C3009893D75
- [x] cGcGenericMissionSequence	18E217B654D6C44F
- [x] cGcGrabPlayerComponentData	0C084B2513F196B92
- [x] cGcHUDStartup	63D45E8B18583AD
- [x] cGcHUDStartupTable	8AB6814356196AEF
- [x] cGcHotActionsSaveData	68C4679239DBF73C
- [x] cGcInteractionBufferType	0C44D601AF6AE9B96
- [x] cGcInventorySlotActionData	0BFB12952A773A483
- [x] cGcLaserBeamData	0A85D4778461F81E2
- [x] cGcMissionBoardOptions	4C591D47CCA6F35A
- [x] cGcMissionConditionInCombat	75A2443DD36E45AA
- [x] cGcMissionConditionInMultiplayer	862D7990AD850507
- [x] cGcMissionSchedulesTable	0A66AAC7948F38D4B
- [x] cGcMissionSequenceAudioEvent	149D026B9CC47E63
- [x] cGcMissionSequenceDetailMessage	6DD02FDFDBBFCF95
- [x] cGcMissionSequenceShowMessage	0A2F40488F1CA7198
- [x] cGcMissionTable	980B5E56CCE33345
- [x] cGcProjectileData	9269A537CC3F983F
- [x] cGcProjectileDataTable	0B2DC960C4794EEF
- [x] cGcQuickMenuActionSaveData	71C42B9CDCDF3C33
- [x] cGcQuickMenuActions	0CDC9DB9C8E1C0C47
- [x] cGcRewardSecondaryInteractionOptions	0DC52AC273B5FF98B
- [x] cGcScanEventSolarSystemLookup	0B43DA88C9A6169DF
- [x] cGcScanEventTable	0DB6113A017CDD330
- [x] cTkMaterialMetaData	5D3A372D8396458E

# Structs with a file size change:

- [x] cGcAlienPuzzleEntry	old: 0x108	new: 0x110	GUID: 9B58505B59BAB86B
- [x] cGcAtlasSendSubmitBase	old: 0x2F0	new: 0x300	GUID: 1E3A3511CBD73A40
- [x] cGcAtlasSendSubmitBaseWithImage	old: 0x310	new: 0x320	GUID: 0AED7A5A095C6D0FE
- [x] cGcDefaultSaveData	old: 0x262A0	new: 0x262B0	GUID: 1D73AD524C921A63
- [x] cGcMissionSchedulingData	old: 0x90	new: 0x98	GUID: 7EEFA78A53AECF66
- [x] cGcPersistentBase	old: 0x2A0	new: 0x2B0	GUID: 724F968605EF0D45
- [x] cGcPlayerStateData	old: 0x26220	new: 0x26230	GUID: 191FF63EB0D67233
- [x] cGcRewardAdvancePortalState	old: 0x1	new: 0x20	GUID: 0E7D8F6DF60098845
- [x] cGcScanEventData	old: 0x2F8	new: 0x300	GUID: 0A1E07BDDA45DF2ED

# Globals:
- [x] GCBUILDINGGLOBALS.GLOBAL.MBIN
- [x] GCDEBUGOPTIONS.GLOBAL.MBIN
- [x] GCGALAXYGLOBALS.GLOBAL.MBIN
- [x] GCGRAPHICSGLOBALS.GLOBAL.MBIN
- [x] GCMULTIPLAYERGLOBALS.GLOBAL.MBIN
- [x] GCUIGLOBALS.GLOBAL.MBIN

**Comment by HolterPhylo** [comment]
GCGALAXYGLOBALS.GLOBAL.MBIN
GCGRAPHICSGLOBALS.GLOBAL.MBIN
GCUIGLOBALS.GLOBAL.MBIN

should be closed here,  they are superseded by #197

**Comment by HolterPhylo** [comment]
cGcAtlasRecvBaseList was done in PR #193
