### ISSUE TITLE
MBIN Format V3

### ISSUE THREAD

**Issue by GaticusHax** [monkeyman192/MBINCompiler#169]
Currently, TkAnimMetadata and TkGeometry files are handled as hard-coded/static mbin format V0 files regardless if V1 or V2 is used. This presents various issues. It means that it is not possible for these types of files to utilize the features that are provided in the newer formats. Most importantly, mbincompiler cannot validate the GUIDs because they are hard-coded and do not correspond to the appropriate GUID for the current nms version. This results in false warnings in the MBINCompiler.log. The errors could be specifically ignored from MBINCompiler but that would just be a band-aid and would not address the other issues.

Fixing this breaks compatibility with existing files using the V2 format so the format version must be incremented to V3.

See issue #155

**Comment by monkeyman192** [comment]
I think this can be closed since we are well past this...
