### ISSUE TITLE
Custom ID (GcProductData) 17 chars, truncated, no warning.

### ISSUE THREAD

**Issue by Muzashimaru** [monkeyman192/MBINCompiler#173]
**Describe the bug**
Custom ID with 17 characters. Gets truncated to 16 and there is no warning of this.

**Expected behavior**
Warning message: "IDs longer than 17 characters found. They will be truncated."

**Steps To Reproduce**
1. Go to a `<Property value="GcProductData.xml">`
2. Enter an ID with 17 characters
3. Compile
4. Decompile to see the last character removed.

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 2.15 pre 1
 - NMS Game Version 2.15
 - MBIN File: NMS_REALITY_GCPRODUCTTABLE.MBIN
 - MBIN File Version: 2.15

https://user-images.githubusercontent.com/35605288/68170997-3b6f1100-ff72-11e9-8747-864474c88031.jpg

**Comment by monkeyman192** [comment]
@Muzashimaru Sorry this took so long to get to!
I have made a PR, if you have time check it out and let me know if you think this is a sufficient solution:
https://github.com/monkeyman192/MBINCompiler/pull/224
