### ISSUE TITLE
GCDEBUGOPTIONS.GLOBAL.MBIN not recognized

### ISSUE THREAD

**Issue by DarkSideRC2** [monkeyman192/MBINCompiler#174]
trying to convert GCDEBUGOPTIONS.GLOBAL.MBIN of last NMS 2.15 to EXML generate a warning

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: A:\SteamLibrary\steamapps\common\No Man's Sky\Unpacked PCBANKS_20191106\GCDEBUGOPTIONS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	80869B6E9A3A776C	template:	cGcDebugOptions
  
but create an EXML....

the MBIN reverse created after changing the EXML don't seems to work (not taken in acount by nms)

To reproduce :
1) GCDEBUGOPTIONS.GLOBAL.MBIN to GCDEBUGOPTIONS.GLOBAL.EXML
2) change :   Property name="DisableSaveSlotSorting" value="True"   (original = False)
3) GCDEBUGOPTIONS.GLOBAL.EXML to  GCDEBUGOPTIONS.GLOBAL.MBIN
4) => Test.pak with PSarcTool.exe
5) launch NMS... nothing change

But if i use the "Unsorted Saves 1.3.pak" from "https://www.nexusmods.com/nomanssky/mods/1062", it works.....

Thks

-

**Comment by methatronc** [comment]
I have almost the same issue with GCUIGLOBALS.GLOBAL.MBIN , though no EXML is created, any way to fix it ? Thanks !
![Annotation 2019-11-29 105700](https://user-images.githubusercontent.com/58328740/69861637-0d42cf80-1299-11ea-86a0-d76a24cf2ba8.png)

**Comment by monkeyman192** [comment]
The file was probably updated with the 2.2 update. This will be fixed when I get around to it sorry

**Comment by monkeyman192** [comment]
I'll close this and progress can be tracked in #179 instead :)
