### ISSUE TITLE
Bug STATION.ENTITY.MBIN & STATION_ABANDONED.ENTITY.MBIN

### ISSUE THREAD

**Issue by jasondude7116** [monkeyman192/MBINCompiler#178]
Both files seem to be missing a section that got added a few versions ago. I can decompile, do NO edits, recompile, and file is different. Result: a missing room in the space station. This started with beyond.

**Comment by monkeyman192** [comment]
Fixed by e7a4ef0cf4938ba564961414bb2a0ea30d2c7c42
