### ISSUE TITLE
GCPLAYERGLOBALS.GLOBAL.MBIN still undecompileable in 2.22.0-pre2

### ISSUE THREAD

**Issue by Ratan-Kabidge** [monkeyman192/MBINCompiler#182]
**Additional Information**
 Likely you know this, I didn't see it mentioned specifically, but it is in the list as "unchecked" status.
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3912762/MBINCompiler.log)

Forgive me if this is already known, as I'm still learning what you have posted where, lot to digest. 

Included log file is the vanilla file.

**Comment by monkeyman192** [comment]
The global is listed in #179 
I'll probably get to it tonight however so it should be fixed soon :)
