### ISSUE TITLE
GAMEPLAYGLOBALS Line 188 Unknown 0x394

### ISSUE THREAD

**Issue by Gumsk** [monkeyman192/MBINCompiler#187]
I figured out what this line is:

<Property name="Unknown0x394" value="400" />

It's for the scan range on the hotspot scanner in the analysis visor, in u. I'm calling it HotspotScanRange in my lua.

**Comment by HolterPhylo** [comment]
From Discord: It's Unknown0x394 on line 188 of Gameplay.

**Comment by monkeyman192** [comment]
If you could make a PR to add this it would be great! :)
