### ISSUE TITLE
Unable to decompile vanilla PLANTINTERACTION.ENTITY.MBIN files.

### ISSUE THREAD

**Issue by Ratan-Kabidge** [monkeyman192/MBINCompiler#192]
**Describe the bug**
Unable to decompile any of these vanilla files to exml. I did not see them on the update lsit at all, and I know these are not used too often so thought perhaps this was an oversight, or a bug, but I can say my original 2.14 MOD crashes the game client so I suspect something was up[dated.
Files known to have issues (same file names in multiple locations:
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMALBUMEN\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMBARREN\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMDEADCREATURE\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMGRAVATINO\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMLUSH\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMNIP\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMPOOP\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMRADIOACTIVE\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMSCORCHED\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMSNOW\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMTOXIC\ENTITIES\PLANTINTERACTION.ENTITY.MBIN
\MODELS\PLANETS\BIOMES\COMMON\INTERACTIVEFLORA\FARMVENOMSAC\ENTITIES\PLANTINTERACTION.ENTITY.MBIN

**Expected behavior**
Simply put, attempted to decompile the 2.22 (or isi it 2.23 now?) files to update my farming time reducer mod and they all respond with the attached MBINCompiler Log.

**Steps To Reproduce**

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: [eg 1.0.0.0]
 - NMS Game Version or Steam Build Number: [eg 1.0.0.0, or 4154325] (To find the build number, 
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3943797/MBINCompiler.log)
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/3943802/MBINCompiler.log)

right click on the game in steam, select `Properties`, then click on the `LOCAL FILES` tab and the buildID is at the bottom).
 - MBIN File: [eg GCPLAYERGLOBALS.GLOBAL.MBIN]
 - MBIN File Version: [eg 1.0.0.0]

**Additional Information**
This is with MBIN Compiler v2.22.0-pre4.

_Attachments:_
_Always include the entire log file._
_Do not attach MBIN files unless requested._

**Comment by HolterPhylo** [comment]
No issue reported in log files by MBINCompiler doing MBIN->EXML->MBIN.
And Hex comparing MBINs before and after shows no differences.
Except the usual header differences:
- At 0x04: "C4090000 00000000 00000000" vs "C4090200 02160000 02160004"

So, I cannot replicate this problem.

I would suggest you check your "Vanilla" file(s) against current MBINs...

And if you still get those errors, please post the MBIN file you are using and I'll have a look at it. Thanks

**Comment by Ratan-Kabidge** [comment]
Roger, it is working for me now as well, god only knows what I screwed up (wrong compiler, wrong entity version... is what I get for modding in the middle of the night i guess). /shrug

Consider issue closed, working on updating my final mod until HG changes something else.
