### ISSUE TITLE
[TableReward]Ingame error 

### ISSUE THREAD

**Issue by Teneombre** [monkeyman192/MBINCompiler#20]
Even without modify anything, decompile/Recompile TableReward make game crash when the event giving a location is launched. It is not happen if it comes from a mission or a signal scanner (until last NMS update, didn't try since). I can't test yet with exocraft but ask to a npc for a location and observatory success minigame currently crash the game each time.

**Comment by monkeyman192** [comment]
This issue has been fixed in the most recent version on discord, and the current code here also fixes the issue :)
