### ISSUE TITLE
CREATUREDATATABLE.MBIN error

### ISSUE THREAD

**Issue by melad0rimagpie** [monkeyman192/MBINCompiler#209]
I can't get an .EXML file from the CREATUREDATATABLE.MBIN
I was using NMS Mod Station and it wouldn't generate the .EXML (nothing happened at all), and then I tried manually with MBINCompiler but it just gives an error.

[VERSION]: MBINCompiler v2.24.0.1
NMS 2.24
CREATUREDATATABLE.MBIN

LOG:
[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcCreatureDataTable from MBIN.
[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x1598

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by monkeyman192** [comment]
Whoops, meant to have this happen automatically but this was closed by #210 and the fix is in the latest release :)
