### ISSUE TITLE
[Entity] Compilation from EXML to MBIN erases GcActionTrigger data

### ISSUE THREAD

**Issue by WinderTP** [monkeyman192/MBINCompiler#21]
Compiling EXML entities to MBIN makes the action trigger ineffective, tested with a door opening entity, resulting in door doing nothing.

Decompiling said MBIN to EXML reveals missing GcActionTrigger.

Decompiling vanilla MBIN to EXML reveals GcActionTrigger still present, but upon recompiling said EXML to MBIN and decompiling again, the GcActionTrigger disappears.

My hypothesis: MBINcompiler does not compile GcActionTrigger data into to MBIN properly.

**Comment by WinderTP** [comment]
Note: Upon decompiling a vanilla entity, "EmptyNode"s are found spread across the EXML, example attached.
[MAINDOOR.ENTITY.txt](https://github.com/monkeyman192/MBINCompiler/files/1236911/MAINDOOR.ENTITY.txt)

**Comment by monkeyman192** [comment]
Still need to look into this a bit. Hopefully with the custom alignment stuff I can fix this, but need to have another look. Will hopefully fix soon because I think it maybe applies to most entity files :/
