### ISSUE TITLE
MBINCompiler v2.24.0.1 does not decompile CREATUREDATATABBLE.MBIN

### ISSUE THREAD

**Issue by Toccatta** [monkeyman192/MBINCompiler#211]
Confirmed NMS is most recent version (patched) at v2.24; Error message reads:

[VERSION]: MBINCompiler v2.24.0.1
[ARGS]: "F:\Mass PSARC Tool - v2.24\METADATA\SIMULATION\ECOSYSTEM\CREATUREDATATABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcCreatureDataTable from MBIN.
[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x1598

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by Toccatta** [comment]
[name and path of the file relative to the GAMEDATA folder]

f:\Mass PSARC Tool - v2.24\ is my archive of all the decompressed pak files from D:\no man's sky\GAMEDATA\PCBANKS

**Comment by monkeyman192** [comment]
Most recent version is 2.24.0.2: https://github.com/monkeyman192/MBINCompiler/releases/tag/v2.24.0-pre2
I'll close this but comment if it still doesn't work on the newer version. It *should* though since this file is included in the automated tests which pass...
