### ISSUE TITLE
game name or extension too long

### ISSUE THREAD

**Issue by methatronc** [monkeyman192/MBINCompiler#214]
Hello,
I see the error mentioned in the object of this message : "game name or extension too long" each time I try to convert more than around 400/500 items, though the issue is not with the files since they are convertible as long as I don't ask to convert more than 400 as I said.
This happens with the latest version of both MBINCompiler and NMS, with w10 1909.
Thanks for your help !

**Comment by monkeyman192** [comment]
How are you converting all the files? I have a test folder which contains 1276 .mbin files and it works fine.
In this case I am passing the folder name as an argument to MBINCompiler (ie. `MBINCompiler ./entities`)
Result: `1276 files converted.`

**Comment by methatronc** [comment]
You're completely right, I'm sorry, I always used to just drag/drop on the .exe but goig with a .bat is indeed far more powerful !
Thanks for the help :)

**Comment by monkeyman192** [comment]
Yeah, if you throw a massive amount of file names at it in one go it will probably not be happy. As you said, it is better to use a .bat script for this (or pass a folder like I did)
