### ISSUE TITLE
[UPDATE] 2.26 -> 2.30 (4689150)

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#215]
## New structs:

- [x] cGcCostHasFireteamMember	0E0E796329D5B09D2
- [x] cGcCostItemFromList	9A0C270A968717A4
- [x] cGcCostItemListIndexed	88CD3922DC3770EF
- [x] cGcCostProcProduct	3EC0641E6E3D791E
- [x] cGcCustomisationBobbleHead	359044F0ECE101F8
- [x] cGcCustomisationShipBobbleHeads	90073A922E595FC
- [x] cGcCustomisationShipTrails	0F0149679F3FBEF56
- [x] cGcCustomisationThrusterEffects	323651CECEC47053
- [x] cGcMissionConditionEventRequiresRGB	7C8690206AE1767F
- [x] cGcMissionConditionPulseEncounterOverriden	0F092F88AC97C0E5D
- [x] cGcMissionConditionUsingThirdPersonCamera	5993895CC7D60EEA
- [x] cGcPulseEncounterInfo	0B35D05C4D201EC29
- [x] cGcPulseEncounterSpawnAlienFreighter	3C55850F56D543F3
- [x] cGcPulseEncounterSpawnConditions	0F8578ADA4A226CB5
- [x] cGcPulseEncounterSpawnObject	1CAC5B1C7E541096
- [x] cGcPulseEncounterSpawnPirates	0EC04600EBA97FE19
- [x] cGcPulseEncounterSpawnTrader	0AE168EB8E846799D
- [x] cGcRewardCommunicatorMessage	0A4CCC2F6A734A389
- [x] cGcRewardExchangeProduct	0AD794EB2CCE2FD5F
- [x] cGcRewardOSDMessage	57335F2CCB86257A
- [x] cGcRewardOverridePulseEncounterChance	7DF029F2D7549646
- [x] cGcRewardRepairWholeInventory	45134A0129932783
- [x] cGcRewardSetNexusExitWarpTargetToFireteamMemberUA	625032005EB3E14F
- [x] cGcScanEventGPSHint	4B109224F6A17ADB

## Structs with internal changes:

- [x] cGcAISpaceshipComponentData	70DD92F44548851C
- [x] cGcAISpaceshipManagerData	3B5F72E90BD1D033
- [x] cGcAISpaceshipModelData	16A3216F6E8803A4
- [x] cGcAISpaceshipModelDataArray	0EDA286B4444D971A
- [x] cGcAISpaceshipPreloadCacheData	4C2C0909B85A05A0
- [x] cGcAISpaceshipPreloadList	43702E4CEBA1DF49
- [x] cGcAlienPuzzleEntry	10D718CBCEB2849A
- [x] cGcAlienPuzzleOption	9B3B99197A4F4CDD
- [x] cGcAlienPuzzleTable	0C9912AAF7CEA1AD8
- [x] cGcAudioAreaTriggerComponentData	6DC4E22787116212
- [x] cGcAudioWwiseEvents	0D07ADD4F46EBBCC2
- [x] cGcAudioWwiseRTPCs	0BF6D4FBDF2DE24DE
- [x] cGcBiomeData	0D1AC608AD561BB6
- [x] cGcBuildingSpawnData	3BA25CB7210100C8
- [x] cGcCharacterCustomisationColourData	7C7F3533B4EC15F3
- [x] cGcCharacterCustomisationData	3907FBAAF3404E7
- [x] cGcCharacterCustomisationSaveData	2071C8ECAB56ADE1
- [x] cGcConsumableItem	0D0420536D2DCEED3
- [x] cGcConsumableItemTable	79B64B3923CFF392
- [x] cGcCostPirateTribute	91DB81C7C04C4284
- [x] cGcCostTable	506BCAC7DB4FD1CB
- [x] cGcCostTableEntry	280D4347D75088D9
- [x] cGcCreatureSpawnComponentData	0CCD7D14A20B9A103
- [x] cGcCreatureSpawnData	950A53BDC3FAFE4F
- [x] cGcCustomisationColourGroup	1140A5527024434B
- [x] cGcCustomisationDescriptorGroupOption	0B58FA1EE8A51F1E1
- [x] cGcCustomisationDescriptorGroupOptions	7369AA0D0B9559FD
- [x] cGcCustomisationGroup	8A33356FBCF71149
- [x] cGcCustomisationGroups	0F0257C49A45B03D0
- [x] cGcCustomisationPreset	823D8545F72BF298
- [x] cGcCustomisationPresets	0BC2D2BDDEE7D3191
- [x] cGcCustomisationRace	49AAC830D1E734A1
- [x] cGcCustomisationTextureOption	28101937F4FE62D1
- [x] cGcCustomisationTextureOptions	873A00FC309B7065
- [x] cGcCustomisationUI	66DC729409728F3E
- [x] cGcCustomisationUIData	38AC172BEC4FC990
- [x] cGcDefaulMissionProduct	2E9422BBD4E895A
- [x] cGcDefaulMissionSubstance	3CDDF6994BEB5829
- [x] cGcDefaultMissionItemsTable	217C512892CCF77B
- [x] cGcDoShipFlybyClose	9A90AA1BA5899070
- [x] cGcEnvironmentSpawnData	23FAAE0C3C70B26
- [x] cGcExplosionData	0BCCF05FEE9407392
- [x] cGcExplosionDataTable	5E2D19B626BC1471
- [x] cGcExternalObjectList	0C6F50AA19CA19F24
- [x] cGcFogProperties	82BFC9EF9A2BCB7C
- [x] cGcGalaxyAudioSetupData	4709E8A469B2E865
~cGcGenericMissionSequence	73BC433EDE18F156~
- [x] cGcGrabPlayerComponentData	4EB7363A1F521EE4
- [x] cGcHUDStartup	64730032ABF9C77F
- [x] cGcHUDStartupTable	90DD0CB755AC523
- [x] cGcHeavyAirSetting	0C94CB973E523C055
- [x] cGcHeavyAirSettingValues	0B093C1958758D9A4
- [x] cGcInventoryBaseStat	1D401D82CA24DF9B
- [x] cGcInventoryBaseStatBonus	17E60DA66FBD1218
- [x] cGcInventoryLayoutSizeType	0C84CE79CC0FE81EE
- [x] cGcInventorySlotActionData	0F442220BF52892C2
- [x] cGcInventoryTableEntry	569D04D5958E8953
- [x] cGcLaserBeamData	558031D33E143E28
- [x] cGcMissionConditionHasFuel	0DBC3CA9A52643B81
- [x] cGcMissionConditionHasSubstance	0CAC971ACAEED9AF4
- [x] cGcMissionConditionHasTechnology	55C4A9DE2A42E68F
- [x] cGcMissionConditionIsTechnologyRepaired	63644C1513C9B8D3
- [x] cGcMissionConditionNearObject	6CEB89D0BE94C755
- [x] cGcMissionConditionNearScanEvent	8AC2DF4FD4140247
~cGcMissionConditionProductKnown	651B4AE5C2B237ED~
- [x] cGcMissionConditionTechnologyKnown	87A89102F10A611B
- [x] cGcMissionConditionWeaponMode	1024E2C04ACBDD35
- [x] cGcMissionSequenceAudioEvent	0BE106923AE47D2ED
~cGcMissionSequenceCollectProduct	7CFFA5186A0E4B9C~
- [x] cGcMissionSequenceCollectSubstance	4D950F2D01B2FFF3
- [x] cGcMissionSequenceDetailMessage	37E222056CD6DB84
- [x] cGcMissionSequenceGatherForRefuel	35DA13F800DE0F73
- [x] cGcMissionSequenceGatherForRepair	0C44AFF4BBDD202F9
- [x] cGcMissionSequenceGroup	0ACAE973C5302E516
- [x] cGcMissionSequenceShowMessage	1536A488BF45FE1
- [x] cGcMissionSequenceWaitForRefuel	7AFBA03D4ED094D4
- [x] cGcMissionSequenceWaitForRepair	0FBE73A007519C7F7
- [x] cGcMissionTable	0A6205A2B633D246B
- [x] cGcNGuiGraphicData	0B315DD90C4E2B5ED
- [x] cGcNGuiLayerData	9026DC960073CC8E
- [x] cGcNGuiPreset	1AD7D8436A85F2B5
- [x] cGcNGuiPresetGraphic	37E9D6953FAF4A31
- [x] cGcNGuiPresetText	0B32D5DA74C1EFD0C
- [x] cGcNGuiTextData	3C538C7C225E4D50
- [x] cGcNPCPlacementInfo	0AB481CB332C7ACB0
- [x] cGcNPCPropInfo	0EA9EE3B6B0BAB242
- [x] cGcNPCPropTable	0BA15624EC65A5DC8
- [x] cGcNPCSpawnTable	0D03210F547BF1A40
- [x] cGcNPCWorkerData	9282A787424288F3
- [x] cGcObjectSpawnData	0DDE6AC98AE03E02D
- [x] cGcObjectSpawnDataArray	5454390E083624B4
- [x] cGcPlanetBuildingData	0D28613255D608C2F
- [x] cGcPlanetTerrainColour	0CE6A62A6BA1046B1
- [x] cGcPlanetWeatherData	0DD7AA425D9E33044
- [x] cGcPlayerOwnershipData	0F96A60B3E3E74A10
- [x] cGcPlayerWeapons	0F7269993F8A4F96E
- [x] cGcProceduralProductCategory	0FD9990071C5EADD2
- [x] cGcProceduralTechnologyData	0A296C81EDA433A2B
- [x] cGcProceduralTechnologyStatLevel	0B9086DC4FDA4559F
- [x] cGcProceduralTechnologyTable	520CDCF02475ABE4
- [x] cGcProjectileData	0FEF025D899A4F48A
- [x] cGcProjectileDataTable	0E1063CFE4239CBC9
- [x] cGcResourceElement	3558F692031D58C
- [x] cGcRewardDamageTech	293DBC051B8AE1C4
- [x] cGcRewardPirateAttack	0D9C2D5EE2FB6393A
- [x] cGcRewardRepairTech	7CCDE164FB24F726
- [x] cGcRewardSecondaryInteractionOptions	0C73E7DC0140F71F6
- [x] cGcRewardSpecificShip	0C48C630109CB3A82
- [x] cGcRewardTechRecipe	6881566E93739B47
- [x] cGcScanEventTable	16680FA46653A2EB
- [x] cGcScreenFilters	80FB7733205005F7
- [x] cGcSelectableObjectSpawnData	286B0C3C37E87BA2
- [x] cGcSelectableObjectSpawnList	7104FBF2DB682458
- [x] cGcShipOwnershipComponentData	0CEF2498474683652
- [x] cGcShipWeaponData	0F190D8BD8DB604E1
- [x] cGcSpaceshipClasses	283835244553D998
- [x] cGcSpaceshipComponentData	0B8DDE7805167BA7D
- [x] cGcSpawnComponentOption	0EF6C780BE2FE91C4
- [x] cGcStats	92292BD11FC301AC
- [x] cGcStatsBonus	60EAF1A4E0E740B4
- [x] cGcStatsEntry	0EF4287DA929B5762
- [x] cGcStatsGroup	5E48B11C55A79E22
- [x] cGcStatsTypes	0BCC31AD0357D4610
- [x] cGcStormProperties	0D66F61437AFED6C7
- [x] cGcTechnology	8FE513CD484DB1BA
- [x] cGcTechnologyCategory	0EA1F67D024C2D20C
- [x] cGcTechnologyTable	0D027831E3871640B
- [x] cGcTechnologyTypes	0EE8E32B86B95196E
- [x] cGcTileTypeOptions	8D914CCF3ABE423E
- [x] cGcTileTypeSet	0D2A302F10249BA29
- [x] cGcTileTypeSets	0CD0F12F746CB16B3
- [x] cGcUniqueNPCSpawnData	8E8D1FE2022A3EA3
- [x] cGcWarpAction	844FED1B7CC7A30
- [x] cGcWeatherProperties	1A7B0A07112D4A39
- [x] cTkEngineSettingTypes	9FB0D2A8D613F2C
- [x] cTkGlobals	3BD5B163E6D81E47
- [x] cTkGraphicsSettings	2D17E33EFF5835EF
- [x] cTkNGuiEditorStyleData	85CB6ECFAC1A21A1
- [x] cTkNGuiGraphicStyle	0B795862495EA8C5C
- [x] cTkNGuiGraphicStyleData	45240D7A5E9C693B
- [x] cTkPaletteTexture	565979C690E12DA2
- [x] cTkProceduralTexture	0EDF250D3D9ABB318
- [x] cTkProceduralTextureChosenOption	0EFA68130B1B05C91
- [x] cTkProceduralTextureChosenOptionList	38EFB67C33AE033D
- [x] cTkProceduralTextureChosenOptionSampler	8578DEEF68E7D98C
- [x] cTkProceduralTextureLayer	0BD83E215E5C89AE7
- [x] cTkProceduralTextureList	2C04CD0BD6534FA0
- [x] cgcproducttableEnum	940691424D2C1AD1
- [x] cgcsubstancetableEnum	180F7F2AAAEC5208
- [x] cgctechnologytableEnum	0B006C7C53A92D025

## Structs with a file size change:

- [x] cGcDefaultSaveData	old: 0x29710	new: 0x29770	GUID: 2D76381453AEFF59
- [x] cGcDestructableComponentData	old: 0x198	new: 0x1C0	GUID: 0B5D1776FD909924C
- [x] cGcDisplayText	old: 0x304	new: 0x318	GUID: 67991AA77D99A38E
- [x] cGcExperienceSpawnTable	old: 0xD0	new: 0xE0	GUID: 40B3FC2ADCC3B1F0
- [x] cGcInteractionBuffer	old: 0x10	new: 0x18	GUID: 1F893025804FBD28
- [x] cGcInventoryTable	old: 0x7D0	new: 0x888	GUID: 0CCB56BA9818B0115
- [x] cGcMissionConditionHasProduct	old: 0xC	new: 0x10	GUID: 0DFFE983F14A63402
- [x] cGcMissionSequenceGetToScanEvent	old: 0x230	new: 0x238	GUID: 172A5E650D502F46
- [x] cGcMissionSequenceWaitForScanEvent	old: 0x228	new: 0x230	GUID: 0B1C47B378D57004
- [x] cGcMissionSequenceWaitRealTime	old: 0x108	new: 0x110	GUID: 0F5CF46F34D184154
- [x] cGcModelExplosionRules	old: 0x30	new: 0x38	GUID: 0D746AFF35025FAAD
- [x] cGcPlanetData	old: 0x3BF0	new: 0x3D40	GUID: 1A7953E3F069A05C
- [x] cGcPlayerStateData	old: 0x29690	new: 0x296F0	GUID: 7D5E84F223561BE2
- [x] cGcRealityManagerData	old: 0xC1A0	new: 0xC2C0	GUID: 82FDF69A0F49BD7E
- [x] cGcRewardProceduralProduct	old: 0x4	new: 0x28	GUID: 249A565C45F7A70C
- [x] cGcRewardSpecificProduct	old: 0x20	new: 0x28	GUID: 44FE10AEC1800BBD
- [x] cGcScanEventData	old: 0x300	new: 0x5B8	GUID: 4D233725DC15D1CC
- [x] cGcScanEventSolarSystemLookup	old: 0x68	new: 0x70	GUID: 9809454F47299CA1
- [x] cGcScreenFilterData	old: 0xA8	new: 0xB0	GUID: 129967321DE298AA
- [x] cGcScreenFilterTable	old: 0x17A0	new: 0x1AD0	GUID: 4F7EFF6A2047FBFD
- [x] cGcSolarSystemData	old: 0x1DA0	new: 0x1EF0	GUID: 43633846B94FE440

## Globals:

- [x] GCAISPACESHIPGLOBALS.GLOBAL.MBIN
- [x] GCCAMERAGLOBALS.GLOBAL.MBIN
- [x] GCCREATUREGLOBALS.MBIN
- [x] GCDEBUGOPTIONS.GLOBAL.MBIN
- [x] GCGALAXYGLOBALS.GLOBAL.MBIN
~GCGAMEPLAYGLOBALS.GLOBAL.MBIN~
- [x] GCPLAYERGLOBALS.GLOBAL.MBIN
- [x] GCSKYGLOBALS.GLOBALS.MBIN
- [x] GCSOLARGENERATIONGLOBALS.GLOBAL.MBIN
- [x] GCSPACESHIPGLOBALS.GLOBAL.MBIN
- [x] GCUIGLOBALS.GLOBAL.MBIN

**Comment by HolterPhylo** [comment]
As discussed, I also find these:
# Structs with a file size change:
- [x] cGcAISpaceshipWeightingData                   | old: 0x1C    | new: 0x20    | GUID: B164EA8EF150DFDC
- [x] cGcInventoryLayoutGenerationData              | old: 0x1C0   | new: 0x1F0   | GUID: A8879B14156D70FE
- [x] cGcPaletteList                                | old: 0xD340  | new: 0xDF70  | GUID: D30F287F6E810E96
- [x] cGcPlanetColourData                           | old: 0x16C0  | new: 0x1810  | GUID: A5943DFEC116B5B7
- [x] cGcProceduralProductTable                     | old: 0x5B70  | new: 0x6C10  | GUID: 1D20382C6544FD00
- [x] cGcStatIconTable                              | old: 0x4900  | new: 0x4A00  | GUID: 1E0206B2601F3050
