### ISSUE TITLE
2.30 (4689150) -> 2.31 (4696452)

### ISSUE THREAD

**Issue by HolterPhylo** [monkeyman192/MBINCompiler#216]
# Structs with internal changes | GUID
- [x] cGcDefaulMissionProduct                            | CB7BB20B2DF0C75E
- [x] cGcDefaultMissionItemsTable                        | E2F72CB28329F490
~cGcExperienceSpawnTable                            | 46819DAB1FE9A3A3~
- [x] cGcGenericMissionSequence                          | 13DAA7CA6B6A977D
- [x] cGcMissionConditionHasProduct                      | 43CFAE7ED8D79E61
- [x] cGcMissionConditionProductKnown                    | DB9394D2855F8023
- [x] cGcMissionSequenceCollectProduct                   | 724C7A664D482864
- [x] cGcMissionTable                                    | 5996E161CAAA5908
~cGcPulseEncounterInfo                              | ECA7EC6BBC6FEB59~
~cGcPulseEncounterSpawnConditions                   | 29C158AEA26006DC~
- [x] cgcproducttableEnum                                | 377BA28C83B5E348

**Comment by monkeyman192** [comment]
closed by e61d2b40a95f291fdbb30a91322e4e109ad37353
