### ISSUE TITLE
2.31 (4696452) -> 2.31(4702377)

### ISSUE THREAD

**Issue by HolterPhylo** [monkeyman192/MBINCompiler#217]
# Structs with internal changes | GUID
- [x] cGcExperienceSpawnTable                            | 68FDE9A04645C86D
- [x] cGcPulseEncounterInfo                              | 75E9444B2695486A
- [x] cGcPulseEncounterSpawnConditions                   | 01DF09CAF01E518B

**Comment by monkeyman192** [comment]
closed by e61d2b40a95f291fdbb30a91322e4e109ad37353
