### ISSUE TITLE
GcAISpaceshipGlobals alignment issue?

### ISSUE THREAD

**Issue by jasondude7116** [monkeyman192/MBINCompiler#218]
I know this:
("TraderHailingEnabled" was changed IN-GAME from "False" in v2.27 to "True" in v2.31, which corresponds with patch notes taunting the new feature)
("FillUpOutposts" was set to "False" in v2.27 IN-GAME and remained so in v2.31)
("FreightersAlwaysAttackPlayer" was set to "False" in v2.27 IN-GAME and remained so in v2.31)
("GroundEffectEnabled" was set to "True" in v2.27 IN-GAME and remained so in v2.31)

These are vanilla decompiled files:
NMS v2.27

!--File created using MBINCompiler version (2.26.0)-->
Data template="GcAISpaceshipGlobals">
  Property name="Unknown0x0" value="3500" />
  Property name="TradersAttackPirates" value="True" />
  Property name="TraderHailingEnabled" value="False" />
  Property name="FreightersAlwaysAttackPlayer" value="False" />
  Property name="GroundEffectEnabled" value="True" />
  Property name="AtmosphereEffectEnabled" value="False" />
  Property name="FillUpOutposts" value="False" /> <----- In this version, this line is aligned properly.

NMS v2.31

!--File created using MBINCompiler version (2.31.0)-->
Data template="GcAISpaceshipGlobals">
  Property name="Unknown0x0" value="3500" />
  Property name="TradersAttackPirates" value="True" /> <----- Circumstantional process of elimination made me believe there is a good chance this value is controlling "TraderHailingEnabled", but unable to prove.
  Property name="TraderHailingEnabled" value="False" /> <----- This value is controlling "FreightersAlwaysAttackPlayer"
  Property name="FreightersAlwaysAttackPlayer" value="True" /> <----- This value is controlling "GroundEffectEnabled"
  Property name="GroundEffectEnabled" value="False" />
  Property name="AtmosphereEffectEnabled" value="False" /> <----- This value is controlling "FillUpOutposts"
  Property name="FillUpOutposts" value="False" />

I'm not sure what the other values in the block are controlling, I tried but was unable to prove anything.

**Comment by monkeyman192** [comment]
Update: Looking at the exe, it looks as if there are only 5 bools in this region now.
Evidence would seem to suggest that the first has been removed (`TradersAttackPirates`), so this is probably what I will do to fix this issue.

**Comment by monkeyman192** [comment]
Closed by efda4a72a2b4ffad708276e8f80f2ed49c58927a
