### ISSUE TITLE
Command line switch for customizing log output name and location

### ISSUE THREAD

**Issue by toazd** [monkeyman192/MBINCompiler#221]
Running multiple instances of MBINCompiler.exe simultaneously using a simple batch file (eg. `for /r %%v in (*.mbin, *.mbin.pc) do D:\MBINC\2.31.0-pre2\bin\MBINCompiler.exe -y -f "%%v`") I ran into lock-file issues with the log file.

A "-l" command line switch or unique log file names for each new instance (eg. logfile-date-time) could provide a more graceful solution to this admittedly minor issue.

My solution was to simply make multiple copies of the executable in different directories. I have not yet explored whether or not using the <register> switch results in the executable writing the log file to the calling/working directory when running multiple instances because I use multiple versions of MBINC.

Thank you very much for your work on this project!

**Comment by monkeyman192** [comment]
So I think I can make this automated actually. If there is a single instance of MBINCompiler running it will output to `MBINCompiler.log`. However if there are more instances running, then the log file name will contain the PID of the process running (eg. `MBINCompiler.12345.log`)
I don't think it would be safe to use the number of the instance (ie. 1, 2, 3 as they are created) as if on closes then another one opens it will defintiely overwrite a log. Using the PID should make this happen very infrequently...)

**Comment by monkeyman192** [comment]
@toazd I'm confused by why you closed this... Did you look at #226 and are happy with the resolution? Unfortunately I couldn't add you as a reviewer, but some input would be appreciated :)
If you think the solution is good I'll merge it.

**Comment by toazd** [comment]
> @toazd I'm confused by why you closed this... Did you look at #226 and are happy with the resolution? Unfortunately I couldn't add you as a reviewer, but some input would be appreciated :)
> If you think the solution is good I'll merge it.

Sorry for such a delay in response time the human malware situation has kept me extremely busy.

The solution you came up with fixes the issue I had. I'm quite new to Github and I didn't/don't know what the appropriate response was.
Edit: To be more clear: Yes, #226 is what I reviewed before closing this issue.

**Comment by monkeyman192** [comment]
ok, cool. Just making sure. I'll merge it in then so we can have it in the next release! Thanks for raising the issue and reviewing the PR 👍

**Comment by monkeyman192** [comment]
I'm actually going to re-open this issue. I have noticed a few issues with my solution and a few other users have raised concerns that the solution probably isn't the best, so I'll try make a slightly more thorough solution...
