### ISSUE TITLE
All mods using GCGRAPHICSGLOBALS.GLOBAL are not compatible with Exo Mech update

### ISSUE THREAD

**Issue by horatiohafnaugels** [monkeyman192/MBINCompiler#230]
**Description**
All mods using GCGRAPHICSGLOBALS.GLOBAL are affected by a visual glitch after the Exo Mech update: when loaded the game shows an orange / hyper solarized  / washed out image when walking on foot.

**Steps to reproduce**
1) unpack and decompile GCGRAPHICSGLOBALS.GLOBAL.MBIN
2) recompile GCGRAPHICSGLOBALS.GLOBAL.EXML (no need to change anything) and pack
3) install the mod
4) Load the game.

**Expected behavior**
nothing should change, for GCGRAPHICSGLOBALS.GLOBAL.EXML hasn't been touched.

**Actual behavior**
everything is orange / hyper solarized / washed out.

**Specs**
libMBIN (MBINCompiler) Version: v2.40.0-pre1
NMS Game Version: 2.41 (Eco Mech Update patch)
MBIN File: GCGRAPHICSGLOBALS.GLOBAL.MBIN

**Additional info**
Looks like first elements in in GCGRAPHICSGLOBALS.GLOBAL.EXML have exchanged their values: HBAORadius took the value of HBAOBias (0.1), HBAOIntensity took the value of HBAORadius (2), LightShaftScattering took the value of HBAOIntensity (5) and so on...

**Comment by monkeyman192** [comment]
Please check the update issues (for this update, see #229 ) to see if the struct you are reporting is meant to be fixed. Since this global isn't ticked off it isn't expected to work (eta will be a few days I think...)
I'll close this but I'll keep in mind your additional info when mapping the struct, thanks!

**Comment by monkeyman192** [comment]
Actually, this global only has the changes you noted above, so it's done and will be in the next release :)
