### ISSUE TITLE
[Reporting] Ensure all structs have the correct length

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#233]
by running `./MBINCompiler.exe list`, the results indicate that 592 structs do not have a defined size.
This should be fixed so that every struct has its size in MBINCompiler reported correctly as this information may be required later for automatic generation of documentation etc.

**Comment by HolterPhylo** [comment]
Is it only a matter of adding `Size = 0x50, ` to the `[NMS(Size = 0x50, GUID = 0x3B5F72E90BD1D033, NameHash = 0x785665CB6C017B4C)]` line in the corresponding _**struct.cs**_ file (when the Size entry is missing obviously)?

I can provide a list of all structs size... (except for GLOBALS)

**Comment by monkeyman192** [comment]
yep, that's all that needs to be done.
All globals should already have their lengths added (I did that in one of the most recent commits...)

**Comment by HolterPhylo** [comment]
then maybe help with the git stuff :)

**Comment by HolterPhylo** [comment]
I got 586 changes done adding `Size = 0x??` (where ?? is the current size) to all the .cs files currently missing it.
See Pull request

**Comment by monkeyman192** [comment]
closed by #238
