### ISSUE TITLE
2.43.0-pre1 defaultsavedata and defaultsavedatacreative warning

### ISSUE THREAD

**Issue by instakibbs** [monkeyman192/MBINCompiler#236]
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: <PATH>\DEFAULTSAVEDATACREATIVE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	CEBAEAB5F6742206	template:	cGcDefaultSaveData
  
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: <PATH>\DEFAULTSAVEDATA.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	CEBAEAB5F6742206	template:	cGcDefaultSaveData
  

[INFO]: 2 files converted.

[INFO]: 2 WARNINGS.

**Comment by monkeyman192** [comment]
I cannot reproduce this. The default save data files provided by the test files decompile and recompile perfectly with no errors.
I do have an idea to make that message a little more informative however so I might just leave this open to implement that...
