### ISSUE TITLE
File not recognized. You may need to use an older version of MBINCompiler.

### ISSUE THREAD

**Issue by MOOOOs** [monkeyman192/MBINCompiler#268]
[VERSION]: MBINCompiler v2.61.1.2
[ARGS]: "D:\UNP\GCSPACESHIPGLOBALS.GLOBAL.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: D:\UNP\GCSPACESHIPGLOBALS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	F7AD1AF54F745BBF	template:	cGcSpaceshipGlobals
  [EXPECTED INFO]: GUID: C645D83A9EEF15C4
  

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcSpaceshipGlobals from MBIN.
[EndOfStreamException]: Unable to read beyond the end of the stream.

   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadSingle()
   at libMBIN.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at MBINCompiler.Commands.Convert.ConvertMBIN(String inputPath, FileStream fIn, MemoryStream msOut, String fileOut)

So im trying to unpack file from MBIN to EXML and it gives me this error i have latest MBIN Compiler and currently trying to open latest NMS Origin GCSPACESHIPGLOBALS.GLOBAL.MBIN
Why i get this error please help as quick as possible if you can

**Comment by gebnar** [comment]
@MOOOOs This issue is almost certainly due to the fact that a new update for NMS has just dropped and mbincompiler is not yet updated to work with the new mbin structures. This should be fixed with the next release.

**Comment by monkeyman192** [comment]
Please wait until an update has been released for MBINCompiler. See #269 for details
