### ISSUE TITLE
Incorrect output in after running BUILDMOD.bat today.

### ISSUE THREAD

**Issue by Protiguous** [monkeyman192/MBINCompiler#271]
Just ran the BUILDMOD.bat today (2020-09-28) at it was progressing seemingly fine until the text started spewing out like this (non-english symbols??).

Answered "Y" to all 3 prompts.

I'm sorry, I don't know more details about what's causing this.

Here is a screenshot of where it started happening in the output.
(I'm going to try it again and see if it still spits out the nonsense.)

![image](https://user-images.githubusercontent.com/37120672/94489764-4e01c280-01a2-11eb-882f-505a92a04b22.png)

[log.txt](https://github.com/monkeyman192/MBINCompiler/files/5295249/log.txt)

**Comment by monkeyman192** [comment]
This looks to be an issue with [AMUMSS](https://github.com/MetaIdea/AMUMSS-nms-auto-modbuilder-updater-modscript-system)
The repo doesn't get updated really, but it would be better to raise a bug there than here. I'll pass this error on and close this though
