### ISSUE TITLE
can't open mbin - game version 64519

### ISSUE THREAD

**Issue by ghost** [monkeyman192/MBINCompiler#274]
Hello,

i have this issue:
[VERSION]: MBINCompiler v3.2.0.1
[ARGS]: "UNDERWATERTABLECOMMON.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: E:\ythdd\Downloads\mods\PSArcTool\METADATA\SIMULATION\ECOSYSTEM\ROLEDESCRIPTIONTABLES\UNDERWATER\UNDERWATERTABLECOMMON.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	25E15619B3FCBDC7	template:	cGcCreatureRoleDescriptionTable
[EXPECTED INFO]: GUID: 45465ADD88BB6EC3

[ERROR]: [AggregateException]: Une ou plusieurs erreurs se sont produites.
[MbinException]: Failed serializing GcCreatureRoleDescriptionTable to EXML.
[InvalidOperationException]: Erreur lors de la génération du document XML.
[ArgumentException]: '', valeur hexadécimale 0x01, est un caractère non valide.

   à System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   à System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   à System.Xml.XmlWellFormedWriter.WriteString(String text)
   à System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)

can you help us ? 

Thanks

**Comment by monkeyman192** [comment]
I'll leave this open because it does need investigation, but this issue is already known (see patch notes: https://github.com/monkeyman192/MBINCompiler/releases/tag/v3.02.0-pre1)
Maybe I should have been more explicit. I'll update the patch notes to make this clear what the files are I mean that don't work.

**Comment by ghost** [comment]
sorry, I haven't see it. (thanks)

**Comment by monkeyman192** [comment]
This file has now been removed as it was indeed deprecated by HG. Closing this issue now.
