### ISSUE TITLE
Sent ALL MBIN files for NMS v3.05 at the app at once for decompilation and it threw an error, said to report it via the log here

### ISSUE THREAD

**Issue by RandDenner** [monkeyman192/MBINCompiler#285]
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/5492806/MBINCompiler.log)

**Comment by RandDenner** [comment]
Oh, I see you are already aware of the issues with the 38 files in the METADATA\SIMULATION\ECOSYSTEM\ROLEDESCRIPTIONTABLES subdirectories.

Sorry!

**Comment by RandDenner** [comment]
Okay, so it wasn't just those files that have issues.
I found 74 that won't decompile at all, and another 8 that throw errors but seem to decompile fine anyway.
Here's my analysis:
[NMS v3.05 MBIN File Decompile Errors.txt](https://github.com/monkeyman192/MBINCompiler/files/5494223/NMS.v3.05.MBIN.File.Decompile.Errors.txt)
Hope it's useful!

**Comment by HolterPhylo** [comment]
Hi, please always have a look at the Report I share (under the username Wbertro#8596) in [https://discord.com/channels/215514623384748034/215569790801018880](url) after each MBINCompiler version update.  The Report details the files that you you un-covered...

The summary result is as follows: 
> 
Processed 39331 files
       74 files failed conversion to EXML

      136 files failed with size and difference
      127 files 'however' produced identical EXMLs and should be considered properly handled by MBINCompiler

        9 files 'did not' produce an identical EXML after re-compiling and de-compiling the original EXML

Fri Nov 27 16:09:04 2020

**Comment by RandDenner** [comment]
Yep, thanks. Saw that on Discord a while afterwards.

**Comment by monkeyman192** [comment]
I am guessing this is not an issue and can be closed...
