### ISSUE TITLE
Mislabeled life chance properties in BIOMELISTPERSTARTYPE.MBIN

### ISSUE THREAD

**Issue by clownmug** [monkeyman192/MBINCompiler#286]
Life chance and abandoned life chance have Yellow, Green, Blue, Red as properties but they should be Dead, Low, Mid, and Full like in CREATUREROLEDESCRIPTIONTABLE.MBIN.

Yellow = Dead
Green = Low
Blue = Mid
Red = Full

libMBIN (MBINCompiler) Version: 3.0.5-pre1
NMS Game Version: 3.05
MBIN File: BIOMELISTPERSTARTYPE.MBIN
MBIN File Version: 3.0.5

**Comment by monkeyman192** [comment]
Thanks for picking this up! This will be corrected in the next release (3.10.0-pre1)
