### ISSUE TITLE
[UPDATE] 6254225->6482827->6486179

### ISSUE THREAD

**Issue by HolterPhylo** [monkeyman192/MBINCompiler#303]
# New structs | GUID | NameHash | Size
- [x] GcAlienPodAnimParams                               | 0x0000000000000000| 0x998BA979A167FBB6| 0x4
- [ ] GcAtlasSendQuerySeasonData                         | 0x0000000000000000| 0xB3FF565AF020F672| 0x10
- [ ] GcAtlasSendSubmitSeasonStageCompleted              | 0x0000000000000000| 0x28ADD037AEDE77EB| 0x18
- [x] GcCostCanCustomiseCreature                         | 0x0000000000000000| 0xBA0DB1BC57263E28| 0x1
- [x] GcCreatureDiscoveryThumbnailOverride               | 0x0000000000000000| 0xF81E00514EB73ED9| 0x40
- [x] GcLootProbability                                  | 0x0000000000000000| 0xFCFB8A97D2A5B063| 0x88
- [x] GcMessageTitanFall                                 | 0x0000000000000000| 0x35A64B8A8E9358C9| 0x1
- [x] GcMissionConditionAllMilestonesComplete            | 0x0000000000000000| 0x088DB4BD2401DF5D| 0x4
- [x] GcMissionConditionBuildMenuOpen                    | 0x0000000000000000| 0x6E69D2515C835902| 0x1
- [x] GcMissionConditionExpeditionNearlyOver             | 0x0000000000000000| 0x188B717445D36858| 0x8
- [x] GcMissionConditionHasMultiTool                     | 0x0000000000000000| 0xF65D2CFF75A05B47| 0x8
- [x] GcMissionConditionHasSeasonalReward                | 0x0000000000000000| 0xAF8C0BAEB7E6A88D| 0x1
- [x] GcMissionConditionHasTwitchReward                  | 0x0000000000000000| 0xD5B7E38D470CFF7E| 0x1
- [x] GcMissionConditionIsDepotDestroyed                 | 0x0000000000000000| 0x2797515E3A43C26C| 0x20
- [x] GcMissionConditionIsScanEventRepaired              | 0x0000000000000000| 0xA601980170B475C0| 0x20
- [x] GcMissionConditionSystemPlanetTest                 | 0x0000000000000000| 0xB22694B55382153C| 0x1
- [x] GcMissionConditionSystemStarClass                  | 0x0000000000000000| 0x7073C98F12846D19| 0x4
- [x] GcMissionConditionUnclaimedStageReward             | 0x0000000000000000| 0xF1FBECB7917C1DF7| 0x1
- [x] GcMissionSequenceDisplaySeasonRewardReminder       | 0x0000000000000000| 0x6A64F8439AFA975E| 0x84
- [x] GcMissionSequenceRepairTech                        | 0x0000000000000000| 0xF83A832D3507037F| 0x110
- [x] GcMissionSequenceShowSeasonTimeWarning             | 0x0000000000000000| 0x232C5143BAE4E2F9| 0x104
- [x] GcMissionSequenceVisitPlanets                      | 0x0000000000000000| 0xA6EC06362FCAD424| 0x120
- [x] GcMissionSequenceWaitForStatSeasonal               | 0x0000000000000000| 0xCEBA3C32BCAF04F6| 0x128
- [x] GcMissionSequenceWaitRealTimeCombat                | 0x0000000000000000| 0xB497A82E7D25F7C4| 0x1A8
- [x] GcMultiSpecificItemEntry                           | 0x0000000000000000| 0x7439D28A897F0ACC| 0x50
- [x] GcPetMoodStaminaModifier                           | 0x0000000000000000| 0xE63B46A8CA0EF245| 0x1C
- [x] GcPetTraitStaminaModifier                          | 0x0000000000000000| 0x0DCD830657AF1993| 0x1C
- [x] GcRewardForceDiscoverSystem                        | 0x0000000000000000| 0xE76D1AFAE3C093FC| 0x1
- [x] GcRewardInventorySlots                             | 0x0000000000000000| 0xB34604C635F49B12| 0x4
- [x] GcRewardMissionMessageToMatchingSeeds              | 0x0000000000000000| 0x9688A6EC7C08672F| 0x18
- [x] GcRewardMultiSpecificItems                         | 0x0000000000000000| 0x26C3924987148B0B| 0x10
- [x] GcRewardRequirementsForRecipe                      | 0x0000000000000000| 0x0EC60D3F951991D7| 0x18
- [x] GcRewardSetWeaponSuppressed                        | 0x0000000000000000| 0x9983F7BCE55D938D| 0x1
- [x] GcRewardUnlockSeasonReward                         | 0x0000000000000000| 0x7AB9EBA17278DE9B| 0x18
- [x] GcScanEventTableType                               | 0x0000000000000000| 0x034D109FC6FD5709| 0x4
- [x] GcSeasonalRingArray                                | 0x0000000000000000| 0x4B1FC18F2123392C| 0x10
- [x] GcSeasonalRingData                                 | 0x0000000000000000| 0x772BC47975467C69| 0xC
- [x] GcSeasonalStage                                    | 0x0000000000000000| 0xF1949393FDAF963A| 0xD8
- [x] GcSeasonStateData                                  | 0x0000000000000000| 0x4BC716CF849F5A74| 0x40
- [x] GcTargetMissionSurveyOptions                       | 0x0000000000000000| 0x4E7A7CEB00A9346B| 0x198
- [x] GcUnlockableSeasonReward                           | 0x0000000000000000| 0xC06F148BB67FE0E2| 0x30
- [x] GcUnlockableSeasonRewards                          | 0xBAD34AF4FE7A0E56| 0x3EB0EF943FFD976E| 0x10
- [x] GcUnlockableTwitchReward                           | 0x0000000000000000| 0xE9EC3242091011CC| 0x30
- [x] GcUnlockableTwitchRewards                          | 0xF1CF258442B95850| 0xF128895FDB533FA8| 0x10
- [x] TkMaterialShaderMillComment                        | 0x0000000000000000| 0x69D7A72052C55F5E| 0x410
- [x] TkMaterialShaderMillConnect                        | 0x0000000000000000| 0xE65D6D9E5CB7E8A3| 0x28
- [x] TkMaterialShaderMillData                           | 0x0000000000000000| 0xE5F4152C8F8FC861| 0x58
- [x] TkMaterialShaderMillLink                           | 0x0000000000000000| 0xFC506DC8F06CBE6D| 0x78
- [x] TkMaterialShaderMillNode                           | 0x0000000000000000| 0x465D81033D79E7BB| 0x80

# Removed/Missing structs | GUID | NameHash | Size
- [x] TkMaterialSketchComment                            | 0xE39DD18EF82E623F| 0x4BCC54BC6EF02B80| 0x410
- [x] TkMaterialSketchConnect                            | 0x9761F1A258006A2C| 0x3C0B60A90EFF93A9| 0x28
- [x] TkMaterialSketchData                               | 0xF0E26C56F25263E1| 0x6BD985F678734B62| 0x58
- [x] TkMaterialSketchLink                               | 0xED96E8137A0A3606| 0x6AA5956429CD2D5D| 0x78
- [x] TkMaterialSketchNode                               | 0xB5719C924E6DC6FC| 0x8A6FCDF95D18002E| 0x80

# Structs with internal changes | GUID | NameHash | Size
- [ ] GcAlienPuzzleTable                                 | 0x4ED308E278E67258| 0x05F6B19969ECDDFE| 0x10
- [x] GcBaseBuildingTable                                | 0x0159731E2911A354| 0x69B43206529CA591| 0x1B70
- [x] GcConsumableItemTable                              | 0x75D905A089ADB7E0| 0xA9AA29AB69917BF0| 0x10
- [x] GcCostTable                                        | 0x803EC1794084EEB7| 0x6E62CCB542C4E505| 0x50
- [x] GcCustomisationShipBobbleHeads                     | 0x090073A922E595FC| 0x9822B1463FFAFC3F| 0x10
- [ ] GcExpeditionEventTable                             | 0x0F753F635691AC4D| 0xD5BCFB328D8A80A8| 0x20
- [x] GcExpeditionRewardTable                            | 0x09ACB4C2268914BB| 0xDFC93B6F3652FDE5| 0x10
- [ ] GcExperienceSpawnTable                             | 0xDBA9E65E06DDD541| 0x5F4CA33999F0D259| 0x110
- [ ] GcExplosionDataTable                               | 0xE399C83E8E6F8680| 0xF9FB8E431EB1179F| 0x10
- [x] GcGeneratedBaseTemplatesTable                      | 0x0DCD505A797249A2| 0x7F0943EC9DBC0BDD| 0x40
- [x] GcInputActionInfoMap                               | 0x006243D528366BE6| 0xBEAB285DC115E7C6| 0x2BB90
- [ ] GcInteractionComponentData                         | 0xB3C267BD0F1354F3| 0xDAB0554EA36957B5| 0x2D0
- [ ] GcInventoryTable                                   | 0x144190C40A6C2977| 0x32822FA2FD268A65| 0x898
- [x] GcJourney                                          | 0x73BD2E52B9F59B2D| 0xFADF3E5CAB7333FF| 0x10
- [x] GcJourneyMilestoneTable                            | 0x00A4768229DACCC1| 0xD2E65AA0EC314D9C| 0x10
- [x] GcMissionTable                                     | 0xA1B9619A57778C65| 0x26335C55292A7766| 0x10
- [ ] GcNGuiSpecialTextImages                            | 0x074258C82775950C| 0x4A7B04831F4234B1| 0x10
- [ ] GcNGuiSpecialTextStyles                            | 0xD1752B2A47080504| 0x9E60066285AC5880| 0x10
- [x] GcNPCSpawnTable                                    | 0x7E2CEE7E338663F0| 0xEF1AB4FE11FCFA6D| 0x440
- [x] GcPlayerDamageTable                                | 0x14F40E8752ECF9C6| 0x040154165764DAC5| 0x10
- [x] GcProceduralProductTable                           | 0xB62F3421FE013845| 0x9A0073340429C464| 0xE520
- [x] GcProceduralTechnologyTable                        | 0xDA064475EE1EB329| 0x80ED6EE04AC8D620| 0x10
- [x] GcProductTable                                     | 0xB298C5330E3BC5AB| 0x7A62ED648FC514F7| 0x10
- [ ] GcProjectileDataTable                              | 0x72D98F9A1DBA5C7E| 0x9439AD97E8673BC0| 0x20
- [x] GcRecipeTable                                      | 0xF736FF0677339B90| 0xB05B3758665D56DE| 0x10
- [x] GcScanEventTable                                   | 0x6B48A4AC889478EA| 0x0D550A58E83EA253| 0x10
- [ ] GcStatDefinitionTable                              | 0xE7448A429BE1CA64| 0x2BFE1835E7B1EFEC| 0x10
- [ ] GcSubstanceTable                                   | 0x21A169BEB95AF61F| 0x390E6B7795024BAB| 0x20
- [x] GcTechnologyTable                                  | 0x567D5EFD542E519F| 0x7BF27C8F05ED20B7| 0x10
- [x] GcVehicleScanTable                                 | 0x39E37E0E5D0EA9DF| 0x78967207D9C549AA| 0x10
- [x] GcVibrationDataTable                               | 0xBC1D97718BFD9814| 0x75E1ADCE47B381E6| 0x10
- [x] GcWeatherEffectTable                               | 0x9525B0BF45E8FA1B| 0x6AE3CB3B6A5A155D| 0x10
- [x] GcWiki                                             | 0x82EAF2218E0F4C34| 0x1037140D8873D8ED| 0x10
- [x] TkMaterialData                                     | 0x61E6156B7B668D85| 0xCEE695A798E64B92| 0x2E0
- [x] TkNGuiEditorLayout                                 | 0x055A2F338BBCB7BA| 0x7CDF4EDAA0962EA0| 0x10A400
- [x] TkParticleData                                     | 0x0E4D91D086120647| 0xE9525144C4F949EB| 0x100

# Structs with a file size change:
- [x] GcAlienPodComponentData                            | old: 0x44   | new: 0x40   | GUID: 0x0000000000000000
- [x] GcAlienPuzzleMissionOverride                       | old: 0x30   | new: 0x38   | GUID: 0x0000000000000000
- [x] GcAntagonistComponentData                          | old: 0x118  | new: 0x148  | GUID: 0x0000000000000000
- [ ] GcAtlasRecvDiscoveryList                           | old: 0x125E0| new: 0x6E2A0| GUID: 0x0000000000000000
- [x] GcBiomeFileList                                    | old: 0x120  | new: 0x130  | GUID: 0xCA4117113AA28365
- [x] GcCreatureComponentData                            | old: 0x50   | new: 0x70   | GUID: 0x0000000000000000
- [x] GcCustomisationThrusterEffect                      | old: 0xC8   | new: 0xF0   | GUID: 0x0000000000000000
- [x] GcCustomisationThrusterEffects                     | old: 0x20   | new: 0x30   | GUID: 0xC23D96F32E4BAF96
- [ ] GcDebugScene                                       | old: 0x1490 | new: 0x1AB0 | GUID: 0x611B2B10B024223B
- [x] GcDefaultSaveData                                  | old: 0x2B2F0| new: 0x2C2C0| GUID: 0x03081A69D1103AFE
- [ ] GcDestructableComponentData                        | old: 0x1D8  | new: 0x1F8  | GUID: 0x0000000000000000
- [x] GcExplosionData                                    | old: 0xC0   | new: 0xC8   | GUID: 0x0000000000000000
- [x] GcGalaxyCameraData                                 | old: 0x68   | new: 0x6C   | GUID: 0x0000000000000000
- [x] GcGalaxyRenderSetupData                            | old: 0x210  | new: 0x350  | GUID: 0x0000000000000000
- [x] GcGenericMissionSequence                           | old: 0x4A0  | new: 0x4B0  | GUID: 0x0000000000000000
- [x] GcLootComponentData                                | old: 0x20   | new: 0x38   | GUID: 0x0000000000000000
- [x] GcMissionConditionIsScanEventLocal                 | old: 0x20   | new: 0x28   | GUID: 0x0000000000000000
- [x] GcMissionConditionIsScanEventLocalOrNear           | old: 0x28   | new: 0x30   | GUID: 0x0000000000000000
- [x] GcMissionConditionRefinerHasOutput                 | old: 0x28   | new: 0x18   | GUID: 0x0000000000000000
- [x] GcMissionSequenceCollectMoney                      | old: 0x108  | new: 0x10C  | GUID: 0x0000000000000000
- [x] GcMissionSequenceGetToScanEvent                    | old: 0x238  | new: 0x3B8  | GUID: 0x0000000000000000
- [x] GcMissionSequenceGroup                             | old: 0x290  | new: 0x410  | GUID: 0x0000000000000000
- [x] GcMissionSequencePirates                           | old: 0xB8   | new: 0xC0   | GUID: 0x0000000000000000
- [x] GcMissionSequenceWaitForScanEvent                  | old: 0x230  | new: 0x3B0  | GUID: 0x0000000000000000
- [x] GcMissionSequenceWaitRealTime                      | old: 0x110  | new: 0x128  | GUID: 0x0000000000000000
- [ ] GcNPCDebugSpawnData                                | old: 0x260  | new: 0x380  | GUID: 0x0000000000000000
- [x] GcPetBehaviourTable                                | old: 0xFE8  | new: 0x1008 | GUID: 0x27F11C8E2215E0EB
- [x] GcPetData                                          | old: 0xF0   | new: 0x1F0  | GUID: 0x0000000000000000
- [x] GcPhotoModeSettings                                | old: 0x50   | new: 0x60   | GUID: 0x0000000000000000
- [x] GcPlayerDamageData                                 | old: 0x140  | new: 0x160  | GUID: 0x0000000000000000
- [x] GcPlayerExperienceSpawnData                        | old: 0x78   | new: 0x98   | GUID: 0x0000000000000000
- [x] GcPlayerStateData                                  | old: 0x2B240| new: 0x2C210| GUID: 0x0000000000000000
- [x] GcPulseEncounterInfo                               | old: 0x178  | new: 0x198  | GUID: 0x0000000000000000
- [x] GcRealityIconTable                                 | old: 0x5030 | new: 0x50B8 | GUID: 0x0000000000000000
- [x] GcRealityManagerData                               | old: 0xD2A0 | new: 0xD6A0 | GUID: 0x6C64322C18E67BAA
- [x] GcRewardActivateFiends                             | old: 0x1    | new: 0x10   | GUID: 0x0000000000000000
- [x] GcRewardDisguisedProduct                           | old: 0x30   | new: 0x40   | GUID: 0x0000000000000000
- [x] GcRewardHazard                                     | old: 0x8    | new: 0xC    | GUID: 0x0000000000000000
- [x] GcRewardMissionSeeded                              | old: 0x20   | new: 0x28   | GUID: 0x0000000000000000
- [x] GcRewardMultiSpecificProducts                      | old: 0x10   | new: 0x30   | GUID: 0x0000000000000000
- [x] GcRewardSpecificShip                               | old: 0x428  | new: 0x458  | GUID: 0x0000000000000000
- [x] GcRewardSpecificWeapon                             | old: 0x230  | new: 0x240  | GUID: 0x0000000000000000
- [x] GcRewardTable                                      | old: 0xF0   | new: 0x110  | GUID: 0x560FBAD5354B4033
- [x] GcRewardUnlockTitle                                | old: 0x10   | new: 0x18   | GUID: 0x0000000000000000
- [x] GcScannerIcons                                     | old: 0xFB40 | new: 0x12540| GUID: 0xAAF97EB9DB2E77B9
- [x] GcSeasonalGameModeData                             | old: 0xE8   | new: 0x450  | GUID: 0x352AB6DFBF7B1FD8
- [x] GcSeasonalMilestone                                | old: 0x40   | new: 0x558  | GUID: 0x0000000000000000
- [x] GcStatIconTable                                    | old: 0x5080 | new: 0x5180 | GUID: 0x0000000000000000
- [x] GcTechnology                                       | old: 0x350  | new: 0x360  | GUID: 0x0000000000000000
- [x] GcTradeData                                        | old: 0xB0   | new: 0xB8   | GUID: 0x0000000000000000
- [x] GcTradeSettings                                    | old: 0xC60  | new: 0xDA8  | GUID: 0x0000000000000000
- [ ] GcUserSettingsData                                 | old: 0x3938 | new: 0x3960 | GUID: 0x4EF81A05468A9B00
- [x] GcWeatherEffect                                    | old: 0x138  | new: 0x1C0  | GUID: 0x0000000000000000
- [x] GcWikiTopic                                        | old: 0xF0   | new: 0x170  | GUID: 0x0000000000000000
- [x] TkEngineSettingsMapping                            | old: 0x78   | new: 0x7C   | GUID: 0x4E677597C10B7408
- [x] TkGraphicsDetailPreset                             | old: 0x2C   | new: 0x34   | GUID: 0x0000000000000000
- [x] TkGraphicsSettings                                 | old: 0x198  | new: 0x1A0  | GUID: 0x63ED58C9662E5D01
- [x] TkMaterialMetaData                                 | old: 0x4B0  | new: 0x4C0  | GUID: 0x0000000000000000
- [x] TkNGuiEditorStyleData                              | old: 0x9F90 | new: 0xAEA0 | GUID: 0x97BBEC400DB04410
# GLOBALS with GUID changed:
- [x] GcAISpaceshipGlobals                     | old 0x2624BDF53371AE48, 0x11E0| new 0xF38F52C515C77963, 0x1230
- [x] GcBuildingGlobals                        | old 0x679DA653FB2E0CB7, 0x3C0| new 0xC942FEAF55D6265D, 0x3D0
- [x] GcCameraGlobals                          | old 0xC0E430882673D987, 0x5840| new 0x5A97F710157A2074, 0x5890
- [x] GcCreatureGlobals                        | old 0x7D053D861FDE6432, 0x3F40| new 0x3E4661EE52DC24D4, 0x4428
- [x] GcDebugOptions                           | old 0x0F1234829ECDB7C5, 0x1FE0| new 0x3A0ABD79424C4E21, 0x25F8
- [x] GcGalaxyGlobals                          | old 0xA5FCAF8F3E12D373, 0x1D80| new 0xBED38FC0F18F4ABA, 0x26C0
- [x] GcGameplayGlobals                        | old 0x085A5211674820B3, 0x1DF0| new 0x272668FEFEEC95B6, 0x1F8C
- [x] GcGraphicsGlobals                        | old 0x5B8F3D449F3BDED1, 0x9C0| new 0xF8372A5337A07B2D, 0xA30
- [x] GcPlayerGlobals                          | old 0x6A8A84FDBD56764A, 0x1CE0| new 0xE1FF6D5955EA6F71, 0x1DC4
- [x] GcRobotGlobals                           | old 0x54E7CDFB76E9FC4C, 0x640| new 0xFCC6E4AB6ABA83F7, 0x680
- [x] GcSolarGenerationGlobals                 | old 0xE5E5B707523C6390, 0x3E0| new 0xCF1B1EB60E963DD0, 0x3FC
- [x] GcSpaceshipGlobals                       | old 0xCB9A3722313BF580, 0x1290| new 0x5711225DD23BB556, 0x12E0
- [x] GcTerrainGlobals                         | old 0xB6A014424B0C7035, 0x400| new 0x9D5FB82FF4D44F8E, 0x430
- [x] GcUIGlobals                              | old 0x02D634E9F5F38006, 0x6E00| new 0x89A1D3829F153672, 0x7080
# GLOBALS with same GUID, different Size or ...:
- [x] GcAudioGlobals                           | old 0x83595753419F7B77, 0x150| new 0x83595753419F7B77, 0x164
- [x] GcEnvironmentGlobals                     | old 0x4AB168D8BF669DDC, 0x6F0| new 0x4AB168D8BF669DDC, 0x740
- [x] GcFleetGlobals                           | old 0x0DE9B2EF02F090A8, 0x2470| new 0x0DE9B2EF02F090A8, 0x254C
- [ ] GcSceneOptions                           | old 0xE631F099F9410CAB, 0x2B0| new 0xE631F099F9410CAB, 0x2C0
- [ ] GcScratchpadGlobals                      | old 0xC14472951E47BFF8, 0x27D0| new 0xC14472951E47BFF8, 0x2810
- [ ] GcSimulationGlobals                      | old 0x49EEE64199B4DFF2, 0x1F90| new 0x49EEE64199B4DFF2, 0x1FF0
- [x] GcSkyGlobals                             | old 0xB296374F545CDF71, 0x1150| new 0xB296374F545CDF71, 0x1160
- [ ] GcVehicleGlobals                         | old 0x0107CD7DE6B7F761, 0x7630| new 0x0107CD7DE6B7F761, 0x7670

**Comment by HolterPhylo** [comment]
Replaces Issue #302
Transferred check info from #302
Removed empty GUID in 'Structs with internal changes'

> -->> To come: clean-up for those structs that did not change...

Added all available GUIDs from MBINs
Hope it is not so lagging !

**Comment by HolterPhylo** [comment]
DONE: Clean-up of 'Structs with internal changes'
Removed all those where the GUID did not changed between the MBIN and MBINCompiler .cs file.

The list does not included those structures where we do not know at the moment if they changed internally...

**Comment by HolterPhylo** [comment]
No change I could detect

**Comment by Geobert** [comment]
Thank you for the pre1 release!

I tried to recompile https://www.nexusmods.com/nomanssky/mods/1857 with it but it fails and finding this issue explained why: GcCameraGlobals  is not up to date yet. 

Am I right?

Hope to see a version with GcCameraGlobals updated so I can play the game :D (I'm subject to motion sickness, unfortunately)

EDIT: lua script for reference
```lua
NMS_MOD_DEFINITION_CONTAINER = 
{
["MOD_FILENAME"] 			= "NOSHAKE.pak",
["MOD_AUTHOR"]				= "mrargful",
["NMS_VERSION"]				= "3.21",
["MODIFICATIONS"] 			= 
	{
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.59B126E2.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= "GCCAMERAGLOBALS.GLOBAL.MBIN",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = {"CameraShakeTable"},
							["REPLACE_TYPE"] 	= "ALL",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Active",					"False"}						
							}
						}
					}
				}
			}
		}
	}	
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE
```

**Comment by horatiohafnaugels** [comment]
GcEnvironmentGlobals is not included in the list, but after 3.30 MBINCompiler is not able to decompile the related file anymore (this happens with v3.34.0-pre1 too). I write this to make sure you're aware of it.

Thank you for reading and my apologies if this report is somehow redundant.

**Comment by monkeyman192** [comment]
@horatiohafnaugels and @Geobert please see the release report: https://github.com/monkeyman192/MBINCompiler/releases/latest/download/report.json
You will notice that the files you are asking about are not passing so they are not suported. Hopefully globals will be supported within a day or two (should be in next release...)

**Comment by chrispurnell** [comment]
I have the globals decompling.  Should I send a pull request?

**Comment by monkeyman192** [comment]
@chrispurnell sorry, only just saw your comment. You are of course welcome to! @HolterPhylo has also got a PR in for them too so you can compare and see if your changes add anything to the code once it's merged 😄
