### ISSUE TITLE
Several MBIN files in the latest No Man's Sky could not be decompiled

### ISSUE THREAD

**Issue by Frolonov** [monkeyman192/MBINCompiler#304]
GCFLEETGLOBALS.GLOBAL.MBIN
COSTTABLE.MBIN
NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
NMS_U3REALITY_GCTECHNOLOGYTABLE.MBIN
REWARDTABLE.MBIN
[error1.txt](https://github.com/monkeyman192/MBINCompiler/files/6253496/error1.txt)
[error2.txt](https://github.com/monkeyman192/MBINCompiler/files/6253497/error2.txt)
[error3.txt](https://github.com/monkeyman192/MBINCompiler/files/6253498/error3.txt)
[error4.txt](https://github.com/monkeyman192/MBINCompiler/files/6253499/error4.txt)
[error5.txt](https://github.com/monkeyman192/MBINCompiler/files/6253500/error5.txt)

**Comment by monkeyman192** [comment]
We know about this (see #303 )
Due to some changes updating is slower than usual, so please just be patient :)
