### ISSUE TITLE
NMS_REALITY_GCTECHNOLOGYTABLE.MBIN  : Failed to read GcTechnologyTable from MBIN

### ISSUE THREAD

**Issue by BradfordCB** [monkeyman192/MBINCompiler#311]
_Fill in the details for each relevant section._
[VERSION]: MBINCompiler v3.21.0.2
[ARGS]: "convert" "-y" "-f" "P:\No Mans Sky Mods\Projects NMS BCB\BCB Weapons Mod210402\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: P:\No Mans Sky Mods\Projects NMS BCB\BCB Weapons Mod210402\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	567D5EFD542E519F	template:	cGcTechnologyTable
  [EXPECTED INFO]: GUID: BB83ED584A541A8D
  

[ERROR]: [MbinException]: Failed to read GcTechnologyTable from MBIN.
  [InvalidListException]: Invalid list read, magic 00000005 expected xxxxxx01 at 0x610
  
  [INFO]: P:\No Mans Sky Mods\Projects NMS BCB\BCB Weapons Mod210402\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	567D5EFD542E519F	template:	cGcTechnologyTable
  
     at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read GcTechnologyTable from MBIN.
  [FILE]: P:\No Mans Sky Mods\Projects NMS BCB\BCB Weapons Mod210402\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
  
[INFO]: 1 WARNINGS.

  [WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [FILE]: P:\No Mans Sky Mods\Projects NMS BCB\BCB Weapons Mod210402\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
  
[INFO]: TIME: 0.033 seconds

**Comment by monkeyman192** [comment]
You look to be using an old version of MBINCompiler. If you are trying to decompile the latest files please use the latest version :)

**Comment by BradfordCB** [comment]
I downloaded and used the version that was released two days ago (v3.35.0-pre1). I tried several times to no avail. It unpacked another Mbin file fine but not NMS_REALITY_GCTECHNOLOGYTABLE.MBIN. I would like to eventually upload my mod to Nexus.
Thanks for making this program.

Bradford

**Comment by BradfordCB** [comment]
I got it to work! 
Thanks so much for your time.

Bradford
