### ISSUE TITLE
Spelling error: CgExpeditionCategoryStrength instead of GcExpeditionCategoryStrength

### ISSUE THREAD

**Issue by cmkushnir** [monkeyman192/MBINCompiler#318]
Spelling error:
CgExpeditionCategoryStrength instead of GcExpeditionCategoryStrength - both class and file names

**Comment by HolterPhylo** [comment]
Hi, HG never corrected that structure name, it is still CgExpeditionCategoryStrength in the exe as far as I know

And Hi from a fellow Canadian!

**Comment by cmkushnir** [comment]
>> And Hi from a fellow Canadian!
:)

**Comment by cmkushnir** [comment]
Spelling believed to be correct, source of error in game not libMBIN.
