### ISSUE TITLE
Possibly incorrect removal of EnumType

### ISSUE THREAD

**Issue by cmkushnir** [monkeyman192/MBINCompiler#326]
Looking at the actual data in the file it appears AlienRaceEnum is correct.
Why was the EnumType removed and the type converted from an Array to a List ?

/libMBIN/Source/NMS/Globals/GcSolarGenerationGlobals.cs

3.34.0-pre2:
        [NMS(Size = 0x8, EnumType = typeof(GcAlienRace.AlienRaceEnum))]     // I think this is the enum type...
        /* 0x200 */ public GcAISpaceshipWeightingData[] SpaceshipWeightings;

3.35.0-pre1
       /* 0x208 */ public List&lt;GcAISpaceshipWeightingData&gt; SpaceshipWeightings;

**Comment by monkeyman192** [comment]
It has definitely changed to a list. The tests would not pass if it had not, and also I just looked in the mbin file itself and it's 100% a list
