### ISSUE TITLE
[Update] Changes for 3.40 (6694623)

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#329]
### New structs:

- [x] GcMissionConditionInteractionIndexChanged	0xCBEC9072D0C53896
- [x] GcMissionConditionNearestBuilding	0x2591D16D8CEA8D4E
- [x] GcMissionConditionSeasonNumber	0x9AA8CC133BED2E72
- [x] GcSeasonalMilestoneEncryption	0xD85DFF8ADAEB741D

### Structs with internal changes:

- [x] GcAlienPuzzleEntry	0x8B7426F1428C8C87
- [x] GcAlienPuzzleTable	0x84101C811E351439
- [x] GcCostTable	0x4EFEFA33DBBF5159
- [x] GcDefaulMissionProduct	0x8C189820A362520F
- [x] GcDefaultMissionItemsTable	0xE040D1760E6B87E1
- [x] GcExpeditionRewardTable	0xE4D543329507BCFA
- [x] GcGenericRewardTableEntry	0xE25C066881788006
- [x] GcInteractionComponentData	0xA96F674CC17037F3
- [x] GcInteractionType	0x3312ECE81220D1FF
- [x] GcMissionConditionHasProduct	0xD184553D0179DC39
- [x] GcMissionConditionHasTechnology	0xB78074E3F1EFC33B
- [x] GcMissionConditionIsTechnologyRepaired	0x6C83910E4F5375A3
- [x] GcMissionConditionProductKnown	0xB979E71DDCD32E2A
- [x] GcMissionConditionTechnologyKnown	0x16AAE01577BF5445
- [x] GcMissionSequenceCollectProduct	0xE740187C9278D774
- [x] GcMissionSequenceRepairTech	0x5F1FB2F7C63E5760
- [x] GcMissionTable	0xA06E543CCD6340C5
- [x] GcNPCPlacementInfo	0xDCDFAF5EBCC7DF34
- [x] GcNPCSpawnTable	0xFC090610940F36B3
- [x] GcPlayerTitle	0x38F1CA903056BF52
- [x] GcPlayerTitleData	0xC78ECEA79E607B6E
- [x] GcRewardIncrementInteractionIndex	0x9F57A5594FF4F5F7
- [x] GcRewardTableCategory	0xF42FD2358DCAA885
- [x] GcRewardTableEntry	0xD6D51C085D901623
- [x] GcRewardTableItemList	0xD424AC8983D873D8
- [x] GcScanEventData	0xA53093C86BB6F82E
- [x] GcScanEventTable	0x2AACE57A0B6D1452
- [x] GcSeasonStateData	0x72A849FE6FF40A2E
- [x] GcSeasonalStage	0x2527AC6B9E39D4F8
- [x] GcUnlockableSeasonRewards	0xE5F4D8D17FB06A9F
- [x] gcproducttableEnum	0xEC311FBC38AA8BA5
- [x] gctechnologytableEnum	0x6D804AABF1756F2B

### Structs with a file size change:

- [x] GcCostTableEntry	old: 0x68	new: 0x88	GUID: 0xC1902D5884D707C2	fields: 9	
- [x] GcDefaultSaveData	old: 0x2C2E0	new: 0x2C340	GUID: 0x919E6F4D01504722	fields: 2	
- [x] GcMissionConditionAllMilestonesComplete	old: 0x4	new: 0x8	GUID: 0x124458932833A2E6	fields: 2	
- [x] GcMissionSequenceSetCurrentMission	old: 0x90	new: 0x98	GUID: 0xA3B5E6806301CC0C	fields: 3	
- [x] GcPlayerStateData	old: 0x2C230	new: 0x2C290	GUID: 0x9E5E9CF44AA13A15	fields: 196	
- [x] GcRewardOSDMessage	old: 0xC0	new: 0xD0	GUID: 0x57E12825C5D9CB1A	fields: 6	
- [x] GcRewardTable	old: 0x110	new: 0x130	GUID: 0x29F1A6CFFB862932	fields: 19	
- [x] GcRewardUnlockSeasonReward	old: 0x18	new: 0x40	GUID: 0xE6212DF525ECA350	fields: 5	
- [x] GcSeasonalGameModeData	old: 0x450	new: 0x498	GUID: 0x35B0C9DA67415CD3	fields: 36	
- [x] GcSeasonalMilestone	old: 0x758	new: 0x8F8	GUID: 0x2EEEDEBB6597DC9E	fields: 21	
- [x] GcUnlockableSeasonReward	old: 0x30	new: 0x38	GUID: 0x22227A02DF0A88DD	fields: 4	

### Structs with a field number changes:

- [x] GcGenericMissionSequence	old: 0x4B0	new: 0x4B0	GUID: 0xB03083BD34A47971	fields: 50	
- [x] GcMissionSequenceWaitForConditions	old: 0x120	new: 0x120	GUID: 0x447961099A4C8366	fields: 6

**Comment by HolterPhylo** [comment]
GcMissionConditionConvertedFromSeason 0xE03A68301E8C7DD3 is NOT a new struct, already correct
GcUIGlobals old: 0x4480 new: 0x44F0 GUID: 0xC8CF05F1144F378E fields: 1135 is already THIS, no need to list it

**Comment by monkeyman192** [comment]
@HolterPhylo thanks! I don't think I was diff-ing from the most recent version before the update, but it was the latest I had 😅

**Comment by HolterPhylo** [comment]
If you are ok with it, I'll repost my list so I can check-out items too.  I now use the .exe against current MBINCompiler, so it does not matter if the most recent is not the latest.  If I do, I'll close the preceding issue since it will be rolled-over!

**Comment by monkeyman192** [comment]
@HolterPhylo I realised I +1'd your comment but you probably didn't get a notification about it, so go ahead!

**Comment by HolterPhylo** [comment]
# New structs | GUID | NameHash | Size | Fields:
- [x] GcMissionConditionInteractionIndexChanged          | 0xCBEC9072D0C53896| 0x42109FD0D90982DB| 0x8    | 2
- [x] GcMissionConditionNearestBuilding                  | 0x2591D16D8CEA8D4E| 0x116C1EDD24B089D5| 0x8    | 2
- [x] GcMissionConditionSeasonNumber                     | 0x9AA8CC133BED2E72| 0x56F9C280B6CFD741| 0x4    | 1
- [x] GcSeasonalMilestoneEncryption                      | 0xD85DFF8ADAEB741D| 0x9562AF9028346F05| 0x180  | 7

# Removed/Missing structs | GUID | NameHash | Size | Fields:
- [x] GcBaseBuildingObjectTypes                          | 0x9C2FA5C781B3CA2E| 0x__NH_MISSING____| ___SIZE_MISSING___| 1
- [x] GcCustomisationJetpackThrusterEffects              | 0x0B312AEA88F41EBE| 0xF437AEF1AED36067| 0x10   | 1

# Structs with internal changes | GUID | NameHash | Size | Fields:
- [ ] GcAlienPuzzleEntry                                 | 0x8B7426F1428C8C87| 0xDE1F17CE7E01A8C2| 0x118  | =
- [ ] GcAlienPuzzleOption                                | 0x6C24072B3EE63D63| 0x3FE862FE8570BE69| 0xE0   | =
- [ ] GcAlienPuzzleTable                                 | 0x84101C811E351439| 0x05F6B19969ECDDFE| 0x10   | =
- [ ] GcAtlasDiscoveryData                               | 0x8B10056FD8A6F907| 0x34272E24BB717FCB| 0x48   | =
- [ ] GcAtlasRecvBaseImages                              | 0x86590CF5159C1D17| 0xC3C14D18029FA426| 0x28   | =
- [ ] GcAtlasSendSubmitMessage                           | 0x2A2E2F3930C60758| 0x3F2A102EA6C0D44B| 0xD0   | +2
- [ ] GcAtlasSendSubmitMonument                          | 0xAEBC854578DE6E33| 0xF4282F250D0EEBDB| 0x1D0  | =
- [ ] GcAtlasSendSubmitSeasonStageCompleted              | 0x5E31B1DF93F2028A| 0x28ADD037AEDE77EB| 0x18   | +3
- [ ] GcAudioAreaTriggerComponentData                    | 0x4E6A71B1E4A9D0BA| 0xD1618D63DA15668C| 0x10   | =
- [ ] GcConsumableItem                                   | 0x08F04CA50192A645| 0xDA5F4DFE0527A693| 0x100  | =
- [ ] GcCostProduct                                      | 0xA3FCD9E831043706| 0xE90BC34FB3DEA4D7| 0x20   | =
- [ ] GcCostTable                                        | 0x4EFEFA33DBBF5159| 0x6E62CCB542C4E505| 0x50   | =
- [ ] GcCreatureCrystalMovementData                      | 0xF1265534B68F266F| 0x46EB806ED8904120| 0x10   | =
- [ ] GcCreatureCrystalMovementDataParams                | 0x4FEE7E782DFFD1B5| 0x1232AC16AD2DF95C| 0x138  | =
- [ ] GcCustomisationGroup                               | 0xC1D1716D86A52E9B| 0x0B5A01AE676FD46D| 0xA8   | =
- [ ] GcDamageMultiplierLookup                           | 0x31B87E042D974AFE| 0x792FD0F5EBBA55E9| 0x28   | =
- [ ] GcDefaultMissionProduct                            | 0x8C189820A362520F| 0x1F78606838C7F310| 0x4    | =
- [ ] GcDefaultMissionItemsTable                         | 0xE040D1760E6B87E1| 0x87FB8E825C599E66| 0x40   | =
- [ ] GcExpeditionRewardTable                            | 0xE4D543329507BCFA| 0xDFC93B6F3652FDE5| 0x10   | =
- [ ] GcExperienceDebugTriggerAction                     | 0x462286389EE0D6E6| 0x3339FF1DC3ABF146| 0x8    | =
- [ ] GcExperienceDebugTriggerActionTypes                | 0xE6F822773EA9F012| 0x902E6B8A4F1B75A6| 0x4    | =
- [ ] GcExperienceDebugTriggerInput                      | 0x3D6FBF736C7B2220| 0x0BCDA670B36E2534| 0x18   | =
- [ ] GcFrigateInteractionAction                         | 0xAD1975B8FA694E7C| 0xD1183794AF82FF99| 0x28   | =
- [ ] GcGalaxyWaypoint                                   | 0xFF20FABD019768C3| 0x562052A8272CC4A3| 0x38   | =
- [ ] GcGalaxyWaypointTypes                              | 0x895A0820CE617DE4| 0xF808614547AF2B25| 0x4    | =
- [ ] GcGenericIconTypes                                 | 0x87544BCF24578A79| 0xA4091406380F5113| 0x4    | =
- [ ] GcGenericMissionSequence                           | 0xB03083BD34A47971| 0xFAE86B2801335B6D| 0x4B0  | +1
- [ ] GcGenericRewardTableEntry                          | 0xE25C066881788006| 0xB457288101712FB5| 0x28   | =
- [ ] GcGrabPlayerComponentData                          | 0x9F444523B5C3C892| 0xDE6FCE33E294F619| 0x320  | =
- [ ] GcHUDStartup                                       | 0x82950635D89DFA72| 0x4B24756D3BA22E88| 0x8    | =
- [ ] GcHUDStartupTable                                  | 0x8BA6DC3475A632C3| 0xB0A39161047DD10D| 0x80   | =
- [ ] GcInteractionComponentData                         | 0xA96F674CC17037F3| 0xDAB0554EA36957B5| 0x2D0  | =
- [ ] GcInteractionType                                  | 0x3312ECE81220D1FF| 0x47E189998F5D82E7| 0x4    | =
- [ ] GcInventoryBaseStat                                | 0xCB86CFCCBC8AEF97| 0x88CEC164B6BD4ACC| 0x30   | =
- [ ] GcInventoryBaseStatBonus                           | 0xFB1C90CB69054C1C| 0xCBEE12530E8A51CD| 0x8    | =
- [ ] GcInventorySlotActionData                          | 0xCBB0E901D8B668B5| 0xC08D0836890AA2D6| 0x1C   | =
- [ ] GcJourneyCategory                                  | 0x1D45AD369A7A2FE8| 0x88F1E142115EF824| 0x188  | =
- [ ] GcLaserBeamData                                    | 0x84B315E44C6B35B3| 0x1AA966F8BA4E3153| 0x1C0  | =
- [ ] GcMarkerComponentData                              | 0x4F3FB3E99D075F87| 0x499B7E363F46B54F| 0x38   | =
- [ ] GcMessageProjectileImpact                          | 0xFDB58E6F6DB84456| 0x7EBC25FE326CF24B| 0x50   | +1
- [ ] GcMissionBoardOptions                              | 0xCA65A99C3B10391B| 0xDD272E15749CCDF5| 0x80   | =
- [ ] GcMissionConditionEventRequiresRGB                 | 0x9C6FF0332EAD43B3| 0x36CE03A85A61CBFB| 0x28   | =
- [ ] GcMissionConditionHasEndpointForEvent              | 0x98657E8C7DFA59B6| 0x9C35F879928BF0CE| 0x28   | =
- [ ] GcMissionConditionHasFuel                          | 0xAFC26734D6BF2110| 0x2A8282CD4FA96596| 0x18   | =
- [ ] GcMissionConditionHasProduct                       | 0xD184553D0179DC39| 0x9537448E73030512| 0x10   | =
- [ ] GcMissionConditionHasTechnology                    | 0xB78074E3F1EFC33B| 0x7454AD5214251C68| 0x8    | =
- [ ] GcMissionConditionIsScanEventActive                | 0x9BFB3B6D5FFE320A| 0xDF80EC28C687305E| 0x28   | =
- [ ] GcMissionConditionIsScanEventOnCurrentPlanet       | 0x79C865AEDFE0C003| 0xEB5EF017837D2565| 0x28   | =
- [ ] GcMissionConditionIsTechnologyRepaired             | 0x6C83910E4F5375A3| 0x24D022A0BCD713A0| 0x8    | =
- [ ] GcMissionConditionLocation                         | 0x0DBD0CB8155C933E| 0x64A394B637C25752| 0x4    | =
- [ ] GcMissionConditionNearScanEvent                    | 0xE31955C81647FC37| 0x8F7E57B730A9C7F8| 0x28   | +1
- [ ] GcMissionConditionProductKnown                     | 0xB979E71DDCD32E2A| 0x7C5208D16FF2D5BF| 0x4    | =
- [ ] GcMissionConditionTechnologyKnown                  | 0x16AAE01577BF5445| 0x1E4A17D964305DC4| 0x4    | =
- [ ] GcMissionConditionWeaponMode                       | 0x3FA159601A988735| 0x798B3001AC5A7114| 0x4    | =
- [ ] GcMissionConsequenceRemoveCommunicatorMessage      | 0x33D4A6F29AFA50E4| 0xE2DF0C2D3E6E3BF8| 0x20   | =
- [ ] GcMissionConsequenceRemoveScanEvent                | 0xD40930210BB52C9F| 0x66D8F2741332E444| 0x20   | =
- [ ] GcMissionPageHint                                  | 0xBAADE82FFF5952D4| 0xBC45706D394C0853| 0x4    | =
- [ ] GcMissionSequenceAudioEvent                        | 0xD4CA478A342F9118| 0x4B1DBAB6A4BE391D| 0x84   | =
- [ ] GcMissionSequenceCollectProduct                    | 0xE740187C9278D774| 0x139E6194371FE10E| 0x140  | =
- [ ] GcMissionSequenceCommunicator                      | 0x8854EDC3BB21A40D| 0xD14F8D38E31CAB20| 0x258  | =
- [ ] GcMissionSequenceDetailMessage                     | 0x7E515B4C6452FF15| 0xA29EE4D703004484| 0xF8   | =
- [ ] GcMissionSequenceEndScanEvent                      | 0x59E934EAC79B537E| 0x0D15F5E0AAE5AA74| 0xA0   | =
- [ ] GcMissionSequenceGatherForRefuel                   | 0x913EE552C721D530| 0x9FA5A1E5E026A5B3| 0x108  | =
- [ ] GcMissionSequenceGatherForRepair                   | 0xDC758A93BA54A2C0| 0x535215E1DEB68BB2| 0x118  | =
- [ ] GcMissionSequenceGetToExpedition                   | 0x20982378EF686841| 0xB3C5F69D62F6CA73| 0x1A8  | =
- [ ] GcMissionSequenceRepairTech                        | 0x5F1FB2F7C63E5760| 0xF83A832D3507037F| 0x110  | =
- [ ] GcMissionSequenceReward                            | 0x2A7E5A2390BD677B| 0x7471FD77815538C2| 0x118  | =
- [ ] GcMissionSequenceShowMessage                       | 0xF97460BE06C91B02| 0xECE8B28E154961E9| 0x230  | =
- [ ] GcMissionSequenceStartScanEvent                    | 0x90CF75D7BA76F02A| 0x84E26BAA3B367507| 0xB0   | =
- [ ] GcMissionSequenceStartScanEventSpecific            | 0xCDB543AB27830175| 0x83CCE421927A9559| 0x100  | =
- [ ] GcMissionSequenceVehicleScan                       | 0x79972371778E4C36| 0x0D9BAAE731EB23B1| 0x120  | =
- [x] GcMissionSequenceWaitForConditions                 | 0x447961099A4C8366| 0x677779252EE27773| 0x120  | +1
- [ ] GcMissionSequenceWaitForPhoto                      | 0x812B41B01DFCC437| 0x2EB82866D685EFBF| 0x240  | =
- [ ] GcMissionSequenceWaitForRefuel                     | 0xCFC9CC53C7F79504| 0x25696B35BE341F6C| 0x108  | =
- [ ] GcMissionSequenceWaitForRepair                     | 0x71CA623B59319277| 0x079652C883CA60AE| 0x104  | =
- [ ] GcMissionSequenceWaitForStat                       | 0x2BEFBFF68BD985C8| 0x197E91849165F7F4| 0x128  | =
- [ ] GcMissionTable                                     | 0xA06E543CCD6340C5| 0x26335C55292A7766| 0x10   | =
- [ ] GcModBasePart                                      | 0xF1BD945926480534| 0x6A104C45E1F1638D| 0x6D0  | =
- [ ] GcMultitoolData                                    | 0x5A1C57036035083D| 0x2AF78E5732410B4F| 0x1C0  | =
- [ ] GcNPCPlacementInfo                                 | 0xDCDFAF5EBCC7DF34| 0xA12AC584067DF8E0| 0xC8   | =
- [ ] GcNPCSpawnTable                                    | 0xFC090610940F36B3| 0xEF1AB4FE11FCFA6D| 0x440  | =
- [ ] GcPhotoFlora                                       | 0x324E5B346B2F2882| 0x2D2DE27512E8C450| 0xC    | =
- [ ] GcPhotoPlant                                       | 0x820E799003AAABBF| 0xEFC8FCE1F6004590| 0x4    | =
- [ ] GcPlayerCommunicatorMessage                        | 0x0D18CE159D7434C5| 0xF839343C27983F1A| 0x50   | =
- [ ] GcPlayerCommunicatorMessageWeighted                | 0x279A012C85CE0BDB| 0x3246DB9846FF8B70| 0x58   | =
- [ ] GcPlayerExperienceSpawnTable                       | 0x900EB9C7527F9E30| 0xA1B202DE9A10A705| 0x30   | =
- [ ] GcPlayerTitle                                      | 0x38F1CA903056BF52| 0x864FCB26DF972FCF| 0xD8   | =
- [ ] GcPlayerTitleData                                  | 0xC78ECEA79E607B6E| 0xB6947F6F9E247CD4| 0x10   | =
- [ ] GcProceduralProductData                            | 0x54E33BADFEB9926F| 0xC449167C8DE081CD| 0x8D0  | =
- [ ] GcProceduralTechnologyData                         | 0xEF7C6107950E0E27| 0x6B8472FADE3C492C| 0x290  | =
- [ ] GcProceduralTechnologyStatLevel                    | 0xCF00C7D7A791C49D| 0xF41CD566C844982A| 0x14   | =
- [ ] gcproducttableEnum                                 | 0xEC311FBC38AA8BA5| 0xBD7214A930BFF3F2| 0x4    | =
- [ ] GcProjectileData                                   | 0x686C6E55EBEEB005| 0x98B648B5C054B7F7| 0x3B0  | =
- [ ] GcPulseEncounterInfo                               | 0xF0BA175C5DF06FB5| 0x657592AF71342449| 0x198  | +1
- [ ] GcPulseEncounterSpawnTrader                        | 0x3F837413E3220850| 0x061E014828AD14CD| 0x320  | =
- [ ] GcRealityIcon                                      | 0x53465DE5A63828B1| 0x28AB5E6C29FCA8E5| 0xA8   | =
- [ ] GcRefinerRecipe                                    | 0xA2F08B28C5066577| 0x309D52938C546138| 0x70   | =
- [ ] GcRepairTechData                                   | 0xFF031B966938227C| 0xD610CA25729E63C3| 0x1A0  | +1
- [ ] GcRewardActivateCorruptedDrone                     | 0xF032A4340F8381ED| 0xCA4D2B1DC7089D9D| 0x28   | =
- [ ] GcRewardAdvancePortalState                         | 0x6F026107F210237D| 0x54AAB4996FB2487B| 0x20   | =
- [ ] GcRewardCommunicatorMessage                        | 0x4FC3C8E43A0BD0CE| 0x382AC51563627203| 0x1D8  | =
- [ ] GcRewardCrashSiteFly                               | 0xC90DA1C6AAC78894| 0x28670AE3B159B8FC| 0x20   | =
- [ ] GcRewardIncrementInteractionIndex                  | 0x9F57A5594FF4F5F7| 0x317FB72CFB424340| 0x8    | =
- [ ] GcRewardMissionMessageSeeded                       | 0x867F7373ED1252F6| 0x56DEE85C9E579653| 0x18   | +1
- [ ] GcRewardOpenFreeFreighter                          | 0xB6076343E576F32D| 0x4DD6C74BA4B6AD5A| 0x48   | =
- [ ] GcRewardScanEvent                                  | 0xC4540B52B2725A62| 0xD6D2BF5DDCCD9F49| 0x28   | =
- [ ] GcRewardSecondaryInteractionOptions                | 0x281F553D93206D90| 0x448E93C725811D8E| 0x10   | =
- [ ] GcRewardSpecificSpecial                            | 0xA4AFBFF9DFE44876| 0xCF9FC45A7B70BB85| 0x38   | =
- [ ] GcRewardSpecificTech                               | 0xFEB1FC5E038A21E6| 0xDABE4D9A95799081| 0x18   | =
- [ ] GcRewardSpecificTechFromList                       | 0x7C282CE33A844ED7| 0xF33640B1865E5E4B| 0x18   | =
- [ ] GcRewardTableCategory                              | 0xF42FD2358DCAA885| 0xCF538100E4D1C218| 0x48   | =
- [ ] GcRewardTableEntry                                 | 0xD6D51C085D901623| 0x29C1A8399A70F9A7| 0xE8   | =
- [ ] GcRewardTableItem                                  | 0xD61AC3F6F7059033| 0x743B54DBF617C58D| 0x98   | =
- [ ] GcRewardTableItemList                              | 0xD424AC8983D873D8| 0xF97DB1C704357E47| 0x18   | =
- [ ] GcScanEventData                                    | 0xA53093C86BB6F82E| 0x7BBBCE7D7BC0F1F4| 0x5E0  | =
- [ ] GcScanEventSave                                    | 0x0E527F6FF8F5898E| 0x434C17159AF37265| 0x80   | =
- [ ] GcScanEventTable                                   | 0x2AACE57A0B6D1452| 0x0D550A58E83EA253| 0x10   | =
- [ ] GcScannableComponentData                           | 0x8B670E1642F40DC2| 0x74BA808E86F0EC01| 0x80   | =
- [ ] GcScannerIcon                                      | 0x818EF9AAA4C46A66| 0x85905E340468CC13| 0x10C  | =
- [ ] GcScannerIconTypes                                 | 0xD871C82A57BD4AE7| 0x8A4027FC041677F0| 0x4    | =
- [ ] GcSeasonalStage                                    | 0x2527AC6B9E39D4F8| 0xF1949393FDAF963A| 0xD8   | =
- [ ] GcSeasonStateData                                  | 0x72A849FE6FF40A2E| 0x4BC716CF849F5A74| 0x50   | =
- [ ] GcShipDialogue                                     | 0x24D8AF9733730235| 0x770E3F1934F2D769| 0x268  | =
- [ ] GcShipWeaponData                                   | 0xB164A93BB44FF0B4| 0x73BA1311CF8E1962| 0x40   | =
- [ ] GcStats                                            | 0xE815AF4E17216578| 0x9C20970E839B65D9| 0x10   | =
- [ ] GcStatsBonus                                       | 0xEE5DBAAC1719BE35| 0xBAC710ADD80D9C59| 0xC    | =
- [ ] GcStatsEntry                                       | 0x8747A1C16EC24E65| 0x4309D65C13EEC689| 0x40   | =
- [ ] GcStatsGroup                                       | 0xEDB19955BFB2F65E| 0xEB5E59FB895AFF06| 0xA8   | =
- [ ] GcStatsTypes                                       | 0xBE9642E402E2836E| 0x003E6292A999E2A6| 0x4    | =
- [ ] GcTargetMissionSurveyOptions                       | 0xC5BCD08BAB773978| 0x4E7A7CEB00A9346B| 0x198  | -1
- [ ] gctechnologytableEnum                              | 0x6D804AABF1756F2B| 0xA32EA4A9B1B5B242| 0x4    | =
- [ ] GcTechnologyTypes                                  | 0xFEDC3500FE067BD6| 0x324956CF456BD3E1| 0x10   | =
- [ ] GcTerrainEditing                                   | 0xE0D6A6545E3C505E| 0x4686D0FAC0A1B9EC| 0x98   | =
- [ ] GcTradeSettings                                    | 0xCFFA3BDDF2A0BDDA| 0x4B63CD1B58DAF5A4| 0xDA8  | =
- [x] GcUnlockableSeasonRewards                          | 0xE5F4D8D17FB06A9F| 0x3EB0EF943FFD976E| 0x10   | =
- [ ] GcVehicleScanTableEntry                            | 0x08F71353B2FED771| 0xBAC942D350F478B1| 0xC8   | =

# Structs with a size change:
- [ ] GcAtlasRecvActiveFeaturedBasesQuery                | old: 0x18   | new: 0x20   | GUID: 0x42D07F5EA314B2B0| Fields: =
- [ ] GcAtlasRecvBaseList                                | old: 0x30   | new: 0x38   | GUID: 0x29046730D3CB288A| Fields: =
- [ ] GcAtlasRecvBaseQueryList                           | old: 0x20   | new: 0x28   | GUID: 0xB51027B0F5F84DDF| Fields: =
- [ ] GcAtlasRecvBasic                                   | old: 0x10   | new: 0x18   | GUID: 0x74F43D9D795E8787| Fields: +2
- [ ] GcAtlasRecvDiscoveryExact                          | old: 0x300  | new: 0x310  | GUID: 0x5C7C6013F8BCE2AB| Fields: +3
- [ ] GcAtlasRecvFeaturedBasesQueryList                  | old: 0x20   | new: 0x28   | GUID: 0xC51628B104A72A46| Fields: =
- [ ] GcAtlasRecvMonumentList                            | old: 0x1A0  | new: 0x1B0  | GUID: 0xE7251104BD32F87E| Fields: =
- [ ] GcAtlasRecvTotalContribution                       | old: 0x18   | new: 0x20   | GUID: 0x88D927C5D3ACE8D9| Fields: =
- [ ] GcAtlasRecvVoxel                                   | old: 0x50   | new: 0x58   | GUID: 0xAB31E38EB110A2EB| Fields: =
- [ ] GcAtlasSendChangeFeaturedBasesEnv                  | old: 0x18   | new: 0x20   | GUID: 0xA4BF39A04658FAB1| Fields: =
- [ ] GcAtlasSendMarkFeaturedBase                        | old: 0x48   | new: 0x50   | GUID: 0xC27C66754E23328B| Fields: =
- [ ] GcAtlasSendMarkFeaturedBaseWithImage               | old: 0x58   | new: 0x60   | GUID: 0x43B957129D1B95F6| Fields: =
- [ ] GcAtlasSendQueryActiveFeaturedBases                | old: 0x8    | new: 0x10   | GUID: 0x984230EA43944609| Fields: =
- [ ] GcAtlasSendQueryBaseImages                         | old: 0x18   | new: 0x20   | GUID: 0xFEC2B020D496EB35| Fields: =
- [ ] GcAtlasSendRemoveFeaturedBases                     | old: 0x18   | new: 0x20   | GUID: 0x067E627F1BDA6FC4| Fields: =
- [ ] GcAtlasSendReport                                  | old: 0xA8   | new: 0xB0   | GUID: 0x2869871E836C6B06| Fields: +6
- [ ] GcAtlasSendRequestBlob                             | old: 0x70   | new: 0x78   | GUID: 0x534F1EAF42644C4A| Fields: +4
- [ ] GcAtlasSendRequestDiscoveryAllOnPlanet             | old: 0x20   | new: 0x28   | GUID: 0x6DFEB50FEF29FC7C| Fields: +2
- [ ] GcAtlasSendRequestDiscoveryCategory                | old: 0x28   | new: 0x30   | GUID: 0x9102AD934E34EED9| Fields: +3
- [ ] GcAtlasSendRequestDiscoveryExact                   | old: 0x50   | new: 0x58   | GUID: 0x79B8FBAA3C146C56| Fields: +2
- [ ] GcAtlasSendRequestMonument                         | old: 0x20   | new: 0x28   | GUID: 0xD04C6FE608349B49| Fields: +2
- [ ] GcAtlasSendRequestTotalContribution                | old: 0x8    | new: 0x10   | GUID: 0x3D02503C2F082AFF| Fields: =
- [ ] GcAtlasSendRequestVoxel                            | old: 0x20   | new: 0x28   | GUID: 0x07B0C9934C1CF50C| Fields: +2
- [ ] GcAtlasSendSubmitBaseWithImage                     | old: 0x320  | new: 0x330  | GUID: 0x766BDAAD5AF729EC| Fields: =
- [ ] GcAtlasSendSubmitDiscoveryExact                    | old: 0xD0   | new: 0xD8   | GUID: 0x2C9685FB3FF52145| Fields: +3
- [x] GcCostTableEntry                                   | old: 0x68   | new: 0x88   | GUID: 0xC1902D5884D707C2| Fields: +1
- [x] GcDefaultSaveData                                  | old: 0x2C2E0| new: 0x2C340| GUID: 0x919E6F4D01504722| Fields: =
- [x] GcMissionConditionAllMilestonesComplete            | old: 0x4    | new: 0x8    | GUID: 0x124458932833A2E6| Fields: +1
- [x] GcMissionSequenceSetCurrentMission                 | old: 0x90   | new: 0x98   | GUID: 0xA3B5E6806301CC0C| Fields: +1
- [ ] GcPlayerStateData                                  | old: 0x2C230| new: 0x2C290| GUID: 0x9E5E9CF44AA13A15| Fields: =
- [x] GcRewardOSDMessage                                 | old: 0xC0   | new: 0xD0   | GUID: 0x57E12825C5D9CB1A| Fields: +1
- [x] GcRewardTable                                      | old: 0x110  | new: 0x130  | GUID: 0x29F1A6CFFB862932| Fields: +2
- [x] GcRewardUnlockSeasonReward                         | old: 0x18   | new: 0x40   | GUID: 0xE6212DF525ECA350| Fields: +1
- [x] GcSeasonalGameModeData                             | old: 0x450  | new: 0x498  | GUID: 0x35B0C9DA67415CD3| Fields: +4
- [x] GcSeasonalMilestone                                | old: 0x758  | new: 0x8F8  | GUID: 0x2EEEDEBB6597DC9E| Fields: +2
- [x] GcUnlockableSeasonReward                           | old: 0x30   | new: 0x38   | GUID: 0x22227A02DF0A88DD| Fields: +1
- [ ] TkAnim2dBlendNodeData                              | old: 0x50   | new: 0x58   | GUID: 0x5CE2B3CBE6B79B10| Fields: =
- [ ] TkAnimBlendNode                                    | old: 0xF8   | new: 0x108  | GUID: 0x7886A38513257F16| Fields: =
- [ ] TkAnimBlendTree                                    | old: 0x60   | new: 0x70   | GUID: 0xCEBBAB8E576F1B96| Fields: =
- [ ] TkAnimVectorBlendNodeData                          | old: 0xB0   | new: 0xB8   | GUID: 0x2860E63449C8ACD8| Fields: =

# Structs with diff # of Fields | GUID | NameHash | Size | Fields:
- [ ] GcAtlasDiscovery                                   | 0x28F613BC51BF1666| 0x0886C03C3F3987F4| 0x2F0  | +7
- [ ] GcAtlasSendRequestBases                            | 0xF8653D82867B12BE| 0x8224EED427CDE62A| 0x60   | -6
- [ ] GcFontTable                                        | 0xB9913A609DA490D3| 0xD77829A90743F12E| 0x420  | -7
- [ ] GcMessageCrime                                     | 0x1CCB7BDC1ECBB02A| 0x0C64AF7F76101CD0| 0x30   | +2
- [ ] GcMessageFiendCrime                                | 0x5873ED86AF6E466E| 0x037D134945C6DC0E| 0x20   | +1
- [ ] GcMessageNPCBehaviourEvent                         | 0x4C926B203874A03B| 0x40F7E71C83A33DA0| 0x50   | +1
- [ ] GcMessagePetBehaviourEvent                         | 0x306E8557E0A11798| 0x9465A52B8A2F9FD9| 0x70   | +1
- [ ] GcResourceElement                                  | 0x03558F692031D58C| 0x91CAC70AC2792E2A| 0x2A8  | +1
- [ ] GcSmokeBotPlanetReport                             | 0xA45C8D02FAACDDE6| 0x778378F86BB2392C| 0xB0   | +2
- [ ] GcSmokeBotReport                                   | 0x3BC2543792E9B519| 0x16AC643981D10CC9| 0x18   | +2
- [ ] GcSmokeBotStats                                    | 0x2608B5B9ED8DC24B| 0xBF03A94511E0F7B0| 0xA0   | +16
- [ ] GcSmokeBotSystemReport                             | 0x45A0E050DAB66262| 0xFB50309B36475BDE| 0x160  | +4
- [ ] GcTestMetadata                                     | 0xED9D01EDEE998FDB| 0xCE965FAFD6BBF99E| 0x6E0  | +1
- [ ] TkAnimNodeData                                     | 0x14C032849E45EE8D| 0x6E19250A34E2CE86| 0x50   | -1
- [ ] TkIndexStream                                      | 0x0C3F2CB3BC1F3270| 0x4E6048B326CC903A| 0x10   | +1
- [ ] TkMaterialResource                                 | 0xFD4EC7E71CA16A38| 0x75EC92F2E9E3196F| 0x84   | +1
- [ ] TkModelResource                                    | 0x83447CE313934E8F| 0xBE5E5CB33D0EB022| 0x84   | +1
- [ ] TkTextureResource                                  | 0x8F308DA13045525E| 0x2316F23520D820A9| 0x84   | +1
- [ ] TkVertexStream                                     | 0xF7FE8408BD5A0B28| 0x63E16E6AF89FE439| 0x10   | +1

**Comment by HolterPhylo** [comment]
You can close this one, made Issue #330.  I should be easier to work with
