### ISSUE TITLE
Add the option to not add the "File created using MBINCompiler version (X.XX.X)" line

### ISSUE THREAD

**Issue by gistya** [monkeyman192/MBINCompiler#334]
**Is your feature request related to a problem? Please describe.**

I use git to track changes to the decompiled EXML files. Every time I do a conversion from MBIN to EXML using a new version of MBINCompiler, now all the files have diffs because the version number changes `<--File created using MBINCompiler version (3.42.0)-->` So then I have to do a global search-and-replace to remove this line.

**Describe the solution you'd like**

Ideally MBINCompiler would simply not add this version line, since it's totally not needed. However if we must have it added, then please allow the option not to add this line when decompiling MBINs. Thanks!

**Describe alternatives you've considered**

The workaround I've been using is to simply 

**Additional context**

**Comment by HolterPhylo** [comment]
Added this option to '--hideVersionInfo' while I was at it!
