### ISSUE TITLE
[UPDATE] 3.42 -> 3.50 changes

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#338]
## New structs:

- [x] GcByteBeatLibraryData	0xA11EB28A67E6FAA5	6
- [x] GcByteBeatPlayerComponentData	0x54361830E547506C	0
- [x] GcByteBeatSong	0x7C7F71709B8330B7	5
- [x] GcCharacterMove	0x6A39E7A9B4387E46	3
- [x] GcCharacterRotate	0xF350B567ECC52C73	4
- [x] GcDebugPlanetPos	0xC1DB426601356D64	2
- [x] GcMissionConditionReadyToSpawnPirates	0xD0C07E8FE92051A3	0
- [x] GcMissionSequenceClearInventoryHistory	0x929221B9E4FA759C	0
- [x] GcObjectSpawnDataVariant	0xACF1A1C9560AFE02	11
- [x] GcPlayerControlComponentData	0x942496B3E9D157AA	4
- [x] GcPlayerControlInput	0x5B0B15C1922C7378	4
- [x] GcPlayerControlInputAxis	0xBF40484C12B59807	5
- [x] GcPlayerControlModeEntry	0x6A2E0608F3F962B9	2
- [x] GcPlayerControlState	0x6D4181A7ABB245CB	5
- [x] GcRewardFreighterBaseReset	0x6EF2C418DE2885AA	0

## Structs with internal changes:

- [x] GcAlienPuzzleCategory	0x90F0DF33F62406AA
- [x] GcAlienPuzzleEntry	0x62AB8216A3AA8DC1
- [x] GcAlienPuzzleOption	0xE1BD40C08D6E1A96
- [x] GcAlienPuzzleTable	0x203A0FD93F65B4DD
- [x] GcAudioAreaTriggerComponentData	0x4499A2584EA12EF0
- [x] GcAudioWwiseEvents	0x9658500DFBA6BF5
- [x] GcBaseBuildingEntry	0x4121EFDA03646E2F
- [x] GcBaseBuildingTable	0xE56A543E9A120616
- [x] GcConsumableItem	0x78F75C0DA581064
- [x] GcConsumableItemTable	0x637A498A427DABAE
- [x] GcCreatureCrystalMovementData	0x2E00158B7025109C
- [x] GcCreatureCrystalMovementDataParams	0xD711C37FF39815C5
- [x] GcCreatureDataTable	0xFDECB1CD390DFEE4
- [x] GcDefaulMissionProduct	0x52A68D09CA2E4C5A
- [x] GcDefaultMissionItemsTable	0xE4388016DE2A1168
- [x] GcEnvironmentSpawnData	0xBD99A681FCD760B7
- [x] GcExpeditionRewardTable	0x7DEE23CDF5B710CD
- [x] GcExperienceDebugTriggerAction	0x36A55042864ACBAE
- [x] GcExperienceDebugTriggerActionTypes	0xA9A7071266847699
- [x] GcExperienceDebugTriggerInput	0x244ED03FC323784A
- [x] GcExperienceSpawnTable	0x26385ECD4F28FCFE
- [ ] GcExplosionData	0xB3C9E5FC5A165F5A
- [x] GcExplosionDataTable	0x2FDEA9F1FAEE36AA
- [x] GcExternalObjectList	0xD7CB6A6690A51D88
- [x] GcGalaxyAudioSetupData	0x2E538940E929A27C
- [ ] GcGalaxyGlobals	0x62118C7FEAD48BF5
- [ ] GcGenericMissionSequence	0x5C34922E0904BF06
- [ ] GcGenericRewardTableEntry	0x675486DA58825074
- [ ] GcGrabPlayerComponentData	0xF1407B06D510C476
- [x] GcHUDStartup	0x7807B3C10044AC27
- [x] GcHUDStartupTable	0xCEADD5CEA12946E4
- [x] GcHotActionsSaveData	0xCAFFDA6C8A553477
- [x] GcInteractionComponentData	0xEFB82667DA0C592E
- [x] GcInteractionType	0x9EA7089F867CBF54
- [x] GcInventorySlotActionData	0xB08A070C1628BEC5
- [ ] GcLaserBeamData	0xC41363206CAC4D4D
- [x] GcMissionCommunityData	0x2077A7CECC1F140F
- [x] GcMissionConditionHasProduct	0x99ABF41B3F6FC2DE
- [x] GcMissionConditionInteractionIndexChanged	0xE2F9272A3D969B73
- [x] GcMissionConditionProductKnown	0xA0089ED6897BC339
- [x] GcMissionSchedulesTable	0xAC7D4BC44729D2D2
- [x] GcMissionSequenceAudioEvent	0x811688D50133C5B2
- [x] GcMissionSequenceCollectProduct	0x2C5712CBB44F6144
- [x] GcMissionSequenceDetailMessage	0x241F4D1A3F907DC3
- [x] GcMissionSequenceShowMessage	0x4E9EC4AF15672125
- [x] GcMissionTable	0x9B8C9E9BA872E554
- [x] GcModBasePart	0xEC3E2107493EB063
- [x] GcNPCPlacementInfo	0xB52CEC5AC5E1EB4D
- [x] GcNPCSpawnTable	0xDF4971E67FEA328B
- [x] GcObjectSpawnDataArray	0x37D0C7E8CADBB122
- [x] GcPlanetData	0xF9FFC4EEEC16E569
- [x] GcPlayerTitle	0x9501197E0E183F4F
- [x] GcPlayerTitleData	0x7A0333030A9F2B30
- [ ] GcProjectileData	0x1C00DB3292E26840
- [x] GcProjectileDataTable	0x1264143C4CDE3F7A
- [x] GcPulseEncounterInfo	0xA080825EBCF44AD6
- [x] GcQuickMenuActionSaveData	0x77AC48B35CFBA776
- [x] GcQuickMenuActions	0xE15B6DFE7BEFC834
- [x] GcRewardFrigateFlyby	0x8F1EB0AA7764BAC4
- [x] GcRewardIncrementInteractionIndex	0x91C07623EE030B3F
- [x] GcRewardOSDMessage	0xF1F3623962C754F3
- [x] GcRewardSecondaryInteractionOptions	0x5EBBDCD64A01C71B
- [x] GcRewardTable	0x548B9134E984EAB6
- [x] GcRewardTableCategory	0x97D7978F3D97450A
- [x] GcRewardTableEntry	0x785DE0056C134F7
- [x] GcRewardTableItemList	0xC23192B97A18C613
- [ ] GcScanEventData	0xC7D218267C466E5E
- [x] GcScanEventTable	0x1B55F6542D9F7DD
- [x] GcSeasonalGameModeData	0xCA81471A19303785
- [x] GcSeasonalStage	0x7DF451E825D1B9EF
- [ ] GcWeatherEffect	0xB1C20538A90A12BD
- [x] GcWeatherEffectTable	0x348CEA3F0964B2A1
- [x] TkAnimationComponentData	0x9B91CA8A24A906BE
- [x] TkAnimationData	0x38957E72BFAB064F
- [x] TkAnimationDataTable	0x64AA97FB40881F68
- [x] TkEngineSettingTypes	0x7BABB618CE487C65
- [x] TkMaterialFlags	0xA4081297947B2207
- [x] gcproducttableEnum	0x86E2AC8417174443

## Structs with a file size change:

- [ ] GcAudioGlobals	old: 0x148	new: 0x160	GUID: 0x3FC10EFF4AC81A4F	fields: 62 (+6)	
- [x] GcBaseDefenceComponentData	old: 0x18	new: 0x20	GUID: 0xD80E4BC0FC4AC75E	fields: 5 (+2)	
- [x] GcByteBeatDrum	old: 0x58	new: 0x74	GUID: 0x39E7DA2C8408A28C	fields: 14 (+7)	
- [x] GcByteBeatTemplates	old: 0xA8	new: 0xB8	GUID: 0xB473B0B56BC95C77	fields: 10 (+1)	
- [ ] GcCameraGlobals	old: 0x3650	new: 0x3660	GUID: 0x7EEB800C70ED478F	fields: 316 (+2)	
- [x] GcCreatureData	old: 0x58	new: 0x68	GUID: 0x4A290062CBDE61A1	fields: 17 (+3)	
- [x] GcCreatureFiendAttackData	old: 0xC0	new: 0xE8	GUID: 0x254F5939772BE7DC	fields: 20 (+6)	
- [ ] GcDebugOptions	old: 0x2558	new: 0x2570	GUID: 0x93DEEA949C98F6D6	fields: 347 (+9)	
- [ ] GcDebugScene	old: 0x1AD0	new: 0x1C10	GUID: 0x8B8FC105C70B3860	fields: 61 (+10)	
- [x] GcDefaultSaveData	old: 0x2C340	new: 0x2D7E0	GUID: 0x4FE647D093F0BCAA	fields: 2	
- [x] GcEncounterComponentData	old: 0x4	new: 0x18	GUID: 0xF6476E87C35043E4	fields: 2 (+1)	
- [ ] GcGameplayGlobals	old: 0x1CE0	new: 0x1D20	GUID: 0x35FE7EAD026B8549	fields: 523 (+8)	
- [ ] GcGraphicsGlobals	old: 0x0A20	new: 0x0A60	GUID: 0xD22A700AE9752489	fields: 315 (+11)	
- [x] GcMissionSequencePirates	old: 0xC0	new: 0xC8	GUID: 0xFD60E7AD8D890729	fields: 8 (+1)	
- [x] GcObjectSpawnData	old: 0x3B0	new: 0x3C0	GUID: 0xF55A7A26587852DE	fields: 39 (-12)	
- [x] GcPerformanceGuard	old: 0x8	new: 0x20	GUID: 0x25B610E77FEBCEA1	fields: 2	
- [x] GcPetData	old: 0x1F0	new: 0x1F8	GUID: 0xB63A18B6EB667948	fields: 25 (+1)	
- [x] GcPlayerCharacterComponentData	old: 0x10	new: 0x30	GUID: 0xE5F8BE3FDC17F3C2	fields: 3 (+2)	
- [x] GcPlayerStateData	old: 0x2C290	new: 0x2D730	GUID: 0xEAF41C1A72F588FC	fields: 197 (+1)	
- [x] GcRealityManagerData	old: 0xD6A0	new: 0xD6B0	GUID: 0x6C64322C18E67BAA	fields: 67	
- [x] GcSeasonalMilestone	old: 0x8F8	new: 0x900	GUID: 0x408D10D95FF6DF36	fields: 22 (+1)	
- [x] GcSimpleInteractionComponentData	old: 0x1C0	new: 0x1C8	GUID: 0x5142359D32BAE2D2	fields: 36 (+1)	
- [ ] GcSpaceshipGlobals	old: 0x1040	new: 0x1070	GUID: 0x767E1C0E76B0948E	fields: 592 (+9)	
- [x] GcTurretComponentData	old: 0xB0	new: 0xA8	GUID: 0xBB6DFF049368D63D	fields: 28 (-2)	
- [x] GcVehicleData	old: 0x1030	new: 0x1230	GUID: 0x1B1C85741985A052	fields: 142 (+1)	
- [ ] GcVehicleGlobals	old: 0x490	new: 0x4A0	GUID: 0x838D0D49170F902B	fields: 222 (+1)	
- [x] TkAnimPoseComponentData	old: 0xD8	new: 0xE0	GUID: 0xB3A49725481F71E5	fields: 8 (+1)	
- [x] TkEngineSettingsMapping	old: 0x7C	new: 0x90	GUID: 0xB3029E8E98933199	fields: 7 (+1)	
- [x] TkGraphicsDetailPreset	old: 0x34	new: 0x38	GUID: 0xDB5598A7AE4E6F4E	fields: 14 (+1)	
- [x] TkGraphicsSettings	old: 0x1A0	new: 0x1A8	GUID: 0x2F7F47100F00B4FE	fields: 28	
- [ ] TkMaterialMetaData	old: 0x4C0	new: 0x4D0	GUID: 0xA0C736D9CAD33B0D	fields: 107 (+3)	

## Structs with a field number changes:

- [x] GcBaseDefenceTrigger	old: 0x28	new: 0x28	GUID: 0xA3DD15E1F86778ED	fields: 5 (+1)	
- [x] GcCreatureComponentData	old: 0x70	new: 0x70	GUID: 0xDFE71557854AA7E9	fields: 11 (+1)	
- [ ] GcCreatureGlobals	old: 0xn/a	new: 0xn/a	GUID: 0x94964AB7DF4884AD	fields: 566 (-2)	
- [x] GcCreatureSpawnData	old: 0x870	new: 0x870	GUID: 0x581465750D0D676F	fields: 24 (+1)	
- [x] GcMissionConditionWaitForPirates	old: 0xC	new: 0xC	GUID: 0x818DB4A533D98EA4	fields: 5 (+1)	
- [x] GcNPCDebugSpawnData	old: 0x380	new: 0x380	GUID: 0x2BFC0C7970E3EF42	fields: 16 (+1)	
- [x] GcPhotoModeSettings	old: 0x60	new: 0x60	GUID: 0x4C02A41D41E19035	fields: 17 (+1)	
- [ ] GcSkyGlobals	old: 0xn/a	new: 0xn/a	GUID: 0x344278B166590F2C	fields: 154 (+5)	
- [ ] GcUIGlobals	old: 0x44F0	new: 0x44F0	GUID: 0x2B6FEF1E4D967B6F	fields: 1138 (+3)	
- [x] TkMaterialData	old: 0x2E0	new: 0x2E0	GUID: 0xB3E85714C2E13A19	fields: 13 (+1)

**Comment by Babscoole** [comment]
I don't see then in the list above, but I also got GUID mismatches with scaneventtablevehicle and scaneventtabletutorial using 3.50 pre pre 1.  Don't know if it's that same issue where the guid in the exe differs from the file.

**Comment by monkeyman192** [comment]
> 
> 
> I don't see then in the list above, but I also got GUID mismatches with scaneventtablevehicle and scaneventtabletutorial using 3.50 pre pre 1. Don't know if it's that same issue where the guid in the exe differs from the file.

"GcScanEventTable 0x1B55F6542D9F7DD" ?

**Comment by Babscoole** [comment]
OK, didn't know that entry covered those as well, thanks.  :)

**Comment by HolterPhylo** [comment]
Do you think this can be closed?

**Comment by monkeyman192** [comment]
> 
> 
> Do you think this can be closed?

Yes, I think so :)
