### ISSUE TITLE
Multithreading issue when using the option -Q or --nolog

### ISSUE THREAD

**Issue by Galenmacil** [monkeyman192/MBINCompiler#368]
Hi,

This exception is thrown when launching several MBINCompiler.exe in parallel with the option -Q or --nolog present in the command line:

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at MBINCompiler.CommandLine.ShowException(Exception e, Boolean wait)
   at MBINCompiler.Program.Main(String[] args)

It works fine when the option is not present but, in that case, it generates a whole bunch of differently named .LOG file which is very annoying...

**Comment by chrispurnell** [comment]
Did #364 fix this?

**Comment by Galenmacil** [comment]
Seems like #364 fixed it...
