### ISSUE TITLE
Mbin files not decompiling for last NMS update

### ISSUE THREAD

**Issue by BradfordCB** [monkeyman192/MBINCompiler#379]
_Fill in the details for each relevant section._
_When you're done, then delete any instructions, example text and irrelevant sections._  
_Please select the project on the sidebar where you encountered the problem._

**Things to check before you raise an issue**
- Make sure that you have looked at the log file and determined that the issue is in fact an issue with MBINCompiler, and not an issue with the exml file being modified incorrect etc.
- Check to see that an issue has not already been raised of the same manner.
- If there has been a recent update, check to see for any issues marked `[UPDATE]` to see if the struct you are having issues with is in fact supported yet or not. If not ticked off, please do not post an issue.
**IMPORTANT**: If there was a recent release and there is no issue with the update info, please do not raise an issue about single broken files. It may take some time for this issue to be created, so please be patient. Opening multiple issues will not help and they will just be closed.

**Describe the bug**
Include a summary of the error message if there is one.

**Expected behavior**

**Steps To Reproduce**

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: [eg 1.0.0.0]
 - NMS Game Version or Steam Build Number: [eg 1.0.0.0, or 4154325] (To find the build number, right click on the game in steam, select `Properties`, then click on the `LOCAL FILES` tab and the buildID is at the bottom).
 - MBIN File: [eg GCPLAYERGLOBALS.GLOBAL.MBIN]
 - MBIN File Version: [eg 1.0.0.0]

**Additional Information**
Add any other information here that you think might be helpful.

_Attachments:_
_Always include the entire log file._
_Do not attach MBIN files unless requested._
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/7096009/MBINCompiler.log)

**Comment by monkeyman192** [comment]
Please see point 3 in the "Things to check before you raise an issue" of this issue itself ;)
