### ISSUE TITLE
Add Option to Specify File Type 

### ISSUE THREAD

**Issue by Fuzzy-Logik** [monkeyman192/MBINCompiler#38]
Re: Issue #37 Unexpected Behaviour When Processing Directories with both MBIN and EXML

The default behaviour should be to detect if the input directory contains mixed types and prompt
the user to select which type to process: MBIN or EXML.

There should be a command line option to be able to specify which type of file to process and avoid the warning: `--inputType (MBIN | EXML)`

If the type is MBIN then files will be filtered by `"*.MBIN;*.MBIN.PC"`.
If the type is EXML then files will be filtered by `"*.EXML"`.

The `--inputType` filter should be applied before the `--include` and `--exclude` filters.

Although the proper filtering could be accomplished with the `--include` or `--exclude` options, 
having a specific option to select the type is simpler to use and allows the other options to have
generic patterns that could work with either type instead of needing separate patterns for each.

Depends on issue #35.

**Comment by monkeyman192** [comment]
I think the option to prompt the user if they want to do just exml or just mbin (de)serialisation is a great one. Shouldn't be that hard to implement I don't think...
Also being able to call it from command line would be good too as it could allow better connectivity with other programs such as the modding station
