### ISSUE TITLE
Error when accessing GCSettlementGlobals.MBIN

### ISSUE THREAD

**Issue by floraRaccoon** [monkeyman192/MBINCompiler#386]
GUID for GCSettlementGlobals.MBIN seems to be improperly set

Stack trace:
----- [INFO] GCSETTLEMENTGLOBALS.MBIN
    [WARNING] MBINCompiler = [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler. OR check your script!
    [WARN]    MBINCompiler =   [INFO]: GCSETTLEMENTGLOBALS.MBIN
    [WARN]    MBINCompiler =   [INFO]: MBIN     version:        0.0.0.0 guid:   89D86EF3DCA27CB1        template:
        cGcSettlementGlobals
    [WARN]    MBINCompiler =   [EXPECTED INFO]: GUID: FB37C00D542308DE
    [WARN]    MBINCompiler = [ERROR]: [MbinException]: Failed to read GcSettlementGlobals from MBIN.
    [WARN]    MBINCompiler =   [ArgumentOutOfRangeException]: Non-negative number required. (Parameter 'value')
    [WARN]    MBINCompiler =   [INFO]: C:\Users\\[username]\Desktop\AMUMSS\MODBUILDER\_TEMP\EXTRACTED\GCSETTLEMENTGLOBALS.MBIN    [WARN]    MBINCompiler =   [INFO]: MBIN     version:        0.0.0.0 guid:   89D86EF3DCA27CB1        template:
        cGcSettlementGlobals
    [WARN]    MBINCompiler =      at System.IO.FileStream.set_Position(Int64 value)
    [WARN]    MBINCompiler =      at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
    [WARN]    MBINCompiler = [INFO]: 1 FILES FAILED.
    [WARN]    MBINCompiler =   [ERROR]: Failed to read GcSettlementGlobals from MBIN.
    [WARN]    MBINCompiler =   [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
     [ERROR]  MBINCompiler = [MbinException]: Failed to read GcSettlementGlobals from MBIN OR check your script, if it is a NMS file!
     [ERR]    MBINCompiler =   [ArgumentOutOfRangeException]: Non-negative number required. (Parameter 'value')
     [ERR]    MBINCompiler =   [INFO]: C:\Users\\[username]\Desktop\AMUMSS\MODBUILDER\_TEMP\EXTRACTED\GCSETTLEMENTGLOBALS.MBIN     [ERR]    MBINCompiler =   [INFO]: MBIN     version:        0.0.0.0 guid:   89D86EF3DCA27CB1        template:
        cGcSettlementGlobals
     [ERR]    MBINCompiler =      at System.IO.FileStream.set_Position(Int64 value)
     [ERR]    MBINCompiler =      at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
     [ERR]    MBINCompiler = [INFO]: 1 WARNINGS.
     [ERR]    MBINCompiler =   [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.

**Comment by floraRaccoon** [comment]
Note this IS in conjunction with AMUMSS but appears to be a compiler error

**Comment by Babscoole** [comment]
See the comment at the bottom of https://github.com/monkeyman192/MBINCompiler/issues/378.  Those few files are currently setup for the build that is currently in experimental, that will become 3.63.  So, you'll see these message for those files with 3.62.

**Comment by floraRaccoon** [comment]
Thanks for that info, thought I'd seen that this was already in production but I must have misunderstood
