### ISSUE TITLE
.net5

### ISSUE THREAD

**Issue by DarkAnimist** [monkeyman192/MBINCompiler#388]
lastest version of libMbin.dll always tells me i need .net 5 which i do have and will not work

**Comment by DarkAnimist** [comment]
this is what i am getting
![WIN_20210905_19_23_15_Pro](https://user-images.githubusercontent.com/90161141/132145577-4b21ce5b-0b38-4b1f-96bb-a641264ab03d.jpg)

**Comment by monkeyman192** [comment]
Yeah, I need to add more documentation on this issue/ I'll be doing this tonight...
