### ISSUE TITLE
Improve Error Messages and Reporting

### ISSUE THREAD

**Issue by Fuzzy-Logik** [monkeyman192/MBINCompiler#39]
The codebase needs to be reviewed and all error message should have helpful, user-friendly error messages. Currently errors are reported with stack traces which are hard to read and usually unnecessary.

Technical details should be logged to a file named `MBINCompiler.log`. Having a log file also makes it easier to file consistent bug reports with full details by requesting the file be attached.

The error log should be generated in the same directory as MBINCompiler.exe and should overwrite any existing log.

A command line option could be provided to specify a custom log path.

**Comment by GaticusHax** [comment]
Error logging implemented.
Defined proper exceptions for MBINCompiler and libMBIN errors.
End-user error messages still need work.
