### ISSUE TITLE
Warnings while decompiling GCUIGLOBALS.GLOBAL.MBIN from NMS Build ID 7343970

### ISSUE THREAD

**Issue by clampi** [monkeyman192/MBINCompiler#407]
**Descrption**
As per title, here is the log
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/7160127/MBINCompiler.log)

**Expected behavior**
MBINCompiler should be able to de-compile said file from (latest as of defect opening date) NMS, without issuing any warnings.

**Steps To Reproduce**
1. Try to de-compile by running `MBINCompiler GCUIGLOBALS.GLOBAL.MBIN`
2. Observe the messages from console, check the generated log

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 3.64.0.1
 - NMS Game Version or Steam Build Number: 7343970
 - MBIN File: GCUIGLOBALS.GLOBAL.MBIN
 - MBIN File Version: don't know,

**Additional Information**
While the warnings are not errors. it might be an indication that the result of the decompile isn't accurate, thus I am not sure whether or not decompile->modify xml->recompile action result can be trusted.

**Comment by HolterPhylo** [comment]
GCUIGLOBALS.GLOBAL.MBIN changed in 7332732 which is more recent than what MBINCompiler 3.64.0.1 was build on, so it does not have those changes and fails.  Normal behavior! **Not a bug.**

To get the latest version of MBINCompiler goto :

[https://github.com/monkeyman192/MBINCompiler/actions/runs/1234243025](https://github.com/monkeyman192/MBINCompiler/actions/runs/1234243025)

Download the MBINCompiler zip file in the **_Artifacts_** section, unblock it (in properties), un-zip to a temp folder and grab MBINCompiler.exe in the MBINCompiler\Build\Release\net5 folder.  There is also the .net 5 version of libMBIN.dll in there.

For NMSPE of AMUMSS,  go to MBINCompiler\Build\Release\net4 folder and get the libMBIN-dotnet4.dll.  Copy/ paste to the main folder of AMUMSS,  Delete libMBIN.dll there.  Rename libMBIN-dotnet4.dll to libMBIN.dll. Done!

**Comment by clampi** [comment]
Not sure what release you are pointing to, I get to an empty page when I click the link.

If the latest public release is emitting the warnings, it is still a defect in my opinion. It might be fixed upstream, but that only means a new public release is required for me to be able to work with the file in question.

**Comment by clampi** [comment]
To be more precise, 3.64,0.1 decompiled fine GCUIGLOBALS.GLOBAL.MBIN until the update pushed this morning through steam. So a new public release of MBINCompiler which includes the changes needed would be in order.

**Comment by HolterPhylo** [comment]
You are right!  That link does not work for me either when I click it above.  I did not do it correctly above.

Revisiting your first comment, I see you have updated this morning to :
> NMS Game Version or Steam Build Number: 734397

Please use this one, unless NMS updated again.  That works for me. 

[https://github.com/monkeyman192/MBINCompiler/actions/runs/1232053110](https://github.com/monkeyman192/MBINCompiler/actions/runs/1232053110)

Then follow the above instructions to get the latest MBINCompiler that should be updated for 734397.  **Remember that MBINCompiler always tries to match the latest Experimental branch of No Man's Sky on Steam.**  You are on the Public branch.

With HG currently pushing updates _very often_, MBINCompiler is constantly being updated as fast as we can.  Real life also, be patient!  Thanks

**Comment by clampi** [comment]
3.65.0.1 solved the problem, thank you.
