### ISSUE TITLE
Un/Supported Structs

### ISSUE THREAD

**Issue by Fuzzy-Logik** [monkeyman192/MBINCompiler#41]
If libMBIN stored some information about what structs have known issues, it would be possible to detect unsupported files and report it to the user. This would help to avoid many unnecessary bug reports for structs that have yet to be updated.

**Comment by GaticusHax** [comment]
We can make this work fairly easily now.

With each struct having a GUID, we can use a `Broken` NMSAttribute parameter to indicate files with known issues, such as METADATA\INPUTTEST.MBIN.

When NMS is updated, all changed structs can be me marked with the `Broken` property pending their fixes. That will allow for updates to be released while some structs are waiting to be updated.

MBINCompiler can be updated to detect both the GUID and Broken flags and warn the user that the files are unsupported.

**Comment by monkeyman192** [comment]
sounds good to me :)

**Comment by GaticusHax** [comment]
I think we can call this done.
