### ISSUE TITLE
[v3.68.0.1] Attempting to convert file "GCUIGLOBALS.GLOBAL.MBIN" does not work.

### ISSUE THREAD

**Issue by Galenmacil** [monkeyman192/MBINCompiler#412]
**Console Output:**
Converting C:\Fred\Games Modding\No Man's Sky 3.6\Projects\UI Tweaks\GCUIGLOBALS.GLOBAL.MBIN

[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.

  [INFO]: C:\Fred\Games Modding\No Man's Sky 3.6\Projects\UI Tweaks\GCUIGLOBALS.GLOBAL.MBIN

[ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.

**MBINCompiler.log content:**
[VERSION]: MBINCompiler v3.68.0.1
[ARGS]: "-y" "-i" "EXML" "-o" "MBIN" "."

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: 0 files converted.

[INFO]: TIME: 0 seconds

Operation was working fine in previous MBINCompiler version.

**Comment by monkeyman192** [comment]
If it worked on an old version, then it means that you need to use an older version of MBINCompiler (hence the "[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.").
The latest MBINCompiler binary is for the latest experimental release, so if you are not on it you should use the previous MBINCompiler version 😄 (If using AMUMSS there are steps to follow to use an older version I believe...)

**Comment by Galenmacil** [comment]
Oh ok. Sorry for that. I immediately assumed a bug...
