### ISSUE TITLE
[UPDATE] Changes for 3.70(?) (7553326)

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#414]
## New structs:

- [x] GcGroundWormComponentData	0xC227EED70BB33F53	41
- [x] GcMissionConditionOnPlanetWithSandwormsOverriden	0xF75A70C05C76AA44	2
- [x] GcMissionConditionShieldDown	0x6BF5DBA523DE0C11	1
- [x] GcMissionConditionTakingDamage	0x959EEF00D2B6816B	2
- [x] GcSandwormTimerAndFrequencyOverride	0x15E41A2902E18EE6	3

## Structs with internal changes:

- [x] GcAlienPuzzleEntry	0x1B1D3EF8AFB7C755
- [x] GcAlienPuzzleOption	0x8331A004540D5284
- [x] GcAlienPuzzleTable	0x73B1CCF70E87ACB3
- [x] GcAudioAreaTriggerComponentData	0x231601B847B2CAAF
- [x] GcAudioWwiseEvents	0x8ED4B3D64C581B48
- [x] GcConsumableItem	0x3D75ED83F93ED1CA
- [x] GcConsumableItemTable	0xA02816F032B60544
- [x] GcCreatureCrystalMovementData	0x8A40157B4815A3C4
- [x] GcCreatureCrystalMovementDataParams	0xA41FA6F83AA3DDEA
- [x] GcDefaulMissionProduct	0xFD07D764351D9C44
- [x] GcDefaulMissionSubstance	0x66AFC9E6510A3403
- [x] GcDefaultMissionItemsTable	0x10F691A04CD2BB62
- [x] GcDestructableComponentData	0xED47FD409C8797FF
- [x] GcEncounterComponentData	0x1CBAA2AF7483FD9F
- [x] GcExperienceSpawnTable	0xE708D4288044E050
- [x] GcExplosionData	0x66AEEFACE5FDC5CF
- [x] GcExplosionDataTable	0x387E3703B4CDF8A3
- [x] GcGalaxyAudioSetupData	0xFB8754997DA361A3
- [x] GcGenericMissionSequence	0x8C0B036D3822AAFD
- [x] GcGrabPlayerComponentData	0xC2F083053B0FAA9C
- [x] GcHUDStartup	0xDFCC7612FD2C07FB
- [x] GcHUDStartupTable	0xDC712D78CA8E7CA0
- [x] GcInventorySlotActionData	0x1157BBC7BFC2AA28
- [x] GcLaserBeamData	0xC4C62AC91045E0A7
- [x] GcMissionConditionHasTechnology	0x2689C66A9812B7DB
- [x] GcMissionConditionInCombat	0x3976F75383D76798
- [x] GcMissionConditionIsTechnologyRepaired	0x6004AC2A827EC255
- [x] GcMissionConditionProductKnown	0x712D6804118F3A87
- [x] GcMissionConditionTechnologyKnown	0x303FCB7CE848E221
- [x] GcMissionSequenceAudioEvent	0xD854C0D8FFA1CC7
- [x] GcMissionSequenceDetailMessage	0x15D122F716C8436A
- [x] GcMissionSequenceRepairTech	0x81E5D0092B05967A
- [x] GcMissionSequenceShowMessage	0x6C919AA5AA23E95A
- [x] GcMissionTable	0x6753B34631E254FD
- [x] GcPerformanceGuard	0x924094B8F727824
- [x] GcProjectileData	0x678C02B9E33C9DEB
- [x] GcProjectileDataTable	0x66AB8F5EF29EBBC
- [x] GcPulseEncounterInfo	0x5D81E441F67671AC
- [x] GcRewardFrigateFlyby	0x7F7D743901922DF2
- [x] GcRewardMultiSpecificItems	0xF86ED48EA11560E
- [x] GcRewardOSDMessage	0xAC186AD784DB0CE3
- [x] GcRewardSecondaryInteractionOptions	0x33B08665AE009029
- [x] GcScanEventData	0x31A29A43290207FC
- [x] GcScanEventTable	0x8813C85705C75E66
- [x] GcScannerIconTypes	0x320E4FBE3248CBE5
- [x] GcSimpleInteractionComponentData	0x45BA4B04F7202F8F
- [x] GcStatsEnum	0x2554D296719E9ED4
- [x] GcWeatherEffect	0x66BEBE5A4D2DF040
- [x] GcWeatherEffectTable	0x13E6D80F5BF3A7B3
- [x] gcproducttableEnum	0x80FA1B8AA1CDC1AE
- [x] gcsubstancetableEnum	0xEB096AEFF16AA6CB
- [x] gctechnologytableEnum	0x92B0D75CF9321047

## Structs with a file size change:

- [x] GcDefaultSaveData	old: 0x4D560	new: 0x4D580	GUID: 0x20350EF1682D4AA	fields: 2	
- [x] GcGameplayGlobals	old: 0x1DD0	new: 0x1E00	GUID: 0x59616D8A080ECB8A	fields: 535 (+3)	
- [x] GcMissionConditionHasFuel	old: 0x18	new: 0x20	GUID: 0x4B5BC2DFD4B2C5D8	fields: 4 (+1)	
- [x] GcMissionConditionHasSubstance	old: 0xC	new: 0x10	GUID: 0xD332F70D80FD64DE	fields: 4 (+1)	
- [x] GcMissionConditionInSeasonalUA	old: 0x1	new: 0x8	GUID: 0xE980B8AD2A23D04D	fields: 2 (+2)	
- [x] GcMissionConditionSystemPlanetTest	old: 0x1	new: 0x8	GUID: 0x26E11953489FD24C	fields: 2 (+1)	
- [x] GcMissionConditionWeather	old: 0x3	new: 0xC	GUID: 0xAAA343CB48DFA0FC	fields: 5 (+2)	
- [x] GcMultiSpecificItemEntry	old: 0x50	new: 0x58	GUID: 0xC9F01733A4D84257	fields: 9 (+1)	
- [x] GcPlayerStateData	old: 0x4D4B0	new: 0x4D4D0	GUID: 0xB7FC557507EA41D1	fields: 200	
- [x] GcRewardTable	old: 0x140	new: 0x170	GUID: 0xE4836E027E1BA2F6	fields: 23 (+3)	
- [x] GcScannableComponentData	old: 0x80	new: 0x88	GUID: 0xB0ADA514278F1853	fields: 19 (+1)	
- [x] GcScannerIcons	old: 0x12B90	new: 0x12DC0	GUID: 0xB379FA50914ED263	fields: 79	
- [x] GcSeasonalGameModeData	old: 0xBC8	new: 0xBE0	GUID: 0x8258EDE519B5C7EE	fields: 49 (+4)	

## Structs with a field number changes:

- [x] GcCreatureGlobals	old: 0xn/a	new: 0xn/a	GUID: 0xD42E3A1B54A9B118	fields: 579 (+11)	
- [x] GcMissionConditionHasProduct	old: 0x10	new: 0x10	GUID: 0xE46DEF08271DF4CA	fields: 7 (+1)	
- [x] GcMissionSequenceCollectProduct	old: 0x140	new: 0x140	GUID: 0x33CFFFA112AE370	fields: 12 (+1)	
- [x] GcMissionSequenceCollectSubstance	old: 0x140	new: 0x140	GUID: 0x46CF52B7ECF6568A	fields: 11 (+1)

**Comment by codyLowen** [comment]
Any chance of a GcGameplayGlobals update today? attempting to do so myself with the source however I am not very well versed in decompiler's. Is there a reason the source uses .net 4.5.2 when building as opposed to the required .net 5.0?
