### ISSUE TITLE
[UPDATE] Changes for  7581240 (3.71?)

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#415]
- [x] TkStaticPhysicsComponentData	0x77B2BE2533CE3B9F	9

## Structs with internal changes:

- [x] GcBuildMenuOption	0xF8FB36A4D7DFEDDA
- [x] GcPlanetBuildingData	0x74A654AE55B44DE7
- [x] GcPlanetData	0x61F4781A63B7AC9C
- [x] TkParticleData	0x620376E8715B3267

## Structs with a file size change:

- [x] GcBuildingDefinitionData	old: 0x78	new: 0x70	GUID: 0x2B2DB3B7FBBD9982	fields: 12 (-1)	
- [x] GcBuildingDefinitionTable	old: 0x9A7F8	new: 0x9A660	GUID: 0xE2224B63F1C9F55E	fields: 3	
- [x] GcBuildingDensity	old: 0x10	new: 0x4	GUID: 0xB7C2AFAB0166AACB	fields: 1 (-1)	
- [x] GcBuildingGlobals	old: 0x1160	new: 0x1270	GUID: 0x51E7DCDE36888079	fields: 173 (+3)	
- [x] GcBuildingSpawnData	old: 0x610	new: 0x600	GUID: 0x2F9F6DE29A3DE97E	fields: 27 (-1)	
- [x] GcUIGlobals	old: 0x57E0	new: 0x5840	GUID: 0x8B7824D9ACA57553	fields: 1194

**Comment by aharttsx** [comment]
I noticed that the GCCREATUREGLOBALS.MBIN isn't working with the current version of mbincompiler yet.  I didn't see it in this list of upcoming changes and was wondering if fixing that is gonna be part of this update?

**Comment by monkeyman192** [comment]
> 
> 
> I noticed that the GCCREATUREGLOBALS.MBIN isn't working with the current version of mbincompiler yet. I didn't see it in this list of upcoming changes and was wondering if fixing that is gonna be part of this update?

What version of the game are you on (experimental or public) and what version of MBINCompiler are you using?
It should be supported....

**Comment by aharttsx** [comment]
> 
> 
> > I noticed that the GCCREATUREGLOBALS.MBIN isn't working with the current version of mbincompiler yet. I didn't see it in this list of upcoming changes and was wondering if fixing that is gonna be part of this update?
> 
> What version of the game are you on (experimental or public) and what version of MBINCompiler are you using? It should be supported....

MBINCompiler version is 3.70.0 and im on the public build (build id 7553326).  I've tried a number of other .mbin's and they worked fine.  

Edit - when I try to convert the GCCREATUREGLOBALS.MBIN to .exml it says "[WARN]: File not recognized.  You may need to use an older (or newer) version of MBINCompiler." along with "[ERROR]:  [MbinException]: Exception has been thrown by the target of an invocation.".
