### ISSUE TITLE
.net Runtime

### ISSUE THREAD

**Issue by carrow26** [monkeyman192/MBINCompiler#424]
Later versions of mbincompiler need .net5. Is this the console or desktop download?

**Comment by HolterPhylo** [comment]
this [https://dotnet.microsoft.com/download/dotnet/5.0/runtime](url)

**Comment by cmkushnir** [comment]
.NET Desktop Runtime 5.x x64
https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by monkeyman192** [comment]
I think this can be closed as it has been answered
