### ISSUE TITLE
Not Decompiling: PROJECTILETABLE.MBIN , and NMS_REALITY_GCTECHNOLOGYTABLE.MBIN

### ISSUE THREAD

**Issue by BradfordCB** [monkeyman192/MBINCompiler#431]
No Mans Sky Version 3.81

[VERSION]: MBINCompiler v3.75.0.1
[ARGS]: "T:\BCB.NMS.Mods\BCB-Straff-Minig 2202\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [INFO]: T:\BCB.NMS.Mods\BCB-Straff-Minig 2202\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	74ABDF93A8997CE2	template:	cGcTechnologyTable
[EXPECTED INFO]: GUID: 3BFF7045B5963FD0

[ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.
[InvalidListException]: Invalid list read, magic 00000005 expected xxxxxx01 at 0x620

[INFO]: T:\BCB.NMS.Mods\BCB-Straff-Minig 2202\METADATA\REALITY\TABLES\NMS_REALITY_GCTECHNOLOGYTABLE.MBIN
[INFO]: MBIN	version:	0.0.0.0	guid:	74ABDF93A8997CE2	template:	cGcTechnologyTable

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by DeathWrench** [comment]
Newer version is being worked on, see here: https://github.com/monkeyman192/MBINCompiler/issues/429
