### ISSUE TITLE
Log file information lacking a reference to the file and path that caused the log entry

### ISSUE THREAD

**Issue by HolterPhylo** [monkeyman192/MBINCompiler#444]
Using v3.82.0-pre2

**Is your feature request related to a problem? Please describe.**
- In certain conditions, the Log file information is lacking a reference to the file and path that caused the log entry.
In this case, EXML files (MBIN files could also suffer from this lack of info, did not verify)

**Describe the solution you'd like**
- Every log entry of any type (normal, WARNING or ERROR) should referenced the involved filename and path like this:
[INFO]: D:\AMUMSS\MODBUILDER\MOD\METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.EXML

**Describe alternatives you've considered**
- Otherwise, the log info is only meaningful when converting ONE file at the time (because the file involved is known).
In bulk operation, the log info becomes impossible to related to a file in particular when many are processed

**Additional context**
- It looks like all Logger.Log... calls, outside of class MBINCompiler, do not have access to the filename and path of the current file being converted, so they cannot reference it in the log file.
If only Logger was aware of the filename and path currently processed...

Example log file output:
![image](https://user-images.githubusercontent.com/3037251/159514710-f02904b0-47e5-4856-a4df-b781ef3e407c.png)

- These particular log messages are generated in libMBIN.BinaryStreamExtensions.WriteString but do not show which file or files caused them.
It should be able to do as MBINCompiler.Commands.Convert.WarnBroken does with 
     Logger.LogMessage( null, "INFO", $"{CommandLine.GetFileInfo( mbin )}" );

**Mitigating information**
If we just print the filename and path as each file is about to be processed (as cmkushnir comments below):
- The problem looks worst when multiple-threads are used (that is the default usage)
- If multiple-threads are NOT allowed, the log file content makes more sense as the information is at least sequential.

**Comment by cmkushnir** [comment]
Would it be enough to just print the filename and path as each file is about to be processed, so you know that all following messages are for that file, or does it need to be on each line because you want to use code to parse the line for the filename and path ?
Putting the full path on each message might make some rather awkward to scan by eye.

**Comment by HolterPhylo** [comment]
It would be alright.
My intention was not to have each individual message tagged with the filename/path, but any message is emitted during its processing then at least one reference is required (said reference being 'before' or 'after' the log messages can be resolved if always done the same way)

If all files that are processed are listed in the log, it may make for a very huge log file.
But it would show which files were processed (successfully or not).
This is not required.

I can live with both ways, parsing the file is easy

**Comment by HolterPhylo** [comment]
Weird, it let me edit the above message but it won't show edited when I click the save comment!!

Edited version:
but **if** any message is emitted
