### ISSUE TITLE
newly introduced bug in libMBIN API

### ISSUE THREAD

**Issue by monkeyman192** [monkeyman192/MBINCompiler#449]
**Describe the bug**
I think an issue was introduced by #447 when the `WriteToExml` method for `NMSTemplate` was updated.
Because this is part of the libMBIN API we shouldn't have changed it, or at least added the new option as a separate method so as to not break backward compatibility (ie. the current version of the PCBANKS explorer doesn't handle it I think

**Proposed solution**
We need the original `WriteToExml` method back.
I propose we just add it and it calls the new method with the default value (ie. false).
Also, while there it would be good to update the summary above the method(s) so that they are correct.

**Comment by HolterPhylo** [comment]
The incompatibility is with NMSPE not libMBIN.dll as the param is optional in both 

![Screenshot - 2022-04-14 , 11_05_58](https://user-images.githubusercontent.com/3037251/163423790-5ad6d774-207d-4186-9336-0c8c913d7eee.png)

![Screenshot - 2022-04-14 , 11_06_46](https://user-images.githubusercontent.com/3037251/163423883-0ab5673c-1545-4d29-99db-21d97f000684.png)

I re-build NMSPE and it works fine as far as I can tell

**Comment by HolterPhylo** [comment]
I have a solution... see PR #450

**Comment by cmkushnir** [comment]
Fixed in v3.87.0-pre2, suggest closing.
