### ISSUE TITLE
GCPROCPRODUCTTABLE.MBIN: Values index out of range

### ISSUE THREAD

**Issue by VulcanTourist** [monkeyman192/MBINCompiler#45]
This error occurred when trying to decrypt METADATA\REALITY\TABLES\GCPROCPRODUCTTABLE.MBIN:

> Values index out of Range. Struct: libMBIN.Models.Structs.GcRealitySubstanceCategory field: SubstanceCategory
ERROR: An unknown exception occurred!
Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.MBINFile.GetData()
   at MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose)
   at MBINCompiler.Program.Main(String[] args)

I was using the latest MBINCompiler 1.53.0-pre3, but since NEXT I have never until now tried to decrypt any game MBINs and there was a game patch last night or early this morning, so whether the patch has necessitated an update to the compiler and I'm just lucky to be on the cutting edge of it, I don't know.  Attempting to decrypt this file was actually an accident on my part, as I intended to decrypt the following file, GCPRODUCTTABLE.MBIN.

**Comment by monkeyman192** [comment]
I am not sure what is going on but I believe I have the most recent version of the file and the current version works just fine?
If not, I have just uploaded a newer version which works for the file I have.
If this still doesn't work, attach the file here and I can take a look...

**Comment by VulcanTourist** [comment]
I have pre4 and again unpacked the game's files, just to rule out corruption during that process.  I still get the same error.  I'm attaching the file...

... except that I can't: "Something went really wrong and we can't process that file."  I compressed it with 7-Zip into a Zip file using its defaults.  Alternatives?

**Comment by monkeyman192** [comment]
well the game just updated again, so I will take another look too see if that has affected it.
And I think if you give it the .txt extension it will allow it (I can just change it again on my end)

**Comment by VulcanTourist** [comment]
Are you referring to 1.54 that was released yesterday, or did you receive *another* patch after that one?  What game build do you have now?  I currently have build 3000263, and there are no updates pending.  I presume but am not certain that this is the same build I had after yesterday's update.  It might explain why some or all of my mods are currently broken, including the merges that I put together just yesterday.

**Comment by VulcanTourist** [comment]
I just tried your suggestion to rename the zip as a .txt file and try to upload that, but it *still* informs me that "something went really wrong...."

**Comment by monkeyman192** [comment]
I will be on the most recent experimental build on steam. Current version is 1.55 also (according to GOG)
I will have another look into this when I get home and can.

**Comment by VulcanTourist** [comment]
It seems to me that I wasted my time yesterday trying to merge mods that were already technically out of date, and now 1.55 is on the way?  Many things didn't seem to work when I played briefly, except my swimming speed experiment.  Should I wait until you can vet the Compiler for 1.54 or 1.55 before I try to fix anything?  This is my first encounter with modding a game in active development; it sucks as much (for everyone) as I knew it would.

**Comment by monkeyman192** [comment]
it is always crazy right after an update comes out. Keep in mind that it has only been like 2 weeks since the update. Usually it is about a month for everything to settle down
I will verify the most recent version tonight.

**Comment by VulcanTourist** [comment]
I'm trying this in another browser instead of my heavily defended Firefox, and it looks like it's accepted the Zip file finally...?

**Comment by monkeyman192** [comment]
As weird as it seems, those are actually the values that the mbins have in them... The exe indicates that they are a float, and when you look at the data directly you can see that their value is indeed that...
I don't really know what it means, but no other data type makes sense either (if they were an int the values would be like 945143694)

**Comment by monkeyman192** [comment]
I believe this has been resolved...
