### ISSUE TITLE
Could not decompile 

### ISSUE THREAD

**Issue by DawnShadow** [monkeyman192/MBINCompiler#451]
[VERSION]: MBINCompiler v3.84.0.2
[ARGS]: "convert" "-y" "-f" "C:\__modding\NMS\Unpacked game files\GCDEBUGOPTIONS.GLOBAL.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML
[INFO]: C:\__modding\NMS\Unpacked game files\GCDEBUGOPTIONS.GLOBAL.MBIN

[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [INFO]: C:\__modding\NMS\Unpacked game files\GCDEBUGOPTIONS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	87DAB6637DE673D8	template:	cGcDebugOptions
  [EXPECTED INFO]: GUID: D8AA1A7A1EB32119
  

[ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.
  [InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0xBF8
  
  [INFO]: C:\__modding\NMS\Unpacked game files\GCDEBUGOPTIONS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	87DAB6637DE673D8	template:	cGcDebugOptions
  
     at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read GcDebugOptions from MBIN.
  [FILE]: C:\__modding\NMS\Unpacked game files\GCDEBUGOPTIONS.GLOBAL.MBIN
  
[INFO]: 1 WARNINGS.

  [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [FILE]: C:\__modding\NMS\Unpacked game files\GCDEBUGOPTIONS.GLOBAL.MBIN
  
[INFO]: TIME: 0.102 seconds
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/8500178/MBINCompiler.log)

**Comment by HolterPhylo** [comment]
This is not a bug.
NMS was updated!!
MBINCompiler is not updated YET to handle this file... (and many more)
Please be patient
