### ISSUE TITLE
This is BUG? I can't open INVENTORYTABLE.MBIN

### ISSUE THREAD

**Issue by sukifung** [monkeyman192/MBINCompiler#453]
This is BUG? I can't open INVENTORYTABLE.MBIN
[VERSION]: MBINCompiler v3.84.0.2
[ARGS]: "D:\2\NMSARC.515F1D3\METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML
[INFO]: D:\2\NMSARC.515F1D3\METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN

[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [INFO]: D:\2\NMSARC.515F1D3\METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	ECB5C4E56D307F90	template:	cGcInventoryTable
  [EXPECTED INFO]: GUID: FD7370FC56486179
  

[ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.
[InvalidListException]: Invalid list read, magic 428C0000 expected xxxxxx01 at 0x4D0

[INFO]: D:\2\NMSARC.515F1D3\METADATA\REALITY\TABLES\INVENTORYTABLE.MBIN
[INFO]: MBIN	version:	0.0.0.0	guid:	ECB5C4E56D307F90	template:	cGcInventoryTable

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)

**Comment by masternetra** [comment]
Same can't decompile ANY MBIN, In NMS Mod station it claims it's been decompiled but no decompiled file is created and drag and dropping is yielding no results either. MBINCompiler is broken when it comes to decompiling mbins

**Comment by Babscoole** [comment]
Not a bug, MBINCompiler hadn't been updated for Outlaws compatibility yet.  Partial update posted a few hours ago.
