### ISSUE TITLE
EXmlFile.cs WriteTemplate - Ambiguous match found

### ISSUE THREAD

**Issue by cmkushnir** [monkeyman192/MBINCompiler#455]
System.Reflection.AmbiguousMatchException: 'Ambiguous match found.'

libMBIN/Source/EXML/EXmlFile.cs:
        public static string WriteTemplate(NMSTemplate template) => WriteTemplate(template, false);
        public static string WriteTemplate(NMSTemplate template, bool hideVersionInfo = false)

Please either remove the default value for hideVersionInfo or remove the method w/o hideVersionInfo.

**Comment by cmkushnir** [comment]
Reviewing the change that added the extra method:
https://github.com/monkeyman192/MBINCompiler/commit/c2729e2c3962ae42b7e022971ffe1d09dd461198

The same problem exists with the change in NMSTemplate.cs, either remove the method w/o hideVersionInfo, or remove the default value for hideVersionInfo.

**Comment by cmkushnir** [comment]
I would normally suggest removing the old single param method, and keeping hideVersionInfo = false, as this should allow most old code to still work.  The exception would be if an app tries to find the method via reflection and is specifying the list of param types.  If there's an app like that and it can't|won't be updated then remove the = false from the 2nd method, of course apps that don't specify the list of param types will have to be updated to now include them.

**Comment by HolterPhylo** [comment]
I wonder why can't both co-exist?  I tested with both older/latest version of NMSPE and did not get a complain like 'System.Reflection.AmbiguousMatchException: 'Ambiguous match found.'

I am not a C# guru like you :)

My 1st attempt was to only add the 'bool hideVersionInfo = false' to those methods (like you said).  But it did not work with the older NMSPE (I always believed an optional parameter was optional !?)  So, having older NMSPE causing exception, I added the old single param method and _that satisfied both version_.  Why reflection has a problem with it is still foggy for me...

Ok, so using reflection to get those methods, causes problem if I understand correctly...

Does prevent your app from working at the moment?

**Comment by HolterPhylo** [comment]
Just read your comment in Discord!!

> Now that there are two that can both be called w/ a single arg there is an ambigous match.

It makes more sense now...

**Comment by HolterPhylo** [comment]
Ok, tested removing the ' = false' in both methods and works with older/latest NMSPE
Would that be ok on your side?

**Comment by cmkushnir** [comment]
Yep, that's fine, thanks.  The only ones that would be effected by that solution would be those that find the methods using reflection and specify the binding flags instead of the params, they would now have an ambiguous lookup in Type.GetMethod.  But I don't think anyone is doing that (other than the current NMSMB, but the next release will be fine).

**Comment by HolterPhylo** [comment]
Great, will have in next release

**Comment by cmkushnir** [comment]
Fixed in v3.87.0-pre2.
