### ISSUE TITLE
v3.87.0-pre1 - Cannot decompile seemingly any NMS patch 3.87 MBINs

### ISSUE THREAD

**Issue by Fuhtuhwuh** [monkeyman192/MBINCompiler#457]
Reproduction:
Open any extracted mbin file with the mbin compiler, nothing happens. If I do so with the NMS modding station and try to open the MBINCompiler log, I get the attached information. (log file)

-v.387.0-pre1 MBINCompiler full download
-NMS Build ID: 8566757
-MBIN Files tried: PIRATEMISSIONTABLE, PLANETPROCMISSIONTABLE, SPACEPOIMISSIONTABLE, PLAYERANIMSTABLE, TKGAMESETTINGS, TKGRAPHICSSETTINGS, BASEBUILDINGTABLE, COSTTABLE, LEGACYBASEBUILDINGTABLE, LEGACYITEMTABLE, NMS_REALITY_GCPROCEDURALTECHNOLOGYTABLE, NMS_REALITY_GCPRODUCTTABLE, NMS_REALITY_GCRECRIPETABLE, TRADINGCOSTTABLE... (you get the picture)

[log.txt](https://github.com/monkeyman192/MBINCompiler/files/8532361/log.txt)

**Comment by Babscoole** [comment]
v3.87.0-pre2 is out and another release will be coming for 3.88.

**Comment by HolterPhylo** [comment]
v3.87.0-pre1 was a partial release as stated on the release, not a bug.
