### ISSUE TITLE
Multi-Threaded Compiling for faster building

### ISSUE THREAD

**Issue by djdomi** [monkeyman192/MBINCompiler#468]
**Is your feature request related to a problem? Please describe.**
No. Or Maybe yes: the compiled performance is slowly.

**Describe the solution you'd like**
A Multi-Threaded variant, that either can accept multiple arguments and can process it easier or some kind of using more CPU Power - I mean, basically - the XEON E5 has nothing to do at the moment of writing.

**Describe alternatives you've considered**
As I have seen you have SQLite binaries deployed, add all the Files into a SQLite which will be read numerous faster. There is also a pinpoint, that you can use fingerprint for checking for changes before using the DB instead of the files.

**Additional context**
I like to see, that this project is still under progress, which I really like.
However, compiling just 12 LUA files from the Collection take ages.
I also respect the point, that it takes to change many files; however, it does it one by one if I see it correctly. It can also be an issue how AMUMSS it is using this, but I think  it's due to the limitation of the program…? :)
Maybe @HolterPhylo can get a word here if he is limited for his work on one by one instead a many fileS? 👍

**Comment by HolterPhylo** [comment]
MBINCompiler is multi-threaded.
What you are talking about is an AMUMSS fact that will be addressed in the next release
This issue can be closed
