### ISSUE TITLE
PLANTINTERACTION.ENTITY.EXML files won't recompile

### ISSUE THREAD

**Issue by illegallyretarded** [monkeyman192/MBINCompiler#469]
[INFO]: Auto-Detected --input-format=EXML
[INFO]: --input-format=EXML --output-format=MBIN

[ERROR]: [AggregateException]: One or more issues occurred
[ExmlException]: An EXML exception has occurred!
[NullReferenceException]: Object reference is not set to an object instance 

   ved libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   ved libMBIN.NMSTemplate.DeserializeEXmlValue(NMSTemplate template, Type fieldType, FieldInfo field, EXmlProperty xmlProperty, Type templateType, NMSAttribute settings)
   ved libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   ved libMBIN.EXmlFile.ReadTemplateFromXmlReader(XmlReader reader, String& templateName)
   ved libMBIN.EXmlFile.ReadTemplateFromStream(Stream input, String& templateName)
   ved MBINCompiler.Commands.Convert.ConvertEXML(String inputPath, FileStream fIn, MemoryStream msOut, String fileOut)

SPECS
 - libMBIN (MBINCompiler) Version: [3.5.0.1]
 - Steam Build Number: [8591779]
 - MBIN File: [PLANTINTERACTION.ENTITY.MBIN]
 - MBIN File Version: [eg 3.5.01]

**Comment by monkeyman192** [comment]
Please do not simply remove the info in the issue template, we have it there for a reason so that you can provide enough information for us to understand the actual issue.

eg.
```
**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: [eg 1.0.0.0]
 - NMS Game Version or Steam Build Number: [eg 1.0.0.0, or 4154325] (To find the build number, right click on the game in steam, select `Properties`, then click on the `LOCAL FILES` tab and the buildID is at the bottom).
 - MBIN File: [eg GCPLAYERGLOBALS.GLOBAL.MBIN]
 - MBIN File Version: [eg 1.0.0.0]
 ```

**Comment by illegallyretarded** [comment]
Updated with specs

**Comment by illegallyretarded** [comment]
I'm so sorry it was a fuck up completley my fault.

**Comment by monkeyman192** [comment]
All good. Was going to say your MBINCompiler version isn't up to date! I'll close this then.
