### ISSUE TITLE
Failed to decompile some files

### ISSUE THREAD

**Issue by DawnShadow** [monkeyman192/MBINCompiler#470]
GCGAMEPLAYGLOBALS.MBIN = failed
Log:
> [VERSION]: MBINCompiler v3.88.0.2
> [ARGS]: "convert" "-y" "-f" "C:\__modding\NMS\Unpacked game files\GCGAMEPLAYGLOBALS.GLOBAL.MBIN"
> 
> If you encounter any errors, please submit a bug report and include this log file.
> Please check that there isn't already a similar issue open before creating a new one.
> https://github.com/monkeyman192/MBINCompiler/issues
> 
> [INFO]: Auto-Detected --input-format=MBIN
> [INFO]: --input-format=MBIN --output-format=EXML
> [INFO]: C:\__modding\NMS\Unpacked game files\GCGAMEPLAYGLOBALS.GLOBAL.MBIN
> 
> [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
>   [INFO]: C:\__modding\NMS\Unpacked game files\GCGAMEPLAYGLOBALS.GLOBAL.MBIN
>   [INFO]: MBIN	version:	0.0.0.0	guid:	11B521D3F430EA92	template:	cGcGameplayGlobals
>   [EXPECTED INFO]: GUID: F25C3ADE916F9ED7
>   
> 
> [ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.
>   [InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0xA40
>   
>   [INFO]: C:\__modding\NMS\Unpacked game files\GCGAMEPLAYGLOBALS.GLOBAL.MBIN
>   [INFO]: MBIN	version:	0.0.0.0	guid:	11B521D3F430EA92	template:	cGcGameplayGlobals
>   
>      at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
>   
> 
> [INFO]: 0 files converted.
> 
> [INFO]: 1 FILES FAILED.
> 
>   [ERROR]: Failed to read GcGameplayGlobals from MBIN.
>   [FILE]: C:\__modding\NMS\Unpacked game files\GCGAMEPLAYGLOBALS.GLOBAL.MBIN
>   
> [INFO]: 1 WARNINGS.
> 
>   [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
>   [FILE]: C:\__modding\NMS\Unpacked game files\GCGAMEPLAYGLOBALS.GLOBAL.MBIN
>   
> [INFO]: TIME: 0.028 seconds

GCUIGLOBALS.MBIN = failed
Log:
> [VERSION]: MBINCompiler v3.88.0.2
> [ARGS]: "convert" "-y" "-f" "C:\__modding\NMS\Unpacked game files\GCUIGLOBALS.GLOBAL.MBIN"
> 
> If you encounter any errors, please submit a bug report and include this log file.
> Please check that there isn't already a similar issue open before creating a new one.
> https://github.com/monkeyman192/MBINCompiler/issues
> 
> [INFO]: Auto-Detected --input-format=MBIN
> [INFO]: --input-format=MBIN --output-format=EXML
> [INFO]: C:\__modding\NMS\Unpacked game files\GCUIGLOBALS.GLOBAL.MBIN
> 
> [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
>   [INFO]: C:\__modding\NMS\Unpacked game files\GCUIGLOBALS.GLOBAL.MBIN
>   [INFO]: MBIN	version:	0.0.0.0	guid:	D971A8AC552735A1	template:	cGcUIGlobals
>   [EXPECTED INFO]: GUID: B465C6404E609BCD
>   
> 
> [ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.
>   [InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x2250
>   
>   [INFO]: C:\__modding\NMS\Unpacked game files\GCUIGLOBALS.GLOBAL.MBIN
>   [INFO]: MBIN	version:	0.0.0.0	guid:	D971A8AC552735A1	template:	cGcUIGlobals
>   
>      at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
>   
> 
> [INFO]: 0 files converted.
> 
> [INFO]: 1 FILES FAILED.
> 
>   [ERROR]: Failed to read GcUIGlobals from MBIN.
>   [FILE]: C:\__modding\NMS\Unpacked game files\GCUIGLOBALS.GLOBAL.MBIN
>   
> [INFO]: 1 WARNINGS.
> 
>   [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
>   [FILE]: C:\__modding\NMS\Unpacked game files\GCUIGLOBALS.GLOBAL.MBIN
>   
> [INFO]: TIME: 0.063 seconds

**Comment by monkeyman192** [comment]
I'm going to assume that this has been fixed at some point with the recent updates since no-one else has complained about it.
