### ISSUE TITLE
Decompile not working for GCSPACESHIPGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by MrNegative420** [monkeyman192/MBINCompiler#472]
Using AMUMSS and sadly the MBINCompiler.exe looks to be out of date and can't read the new GCSPACESHIPGLOBALS.GLOBAL.MBIN file that's all. Nice work looking forward to using it again. ty

**Comment by monkeyman192** [comment]
You managed to open this ticket in the less than 10 minutes that I closed the update ticket because it was complete, and the build was processing on the CI.
Latest version is now up which should work.
