### ISSUE TITLE
"GCAISPACESHIPGLOBALS.GLOBAL.MBIN" failed to decompiled

### ISSUE THREAD

**Issue by DawnShadow** [monkeyman192/MBINCompiler#473]
**Describe the bug**
MBINCompiler encounters an error when trying to decompile the file "GCAISPACESHIPGLOBALS.GLOBAL.MBIN".

**Expected behavior**
A successful decompilation of the file.

**Steps To Reproduce**
Drag and drop the file "GCAISPACESHIPGLOBALS.GLOBAL.MBIN" from your unpacked game files onto "MBINCompiler.exe" (without .NET5 installed)

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: v3.91.0-pre1
 - NMS Game Version or Steam Build Number: No Man's Sky OUTLAWS - Expedition : Leviathan
 - MBIN File: GCAISPACESHIPGLOBALS.GLOBAL.MBIN
 - MBIN File Version: Latest NMS update

_Attachments:_

[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/8838118/MBINCompiler.log)

**Comment by monkeyman192** [comment]
I am going to assume this is no longer an issue and close it since no-one else had this problem.
