### ISSUE TITLE
Problem to decompile Defaultreality.mbin

### ISSUE THREAD

**Issue by SpeedySC1978** [monkeyman192/MBINCompiler#484]
hello together

please execuse my english language (german is main). It is not the best but i hope it works.

I got a problem with the updated MBIN Compiler and the "new" No Man's Sky Version 3.96. So aktually i can't update my mod to get work ingame.

 **- libMBIN (MBINCompiler) Version: 3.94.01
 - NMS Game Version or Steam Build Number: 9173694
 - MBIN File: DEFAULTREALITY.MBIN
 - MBIN File Version: Steam Build Number: 9173694**

This is what the report.xml said:

Getting METADATA\REALITY\DEFAULTREALITY.MBIN from NMS source PAKs
Trying to decompile... 
    [WARNING] MBINCompiler = [[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler. OR check your script!]
    
    [WARN]    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	E5ABEC52FBDBD639	template:	cGcRealityManagerData]
    [WARN]    MBINCompiler =   [[EXPECTED INFO]: GUID: 924284E3D4B8D501]
    [WARN]    MBINCompiler = [[ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.]
    [WARN]    MBINCompiler =   [[InvalidListException]: Invalid list read, magic 5954494C expected xxxxxx01 at 0x980]
    [WARN]    MBINCompiler =   [[INFO]: E:\NMS Mods\self made Mod Updates\No Man's Sky AMUMSS\MODBUILDER\_TEMP\EXTRACTED\METADATA\REALITY\DEFAULTREALITY.MBIN]
    [WARN]    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	E5ABEC52FBDBD639	template:	cGcRealityManagerData]
    [WARN]    MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)]
    [WARN]    MBINCompiler = [[INFO]: 1 FILES FAILED.]
    [WARN]    MBINCompiler =   [[ERROR]: Failed to read GcRealityManagerData from MBIN.]
    [WARN]    MBINCompiler =   [[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.]
Trying to decompile 
    [ERROR] MBINCompiler = [MbinException]: Exception has been thrown by the target of an invocation OR check your script!
    [PSARC] The PAK will not include this EXML
    [ERR]   MBINCompiler =   [InvalidListException]: Invalid list read, magic 5954494C expected xxxxxx01 at 0x980
    [ERR]   MBINCompiler =   [INFO]: E:\NMS Mods\self made Mod Updates\No Man's Sky AMUMSS\MODBUILDER\_TEMP\EXTRACTED\METADATA\REALITY\DEFAULTREALITY.MBIN
    [ERR]   MBINCompiler =   [INFO]: MBIN	version:	0.0.0.0	guid:	E5ABEC52FBDBD639	template:	cGcRealityManagerData
    [ERR]   MBINCompiler = [INFO]: 1 WARNINGS.
    [ERR]   MBINCompiler =   [WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.

Maybe there is a problem with my mod script or there is a failure with the compiler. I don't know what is wrong.

I need some help please. greetings by Speed

[REPORT.zip](https://github.com/monkeyman192/MBINCompiler/files/9179990/REPORT.zip)
y

**Comment by Babscoole** [comment]
MBINCompiler is not fully updated for Endurance yet, which is why you are seeing the error.  Can take a week or more after the release of a big NMS update.  The only thing to do is to wait and be patient.  :)

**Comment by SpeedySC1978** [comment]
Thank you for your reply. So i'll be patient. ;)

**Comment by monkeyman192** [comment]
Yep! Patience is key! 😄 
Unfortunately the update has come at a bad time so those of us who update it haven't much time so it's slower than usual...

**Comment by Babscoole** [comment]
...and the hotfixes barfing out every day, including Saturday and Sunday, hasn't helped.
