### ISSUE TITLE
Decompile Error: GCPLAYERGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by D-A-R-K-N-E-S-S** [monkeyman192/MBINCompiler#49]
When decompiling GCPLAYERGLOBALS.GLOBAL.MBIN, many properties have incorrect values. Here is a sample of a few of them:

```
<Property name="WeaponZoomFOV" value="1.401298E-45" />
<Property name="FrontShieldOffsetOff" value="1.401298E-45" />
<Property name="DamageRepairFactor" value="1.401298E-45" />
<Property name="MouseMaxLength" value="1.401298E-45" />
<Property name="LootForceMultiplier" value="2.802597E-45" />
```

Some random info:
-Problem occurs through all version of MBINCompiler, from 1.53.0-pre1 to 1.55.0-pre1

-MBINCompiler use to have no problem with this file until one of the recent updates from HG. This problem either started with 1.54 or definately with the experimental version of 8/08. I'm currently on the latest experimental build 8/09 (3020240).

-Many of the other "GC" files such as GCBUILDINGGLOBALS and GCUIGLOBALS decompile correctly.

Thank you.

**Comment by D-A-R-K-N-E-S-S** [comment]
Yes thanks, I mistyped...corrected it.

**Comment by monkeyman192** [comment]
This has been fixed in the latest release
