### ISSUE TITLE
dependency to .nET cORE libraries

### ISSUE THREAD

**Issue by BSarmady** [monkeyman192/MBINCompiler#495]
I don't have .net core runtimes on my system. running this app I get following error.

It would be nice to include the mentioned dll inside the exe file so it run without requiring to install another package just for using a single application (my developement machine is different from gaming machine).

https://stackoverflow.com/a/61232023

```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [******].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].
```

**Comment by monkeyman192** [comment]
I don't think this is a bug... I don't like the idea of including the dotnet stuff required to make it run otherwise the exe becomes hugely bloated.
I don't think it's too crazy to just install the required runtime and then not have to worry any more...

**Comment by BSarmady** [comment]
It was a suggestion, didn't mean to sound like a bug! not sure how to remove or add tags to issues.

However, it is alright, I compiled to code myself and included it in, the whole thing become a little bigger, then compiled it with .NET 4 into a single exe file with just 1.2 meg in size, and even become faster.

**Comment by monkeyman192** [comment]
FWIW we used to release the exe as .net 4 then migrated to .net 5. There is discussion [here](#480 ) about migrating to .net 6 for better LTS.
Anyway, sounds like you have it sorted so I'll close this 😄
