### ISSUE TITLE
MBINCompiler 4.0.0.2 error_log

### ISSUE THREAD

**Issue by Pavaros** [monkeyman192/MBINCompiler#512]
[MBINCompiler 4.0.log](https://github.com/monkeyman192/MBINCompiler/files/9742235/MBINCompiler.4.0.log)

**Comment by monkeyman192** [comment]
You need to provide more info (don't just delete the default text in issues! It's there for a reason!)
Are you decompiling a vanilla file? It doesn't look like it, and if you are trying to decompile a file modified by a previous version then this error is expected

**Comment by monkeyman192** [comment]
Since I haven't heard anything I am going to assume this is not an issue and close it.
