### ISSUE TITLE
GCGAMEPLAYGLOBALS.GLOBAL.EXML::CommonSettingsData has a default array of length 27, but MBINCompiler expects length 2.

### ISSUE THREAD

**Issue by MarximusMaximus** [monkeyman192/MBINCompiler#518]
**Describe the bug**
MBINCompiler now complains about an array length that is from the original EXML file. (No mods are updating this array.) Prior version did not (approx two days ago), MBINCompilerVersion.txt from AMUMSS reports current as "4.3.0.2", but I don't know what the prior one was. I always allow AMUMSS to update, and have been running it basically daily, so it should be very close to that.

   [[ERROR]] MBINCompiler = [ExmlException]: CommonSettingsData: XML array size 27 doesn't match expected array size 2 OR check your script!
    [PSARC] The PAK will not include this EXML
    [ERR]   MBINCompiler = You might have added/removed an item from an array field
    [ERR]   MBINCompiler = (arrays can't be shortened or extended as they're a fixed size set by the game)
    [ERR]   MBINCompiler =   [ArraySizeException]
    [ERR]   MBINCompiler =   [INFO]: Z:\AMUMSS\MODBUILDER\MOD\GCGAMEPLAYGLOBALS.GLOBAL.EXML

**Expected behavior**
MBINCompiler does not complain about an array whose size has not been modified from the original file.

**Steps To Reproduce**
1) Extract GCGAMEPLAYGLOBALS.GLOBAL.EXML file from game
2) Attempt to compile that file with MBINCompiler.
3) Error occurs.

**Specs (please complete the following information, if applicable):**
AMUMSS:
  MasterVersion = [4.0.0W]
 CurrentVersion = [4.0.0.7W]
libMBIN Product Version: 4.03.0.2
NMS.exe Product Version 29052.0.0.0, Build ID: 9677936

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/9781339/REPORT.txt)

**Comment by HolterPhylo** [comment]
Hi
Completely delete MODBUILDER/_TEMP folder, that should clear this problem

**Comment by MarximusMaximus** [comment]
This + auto-update of AMUMSS + MBINCompiler today seems to have fixed this one. Thank you!
