### ISSUE TITLE
Some files are not converted.

### ISSUE THREAD

**Issue by Polmorlor** [monkeyman192/MBINCompiler#537]
Hello

I updated NMS a few days ago.
I unpacked the new game files. 2x
I downloaded the latest version of the compiler.
Most files are converted. Unfortunately not all.

I attached 3 examples. Maybe there is more. 
(GCDEBUGOPTIONS.GLOBAL.MBIN, 
GCPLAYERGLOBALS.GLOBAL.MBIN, 
GCAISPACESHIPGLOBALS.GLOBAL.MBIN)

I have tested various previous Compiler releases. All with the same result.
On Nexus you can see that other players don't seem to have the problem. But I can't get any further.

best regards
Polmorlor

[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/10303518/MBINCompiler.log)

**Comment by monkeyman192** [comment]
You do not have the latest MBINCompiler version. See in the log where it says `[VERSION]: MBINCompiler v3.98.0.1`
Here is the latest: https://github.com/monkeyman192/MBINCompiler/releases/tag/v4.06.0-pre1
