### ISSUE TITLE
Suspicious Values in Decompiled EXML

### ISSUE THREAD

**Issue by ianm32** [monkeyman192/MBINCompiler#54]
I saw in the Discord that suspicious values that looked wrong in decompiled MBINS were being reported.

UI\HUD\SHIP\MAINSCREEN.MBIN, at line 211 (and a couple other after) the Alpha value is being shown as "1E-05," which doesn't seem like a correct value for that type of field.

**Comment by monkeyman192** [comment]
ok, finally got around to looking at it. Everything looks fine. The value is just that small... Seems kind of weird, but that's what the mbin has...
