### ISSUE TITLE
MbinException

### ISSUE THREAD

**Issue by Smuggl** [monkeyman192/MBINCompiler#544]
With MBinCompiler v4.10.0-pre1 I get the following error when trying to convert GCSPACESHIPGLOBALS.GLOBAL.MBIN to EXML

[ERROR]: [MbinException]: Exception has been thrown by the target of an invocation.

It doesn't tell which exception.

**Comment by Yiril04** [comment]
Yep, this issue is on my side aswell. Any other MBIN file gets converted without issues, but this one MBIN file seems to be "out of reach"
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/10845276/MBINCompiler.log)

**Comment by Yiril04** [comment]
v4.10.0-pre2 fixes it, it can now decompile GCSPACESHIPGLOBALS.GLOBAL.MBIN aswell!

**Comment by Smuggl** [comment]
Confirmed!
