### ISSUE TITLE
Unable to read data from outside of the end of the stream.

### ISSUE THREAD

**Issue by gregus1234** [monkeyman192/MBINCompiler#57]
I'm trying to decompile previously compiled mbin file and i get that error every time. I'm using the latest version of mbincompiler.

C:\Users\Grzesiek\Desktop\XMM v4-751-0-4-beta>mbincompiler "C:\Users\Grzesiek\De
sktop\XMM v4-751-0-4-beta\Pcbanki\UltraFix Mod\GCENVIRONMENTGLOBALS.GLOBAL.MBIN"

ERROR: An unknown exception occurred!
Unable to read data from outside of the end of the stream.
Stacktrace:
   w System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   w System.IO.BinaryReader.ReadSingle()
   w libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   w libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   w libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   w libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   w libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   w libMBIN.Models.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   w libMBIN.Models.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   w libMBIN.MBINFile.GetData()
   w MBINCompiler.Program.DecompileFile(String inputPath, String outputPath, Boolean getVersion, Boolean verbose)
   w MBINCompiler.Program.Main(String[] args)

Press any key

**Comment by monkeyman192** [comment]
I just decompiled the most recent version from steam (experimental) with the most recent version of mbincompiler and it worked fine??

**Comment by D-A-R-K-N-E-S-S** [comment]
Ditto what monkeyman192 said....decompiled fine (latest experimental + MBIN Compiler).

**Comment by monkeyman192** [comment]
oh, that is a good point... I can't test right now, but if you could check that the recompiled mbin is the same size as the vanilla one that would be good.

**Comment by gregus1234** [comment]
Sorry about that. I didn't knew I have to use a older version mbincompiler. I didn't saw that a mod which i'm trying to decompile was for 8 months outdated and like a idiot I thought it was something wrong with your decompiler. Sorry again.

**Comment by monkeyman192** [comment]
No worries. You can see in the (non-vanilla) mbin file the version required to open it ;)
Will close this issue then.
