### ISSUE TITLE
mbin switch

### ISSUE THREAD

**Issue by czdvoika** [monkeyman192/MBINCompiler#575]
hey can you please check out mbin for nintendo switch? here is :)

https://drive.google.com/file/d/1HMiw020lbFAB5GfboUNYEVgQ6d_-qaEk/view?usp=sharing

```
[WARN]: File not recognized. You may need to use an older (or newer) version of MBINCompiler.
  [INFO]: C:\Users\dvoika\Desktop\nomansky_uprava\texty\nms_update3_english.mbin
  [INFO]: MBIN	version:	0.0.0.0	guid:	5627895BB950EF14	template:	cTkLocalisationTable
  [EXPECTED INFO]: GUID: A27983F991070A43
```

**Comment by czdvoika** [comment]
Helooo :-D

**Comment by czdvoika** [comment]
just change the header and it reads :)

**Comment by monkeyman192** [comment]
I'm not really sure what you want here! 😅
This just means you are using the wrong mbincompiler version for the file...

**Comment by czdvoika** [comment]
yeah because the compiler doesn't recognize nintendo switch mbin :D
