### ISSUE TITLE
Many lines of code are missing for "GcGameplayGlobals"

### ISSUE THREAD

**Issue by BradfordCB** [monkeyman192/MBINCompiler#584]
![GcGameplayGlobals missing code 1](https://github.com/monkeyman192/MBINCompiler/assets/47071970/11060dfc-a1c2-48e1-b942-9207181a18d9)
![GcGameplayGlobals missing code 2](https://github.com/monkeyman192/MBINCompiler/assets/47071970/034bc60d-eaee-4a54-a68f-54808e2708c7)
I tried to find setting that I wanted to moddify in GcGameplayGlobals version 4.50 and noticed that 50 or more line of code are missing compared to version 4.47. Below are some lines of code that I wanted to modify, but they are missing. Did they get moved to another section?

**Comment by monkeyman192** [comment]
This is normal when updates happen. See the commit where this changed here: https://github.com/monkeyman192/MBINCompiler/commit/c048e20b5ebbfbc0fce2de20fd7461145a7d02a2#diff-e5c7aa6d4decd93d07293e6d04ab5c046e039d1f4b415721821fdc699dcd0345
