### ISSUE TITLE
Can't recompile File

### ISSUE THREAD

**Issue by EmSay91** [monkeyman192/MBINCompiler#608]
Hi, I have this problem when I try to recompile the file (DAMAGETABLE.EXML) from no man's sky,

I don't get why this specific file fail to recompile as it is the original one.
Here is the error log.

[VERSION]: MBINCompiler v5.1.0.1
[ARGS]: "N:\Downloads\ModsNMS\AMUMSS\TOOLS\NMSPE_Output\DEFAULT_EXMLsaveFOLDER\METADATA\REALITY\TABLES\DAMAGETABLE.EXML"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=EXML
[INFO]: --input-format=EXML --output-format=MBIN
[INFO]: N:\Downloads\ModsNMS\AMUMSS\TOOLS\NMSPE_Output\DEFAULT_EXMLsaveFOLDER\METADATA\REALITY\TABLES\DAMAGETABLE.EXML

[ERROR]: [ExmlException]: Object reference not set to an instance of an object.
[NullReferenceException]

[INFO]: N:\Downloads\ModsNMS\AMUMSS\TOOLS\NMSPE_Output\DEFAULT_EXMLsaveFOLDER\METADATA\REALITY\TABLES\DAMAGETABLE.EXML

   at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   at libMBIN.NMSTemplate.DeserializeEXml(EXmlBase xmlData)
   at libMBIN.EXmlFile.ReadTemplateFromXmlReader(XmlReader reader, String& templateName)
   at libMBIN.EXmlFile.ReadTemplateFromStream(Stream input, String& templateName)
   at MBINCompiler.Commands.Convert.ConvertEXML(String inputPath, FileStream fIn, MemoryStream msOut, String fileOut)

**Comment by monkeyman192** [comment]
This is known. As the release notes say, please look at the test report before reporting broken files.
A new version which fixes this should however be up later today.
