### ISSUE TITLE
Fails to decompile ATLASPATHTABLE and RECURRINGMISSIONTABLE MBIN files

### ISSUE THREAD

**Issue by AdamWelch1** [monkeyman192/MBINCompiler#620]
**Describe the bug**
After NMS updated from 5.05 to 5.10, I tried to recompile the mods I have been using with AMUMSS. Of the 15 mod lua scripts I'm using, only 1 is failing to compile. Based on what I'm seeing in the REPORT.lua file, this is because MBINCompiler is failing to decompile ATLASPATHTABLE.MBIN and RECURRINGMISSIONTABLE.MBIN.

Here is the relevant output from REPORT.lua:

> Starting to process script #8/15 [[Firmware Update for the Signal Booster AIO.lua]] {
>     'Prompt' [[    Choose a cost option:
>     0 - No cost
>     1 - Cost of 1 NAVDATA
>     2 - Cost of 3 NAVDATA
>     3 - Cost of 5 NAVDATA
>     4 - Cost of 10 NAVDATA
>     Default = 0 | Current = >> 0 <<
> ]]: [0] (default)
>     'Prompt' [[Do you want aerial scans (flyup when scan is initiated)?  Default = N.  Press ENTER for default value.]]: [N] (default)
>     ^^^^^^^^ Done running script internal code in 8.364 sec
> >>> Including lua script source in pak
> >>> Mod by Lowkie & Babscoole version 5.05
> Switched to 'most recent' MBINCompiler 5.12.0.1
> Switched back to declared 'public' MBINCompiler 5.11.0.1
> Trying to decompile... 
> Trying to decompile... 
> 
>    [[ERROR]] MBINCompiler = [MbinException]: There was an error generating the XML document => check your script!
>     [PSARC] The PAK will not include this EXML
>     [ERR]   MBINCompiler =   [InvalidOperationException]
>     [ERR]   MBINCompiler =   [ArgumentException]: '.', hexadecimal value 0x00, is an invalid character.
>     [ERR]   MBINCompiler =   [INFO]: C:\Users\AJ\Documents\AMUMSS\MODBUILDER\MOD\METADATA\SIMULATION\MISSIONS\ATLASPATHTABLE.MBIN
>     [ERR]   MBINCompiler =   [INFO]: MBIN	version:	0.0.0.0	guid:	ECD9B0D8878E3AD3	template:	GcMissionTable
>     [ERR]   MBINCompiler = [ERROR]: [MbinException]: There was an error generating the XML document.
>     [ERR]   MBINCompiler =   [InvalidOperationException]
>     [ERR]   MBINCompiler =   [ArgumentException]: '.', hexadecimal value 0x00, is an invalid character.
>     [ERR]   MBINCompiler =   [INFO]: C:\Users\AJ\Documents\AMUMSS\MODBUILDER\MOD\METADATA\SIMULATION\MISSIONS\RECURRINGMISSIONTABLE.MBIN
>     [ERR]   MBINCompiler =   [INFO]: MBIN	version:	0.0.0.0	guid:	ECD9B0D8878E3AD3	template:	GcMissionTable
>    [[NOTICE]]     Currently, due to the way MBINCompiler logging works
>    [[NOTICE]]     it is impossible to exactly pinpoint the problem to a particular processed file above

**Expected behavior**

The MBIN files should be decompiled without errors.

**Steps To Reproduce**
1. Download the attached LUA script and place it in the ModScripts folder in the AMUMSS directory
2. Run BUILDMOD.bat

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: Seems to be 5.11.0.1
 - Steam build ID: 15615514
 - MBIN File: Listed in above error output

_Attachments:_
[Firmware Update for the Signal Booster AIO.lua.txt](https://github.com/user-attachments/files/17004020/Firmware.Update.for.the.Signal.Booster.AIO.lua.txt)
[REPORT.lua.txt](https://github.com/user-attachments/files/17004021/REPORT.lua.txt)

Note: Please change the mod file extension from .txt to .lua. Github does not permit uploading .lua files.

**Comment by monkeyman192** [comment]
These files are not supported. You need to decompile the files which are under the `TABLES` sub-directory of the `MISSIONS` folder. Other people will have had this issue so ask in the AMUMSS channel on the modding discord for more help there.
