### ISSUE TITLE
Game crashes afte modifying OXYGENHARVESTER.ENTITY.MBIN

### ISSUE THREAD

**Issue by deogo** [monkeyman192/MBINCompiler#63]
file
MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\TECH\OXYGENHARVESTER180\ENTITIES\OXYGENHARVESTER.ENTITY.MBIN
decomplie/recompile it without changes, pack it into mod
trying to place oxygen harvester in-game - game crashes
latest NMS Modding Station.exe/MBINCompiler.exe

**Comment by Fuzzy-Logik** [comment]
Recompiled v1.58 MBIN file is identical except for Tag and MBINVersion header fields.
