### ISSUE TITLE
MBIN compiles with one wrong symbol and breaks the mod

### ISSUE THREAD

**Issue by Dr-Kerke** [monkeyman192/MBINCompiler#66]
Hi Guys,
**First off, amazing work! Thank you so much!**

**Describe the bug**
Came across this when I was modifying ship landing gear animations. It doesn't happen with all **LANDINGGEAR.ENTITY.MBIN** files (royal landing gear compiles fine), but it specifically occurs with the scientific/explorer ship landing gear file, so far (that I'm aware of). **MODELS\COMMON\SPACECRAFT\SCIENTIFIC\ACCESSORIES\LANDINGGEAR\LANDINGGEAR_POD\ENTITIES\LANDINGGEAR.ENTITY.MBIN**
Namely, the file decompiles to EXML without problems, however once you recompile it back into an MBIN file it generates with a single wrong symbol at a specific location **0D0** line in the HEX Editor (8 byte mode) even without any changes. Instead of the carrot symbol **(ˆ)** [value 88] the MBIN compiles with the lower quotes symbol **(„)** [value 84]. (image attached)
I don't know much about hex editing but this basically breaks the animation ingame so that the landing gear is always extended for all explorer ships (during flight, take off, and landing).
After I changed the value in Notepad ++ into what it was supposed to be and saved the MBIN like that, the mod worked flawlessly.
I'm guessing there is some misstep in the translation process during compilation that converts this one byte into the wrong symbol (couldn't be due to some arbitrary system language/keyboard settings, right?).

**Expected behavior**
The MBIN was supposed to recompile back the same way it decompiled but instead the process changes this one symbol.

**Steps To Reproduce**
1. Go to 'MODELS\COMMON\SPACECRAFT\SCIENTIFIC\ACCESSORIES\LANDINGGEAR\LANDINGGEAR_POD\ENTITIES\'
2. Decompile the 'LANDINGGEAR.ENTITY.MBIN'
3. Recompile the 'LANDINGGEAR.ENTITY.EXML' back into 'LANDINGGEAR.ENTITY.MBIN' in another location
4. Compare the original 'LANDINGGEAR.ENTITY.MBIN' with the new recompiled one and see the difference at line 0D0

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: [1.57.0.2]
 - NMS Game Version or Steam Build Number: [1.57 build: 3034427]
 - MBIN File: [LANDINGGEAR.ENTITY.MBIN]
 - MBIN File Version: [1.57.0.2]

**Additional Information**
Add any other information here that you think might be helpful.

_Attachments:_
Screenshot of a diff comparison of the original and recompiled MBINs
![screen-2018-08-24_16-42-32](https://user-images.githubusercontent.com/42676197/44592579-48ff0780-a7c1-11e8-9bde-ed19f201d539.jpg)

Just hope any of this helps. :)

**Comment by monkeyman192** [comment]
Thanks for the very detailed error report! Issue is now solved and will be in the next release :)

**Comment by Dr-Kerke** [comment]
Any time. :) Awesome! Thanks.
