### ISSUE TITLE
COSTTABLE.MBIN ingame bug

### ISSUE THREAD

**Issue by DarkWater666** [monkeyman192/MBINCompiler#69]
METADATA\REALITY\TABLES\COSTTABLE.MBIN
Even without modify anything, decompile/recompile, it will be 28.6KB instead of 29KB. Also have problems with finding the coordinates in the game, all options are inactive with recompiled original file in .pak.

_i try with various versions. 58, 57, 55, 53, 52, 38_

**Comment by TheBob12** [comment]
Looked through all the files with names such as GcCost... I found a few things that I think are weird. Some places in the mbincompiler, strings are defined with size 0x10 where other places the same string is defined as 0x20

Example: GcCostBuildingParts
        [NMS(Size = 0x10)]
        public string Description;

in IDA that one is callign the same sub as CostStringCanAfford ( [NMS(Size = 0x20)] ) in GcCostStatCompare
In GcTestMetaData this is TestLocID, which is 0x20 bytes.

There's a struct, GcCostFrigateCargo, that's 0x1 in size, but in the mbincompiler this struct is completely empty, not even padding. I can't find anything in IDA that takes up that 1 byte.

**Comment by Fuzzy-Logik** [comment]
resolved in commit 3f2880493f1cd78149a105d65bf9984be09e33ac
