### ISSUE TITLE
NMS_TESTREALITY_GCPRODUCTTABLE doesn't decompile (but NMS_REALITY & NMS_U3REALITY do)

### ISSUE THREAD

**Issue by theFisher86** [monkeyman192/MBINCompiler#73]
**Describe the bug**
Title says it all

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 1.53.0
 - NMS Game Version or Steam Build Number: Experimental 1.58
 - MBIN File: NMS_TESTREALITY_GCPRODUCTTABLE.MBIN

**Comment by Fuzzy-Logik** [comment]
The TESTREALITY files use an outdated format and are not maintained by HG.
They cannot be de/compiled for newer versions.
