### ISSUE TITLE
Failed to decompile GCPLAYERGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by WTM-Tech** [monkeyman192/MBINCompiler#88]
**Describe the bug**
MBINCompiler failed to decompile the GCPLAYERGLOBALS.GLOBAL.MBIN to the exml file from the recent patch.  MBINCompiler process exits fine and generates a log file.

**Expected behavior**
Expected compiler to generate exml file.

**Steps To Reproduce**
1. Drag and drop to MBINCompiler.exe or Decompile through NMS Mod Workstation
2. MBINCompiler seems to exit fine but doens't generate exml file.
3. Log file attached with specific details

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 1.5.8.0
 - NMS Game Version or Steam Build Number: 1.5.9  (PC 2018-09-06 update)
 - MBIN File: GCPLAYERGLOBALS.GLOBAL.MBIN
 - MBIN File Version: 1.5.9

Attachments:
[MBINCompiler.log](https://github.com/monkeyman192/MBINCompiler/files/2363371/MBINCompiler.log)

**Comment by monkeyman192** [comment]
Hi, have a look and see if the most recent release fixes this issue. I believe it does, so I'll close this but post if for some reason it hasn't :)

**Comment by WTM-Tech** [comment]
Looks like it is working fine now.  Just built a test MOD with it and the changes appear to be working in game as expected.

--  Thanks for all your hard work and time.
