### ISSUE TITLE
Recompiled Loot Drop entities removes rewards from sentinel loot caches

### ISSUE THREAD

**Issue by trevizor** [monkeyman192/MBINCompiler#95]
Decompiling and recompiling the LootDrop entities disables the sentinel rewards.
It seems this also causes the game to crash sometimes.

Attached are the entity files that causes issues.
[MODELS-COMMON-ROBOTS-LOOTDROP.zip](https://github.com/monkeyman192/MBINCompiler/files/2403518/MODELS-COMMON-ROBOTS-LOOTDROP.zip)

MBIN COMPILER: v1.59.0-pre2
NMS: 1.60 (1.59.x as well)

**Comment by monkeyman192** [comment]
I tried one of the drone entities you attached and it recompiles perfectly for me 0 difference when doing a byte-wise comparison... (that's with 1.59.0-pre2)
Haven't look at other files yet...
(posted this in the wrong issue before, sorry!)

edit:
The other two look good. I can't see a single difference between the vanilla and recompiled files with no changes.

**Comment by monkeyman192** [comment]
I think this was a non-issue. Will close but let me know if you are still having issues
