### ISSUE TITLE
Trying to decompile GCSPACESHIPGLOBALS.GLOBAL.MBIN crashed MBINCompiler

### ISSUE THREAD

**Issue by Galenmacil** [monkeyman192/MBINCompiler#96]
Using MBINCompiler 1.61.0-pre2 with official Steam NMS version 1.61

Console output:

mbincompiler "C:\Fred\NMS Modding Station\Projects\Ship Hovering\GCSPACESHIPGLOBALS.GLOBAL.MBIN"
Auto-Detected --input-format=MBIN
Converting C:\Fred\NMS Modding Station\Projects\Ship Hovering\GCSPACESHIPGLOBALS.GLOBAL.MBIN

[ERROR]: [MbinException]: Failed to read GcSpaceshipGlobals from MBIN.

Press any key to continue . . .

Note that the same things also happen for file GCGAMEPLAYGLOBALS.GLOBAL.MBIN.

**Comment by monkeyman192** [comment]
I think you are possibly using an older version of the game files.
I just checked the current release (`1.61.0-pre2`) and it decompiles the most recent NMS Build (ID `3180166`) completely fine.
