### ISSUE TITLE
Update 1.64 breaks NMS_DIALOG_ALIENPUZZLETABLE

### ISSUE THREAD

**Issue by MuteButtonHero** [monkeyman192/MBINCompiler#99]
HG dropped 1.64 about 5am my time. Good Morning! XD

\METADATA\REALITY\TABLES\NMS_DIALOG_GCALIENPUZZLETABLE.MBIN from 1.64 won't decompile under current or past MBINCompilers. Old versions crash the game.

FYI, I had no issues with 
GCGRAPHICSGLOBALS.GLOBAL.MBIN
GCPLAYERGLOBALS.GLOBAL.MBIN
LANGUAGE\NMS_LOC1_ENGLISH.MBIN
LANGUAGE\NMS_UPDATE3_ENGLISH.MBIN
It looks like they just added or changed values in those. Those are the only ones I had to touch for this update. 

As always, thanks for your work on this.

**Comment by monkeyman192** [comment]
1.64 didn't change this file.
Just to check I ran the most recent version on the alien puzzle table and it recompile perfectly (only the expected 6 bytes of difference in the header). So I certainly can't recreate this issue sorry...

**Comment by MuteButtonHero** [comment]
I just went back and carefully unpacked the whole game again. Then I ran Kdiff against that directory and the same directory from 1.63 and it told me that was the one file that did change.

I tried MBINCompiler1.63p4 and got the log that is attached.  If I include NMS_DIALOG_GCALIENPUZZLETABLE.MBIN from 1.63, completely unmodified, in a .pak and try to run it the game crashes on startup.  If I'm misunderstanding something I apologize. But it looks to me like it did change. 
[MBINCompiler1_63_4.log](https://github.com/monkeyman192/MBINCompiler/files/2475202/MBINCompiler1_63_4.log)

**Comment by monkeyman192** [comment]
can you upload the mbin? I can see what version you have compared to what the struct is written for...

**Comment by MuteButtonHero** [comment]
MBIN attached.

**Comment by MuteButtonHero** [comment]
Attached.  I had to zip it for upload.
[NMS_DIALOG_GCALIENPUZZLETABLE.zip](https://github.com/monkeyman192/MBINCompiler/files/2477669/NMS_DIALOG_GCALIENPUZZLETABLE.zip)

**Comment by MuteButtonHero** [comment]
FYI, this is still an issue in 1.65, at least for me.  Which makes sense; Kdiff tells me this file did not change from 1.64 to 1.65.

**Comment by monkeyman192** [comment]
I still can't replicate this. Doing a decompile/recompile of the file you sent and then comparing I get identical files:
```
T:\NMS modding\NMS-1.65>fc /B NMS_DIALOG_GCALIENPUZZLETABLE_O.MBIN NMS_DIALOG_GCALIENPUZZLETABLE.MBIN
Comparing files NMS_DIALOG_GCALIENPUZZLETABLE_O.MBIN and NMS_DIALOG_GCALIENPUZZLETABLE.MBIN
00000006: 00 02
00000008: 00 01
00000009: 00 40
0000000C: 00 01
0000000D: 00 40
0000000F: 00 01
```
Maybe I fixed it since the last public release? I'll upload the most recent version now as it definitely fixes this issue...

**Comment by monkeyman192** [comment]
https://github.com/monkeyman192/MBINCompiler/releases/tag/v1.65.0-pre1 should fix this

**Comment by MuteButtonHero** [comment]
Yup, problem solved! Thank you thank you thank you!

Hey, looking over how I started this thread I tried to share a laugh with you over how often HG drops updates and how it makes us a little both a little crazy. But instead it just looks kinda dickish. Sorry about that. Humor doesn't always work in text form.

Know I'm a big fan of the work you do and intend only respect.

**Comment by monkeyman192** [comment]
No worries, I can tell it was humor :)
I think I was in a rush when I replied initially hence the short reply :P
The updates drop at a similar time in my region so I often wake up to a "HG broke everything", monkeyman please fix!!! lol
